// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.
// prettier-ignore
export const NATIVE_KNOWLEDGE_READ_ACTIONS = Object.freeze(["cloud_conflict_context", "configuration", "entities", "failed_index", "failed_processing", "get", "list", "pending_resolutions", "processing_audits", "pull_conflict_context", "pull_conflicts", "push_conflicts", "reconciliation_context", "relationships", "remote_baseline", "resolution", "resolution_by_key", "resolution_history", "resolutions", "semantic", "sync_outbox", "sync_status", "text", "view"] as const);
// prettier-ignore
export const NATIVE_KNOWLEDGE_WRITE_ACTIONS = Object.freeze(["configure_embedding", "create", "delete", "index_one", "process_one", "promote_index", "reconcile_resolution", "resolve_pull", "resolve_push", "resume_resolution", "retry_index", "select_embedding", "sync_link", "sync_pull", "sync_push", "update"] as const);
