// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.
import type { Id, NativeKnowledgeAppliedReceipt, NativeKnowledgeAuditSummary, NativeKnowledgeCapabilityEntry, NativeKnowledgeChange, NativeKnowledgeCloudContext, NativeKnowledgeCloudGeneration, NativeKnowledgeCloudOutcome, NativeKnowledgeCloudResolution, NativeKnowledgeCommunityAuditSummary, NativeKnowledgeCommunityBuildHistoryPage, NativeKnowledgeCommunityBuildPage, NativeKnowledgeCommunityBuildReceipt, NativeKnowledgeCommunityBuildStatus, NativeKnowledgeCommunitySelection, NativeKnowledgeEmbeddingConfiguration, NativeKnowledgeGraphPullResolution, NativeKnowledgeIndexCoverage, NativeKnowledgeIndexFailureDetail, NativeKnowledgeIndexReceipt, NativeKnowledgeIndexSource, NativeKnowledgeJson, NativeKnowledgeLink, NativeKnowledgeLocalReceipt, NativeKnowledgeMemory, NativeKnowledgeMutationMemory, NativeKnowledgeMutationResult, NativeKnowledgeProcessingCoverage, NativeKnowledgeProcessingFailureDetail, NativeKnowledgeProcessingReceipt, NativeKnowledgeProcessingSource, NativeKnowledgeProcessingTaskSnapshot, NativeKnowledgePullConflict, NativeKnowledgePullContext, NativeKnowledgePullResolution, NativeKnowledgePushConflict, NativeKnowledgeReconciliation, NativeKnowledgeRemote, NativeKnowledgeResolutionRecord, NativeKnowledgeRetrievalCursor, NativeKnowledgeRetrievedEntity, NativeKnowledgeRetrievedRelationship, NativeKnowledgeScope, NativeKnowledgeSemanticHit, NativeKnowledgeSourceGraph, NativeKnowledgeStatus, NativeKnowledgeStoredMemory, NativeKnowledgeSyncedGraphProjection, NativeKnowledgeTextHit, NativeKnowledgeUnbindPolicy, Page, ResolutionId } from './nativeKnowledgeDataGenerated';

// prettier-ignore
export type NativeKnowledgeRequestMap = {
  readonly get: Id;
  readonly create: {
    readonly memory: NativeKnowledgeMutationMemory;
    readonly idempotency_key: string;
  };
  readonly update: {
    readonly memory: NativeKnowledgeMutationMemory;
    readonly expected_revision: number;
    readonly idempotency_key: string;
  };
  readonly delete: {
    readonly id: string;
    readonly expected_revision: number;
    readonly idempotency_key: string;
  };
  readonly sync_status: Readonly<Record<never, never>>;
  readonly sync_link: {
    readonly link: NativeKnowledgeLink;
  };
  readonly sync_push: Readonly<Record<never, never>>;
  readonly sync_pull: Readonly<Record<never, never>>;
  readonly sync_unbind: {
    readonly policy: NativeKnowledgeUnbindPolicy;
  };
  readonly sync_outbox: {
    readonly limit: number;
    readonly after_sequence: number;
  };
  readonly remote_baseline: Id;
  readonly push_conflicts: Page;
  readonly pull_conflicts: Page;
  readonly pull_conflict_context: Id;
  readonly resolution_history: {
    readonly id: string;
    readonly limit: number;
  };
  readonly resolve_pull: {
    readonly resolution: NativeKnowledgePullResolution;
    readonly idempotency_key: string;
  };
  readonly cloud_conflict_context: {
    readonly local_sequence: number;
  };
  readonly resolve_push: {
    readonly resolution: NativeKnowledgeCloudResolution;
    readonly idempotency_key: string;
  };
  readonly resume_resolution: ResolutionId;
  readonly reconcile_resolution: {
    readonly resolution_id: string;
    readonly reconciliation: NativeKnowledgeReconciliation;
  };
  readonly resolution: ResolutionId;
  readonly resolution_by_key: {
    readonly idempotency_key: string;
  };
  readonly resolutions: Page;
  readonly pending_resolutions: {
    readonly limit: number;
    readonly before_resolution_id?: (string) | (null);
  };
  readonly reconciliation_context: ResolutionId;
  readonly graph_pull_conflicts: Page;
  readonly graph_push_conflicts: Page;
  readonly graph_pull_conflict_context: Id;
  readonly graph_resolution_history: {
    readonly id: string;
    readonly limit: number;
  };
  readonly remote_graph_baseline: Id;
  readonly synced_graph_projection: Id;
  readonly synced_graph_projections: {
    readonly limit: number;
    readonly offset: number;
  };
  readonly resolve_graph_pull: {
    readonly resolution: NativeKnowledgeGraphPullResolution;
    readonly idempotency_key: string;
  };
  readonly resolve_graph_push: {
    readonly conflict_id: string;
    readonly change_id: string;
    readonly expected_current_revision: number;
    readonly decision: "keep_current" | "use_proposed" | "merged" | "keep_both";
    readonly content: (NativeKnowledgeJson) | (null);
  };
};

// prettier-ignore
export type NativeKnowledgeResultMap = {
  readonly get: {
    readonly memory: NativeKnowledgeStoredMemory;
  };
  readonly create: NativeKnowledgeMutationResult;
  readonly update: NativeKnowledgeMutationResult;
  readonly delete: NativeKnowledgeMutationResult;
  readonly sync_status: {
    readonly status: NativeKnowledgeStatus;
  };
  readonly sync_link: {
    readonly status: NativeKnowledgeStatus;
    readonly association_state: "configured";
    readonly remote_authorization: "unverified";
  };
  readonly sync_push: ({
    readonly local_sequence: number;
    readonly replayed: boolean;
    readonly receipt: (NativeKnowledgeAppliedReceipt) | ({
      readonly [key: string]: NativeKnowledgeJson;
      readonly status: "conflict";
      readonly change_id: string;
      readonly conflict_id: string;
    });
  }) | (null);
  readonly sync_pull: {
    readonly next_cursor: number;
    readonly applied: number;
    readonly conflicts: number;
    readonly has_more: boolean;
  };
  readonly sync_unbind: {
    readonly status: NativeKnowledgeStatus;
    readonly association_state: "unbound";
    readonly policy: NativeKnowledgeUnbindPolicy;
    readonly fenced_outbox: number;
    readonly removed_local_copies: number;
  };
  readonly sync_outbox: {
    readonly items: readonly ({
      readonly change_id: string;
      readonly local_change: {
        readonly sequence: number;
        readonly memory: NativeKnowledgeMemory;
        readonly deleted: boolean;
      };
    })[];
    readonly next_sequence: number;
  };
  readonly remote_baseline: {
    readonly version: (NativeKnowledgeRemote) | (null);
  };
  readonly push_conflicts: {
    readonly items: readonly (NativeKnowledgePushConflict)[];
  };
  readonly pull_conflicts: {
    readonly items: readonly (NativeKnowledgePullConflict)[];
  };
  readonly pull_conflict_context: {
    readonly context: (NativeKnowledgePullContext) | (null);
  };
  readonly resolution_history: {
    readonly items: readonly ({
      readonly request: NativeKnowledgePullResolution;
      readonly receipt: NativeKnowledgeLocalReceipt;
      readonly archive: NativeKnowledgePullContext;
    })[];
  };
  readonly resolve_pull: {
    readonly receipt: NativeKnowledgeLocalReceipt;
    readonly replayed: boolean;
  };
  readonly cloud_conflict_context: {
    readonly context: NativeKnowledgeCloudContext;
  };
  readonly resolve_push: NativeKnowledgeCloudOutcome;
  readonly resume_resolution: NativeKnowledgeCloudOutcome;
  readonly reconcile_resolution: NativeKnowledgeCloudOutcome;
  readonly resolution: {
    readonly record: NativeKnowledgeResolutionRecord;
  };
  readonly resolution_by_key: {
    readonly record: (NativeKnowledgeResolutionRecord) | (null);
  };
  readonly resolutions: {
    readonly items: readonly (NativeKnowledgeResolutionRecord)[];
  };
  readonly pending_resolutions: {
    readonly items: readonly (NativeKnowledgeResolutionRecord)[];
    readonly next_before_resolution_id: (string) | (null);
  };
  readonly reconciliation_context: {
    readonly context: NativeKnowledgeCloudContext;
  };
  readonly graph_pull_conflicts: {
    readonly items: readonly (NativeKnowledgeJson)[];
  };
  readonly graph_push_conflicts: {
    readonly items: readonly (NativeKnowledgeJson)[];
  };
  readonly graph_pull_conflict_context: {
    readonly context: (NativeKnowledgeJson) | (null);
  };
  readonly graph_resolution_history: {
    readonly items: readonly (NativeKnowledgeJson)[];
  };
  readonly remote_graph_baseline: {
    readonly version: (NativeKnowledgeJson) | (null);
  };
  readonly synced_graph_projection: {
    readonly projection: (NativeKnowledgeSyncedGraphProjection) | (null);
  };
  readonly synced_graph_projections: {
    readonly items: readonly (NativeKnowledgeSyncedGraphProjection)[];
  };
  readonly resolve_graph_pull: {
    readonly receipt: NativeKnowledgeJson;
    readonly replayed: boolean;
  };
  readonly resolve_graph_push: {
    readonly receipt: NativeKnowledgeJson;
    readonly replayed: boolean;
  };
};

// prettier-ignore
export type NativeKnowledgeRetrievalRequest = {
  readonly source?: (NativeKnowledgeProcessingSource) | (null);
  readonly cursor?: (NativeKnowledgeRetrievalCursor) | (null);
  readonly limit: number;
};

// prettier-ignore
export type NativeKnowledgeProcessingQueryMap = {
  readonly configuration: Readonly<Record<never, never>>;
  readonly entities: {
    readonly request: NativeKnowledgeRetrievalRequest;
  };
  readonly relationships: {
    readonly request: NativeKnowledgeRetrievalRequest;
  };
  readonly text: {
    readonly literal: string;
    readonly request: NativeKnowledgeRetrievalRequest;
  };
  readonly semantic: {
    readonly build_id: string;
    readonly config_revision: number;
    readonly query: string;
    readonly limit: number;
  };
  readonly failed_processing: {
    readonly request: NativeKnowledgeDiagnosticRequest;
  };
  readonly failed_index: {
    readonly build_id: string;
    readonly config_revision: number;
    readonly request: NativeKnowledgeDiagnosticRequest;
  };
  readonly processing_audits: {
    readonly source: NativeKnowledgeProcessingSource;
    readonly request: NativeKnowledgeDiagnosticRequest;
  };
  readonly processing_task: {
    readonly source: NativeKnowledgeProcessingSource;
  };
  readonly community_active: Readonly<Record<never, never>>;
  readonly community_build: {
    readonly build_id: string;
    readonly offset: number;
    readonly limit: number;
  };
  readonly community_audit: {
    readonly build_id: string;
    readonly candidate_id: string;
    readonly attempt: number;
  };
  readonly community_builds: {
    readonly offset: number;
    readonly limit: number;
  };
  readonly graph_source: {
    readonly source: NativeKnowledgeProcessingSource;
    readonly expected_audit_attempt: number;
  };
};

// prettier-ignore
export type NativeKnowledgeProcessingResultMap = {
  readonly configuration: {
    readonly configuration: (NativeKnowledgeEmbeddingConfiguration) | (null);
    readonly active_build_id: (string) | (null);
    readonly processing: NativeKnowledgeProcessingCoverage;
    readonly index: (NativeKnowledgeIndexCoverage) | (null);
  };
  readonly entities: {
    readonly items: readonly (NativeKnowledgeRetrievedEntity)[];
    readonly next_cursor: (NativeKnowledgeRetrievalCursor) | (null);
  };
  readonly relationships: {
    readonly items: readonly (NativeKnowledgeRetrievedRelationship)[];
    readonly next_cursor: (NativeKnowledgeRetrievalCursor) | (null);
  };
  readonly text: {
    readonly items: readonly (NativeKnowledgeTextHit)[];
    readonly next_cursor: (NativeKnowledgeRetrievalCursor) | (null);
  };
  readonly semantic: {
    readonly configuration: NativeKnowledgeEmbeddingConfiguration;
    readonly processing: NativeKnowledgeProcessingCoverage;
    readonly index: NativeKnowledgeIndexCoverage;
    readonly hits: readonly (NativeKnowledgeSemanticHit)[];
  };
  readonly failed_processing: {
    readonly items: readonly (NativeKnowledgeProcessingFailureDetail)[];
    readonly next_cursor: (string) | (null);
  };
  readonly failed_index: {
    readonly items: readonly (NativeKnowledgeIndexFailureDetail)[];
    readonly next_cursor: (string) | (null);
  };
  readonly processing_audits: {
    readonly items: readonly (NativeKnowledgeAuditSummary)[];
    readonly next_cursor: (string) | (null);
  };
  readonly processing_task: NativeKnowledgeProcessingTaskSnapshot;
  readonly community_active: {
    readonly selection: NativeKnowledgeCommunitySelection;
    readonly current_status: (NativeKnowledgeCommunityBuildStatus) | (null);
    readonly stale_build_id: (string) | (null);
  };
  readonly community_build: {
    readonly page: (NativeKnowledgeCommunityBuildPage) | (null);
  };
  readonly community_audit: {
    readonly audit: (NativeKnowledgeCommunityAuditSummary) | (null);
  };
  readonly community_builds: {
    readonly page: NativeKnowledgeCommunityBuildHistoryPage;
  };
  readonly graph_source: NativeKnowledgeSourceGraph;
};

// prettier-ignore
export type NativeKnowledgeProcessingCommandMap = {
  readonly configure_embedding: {
    readonly build_id: string;
    readonly provider_id: string;
    readonly provider_revision: number;
    readonly model_id: string;
    readonly expected_config_revision: (number) | (null);
  };
  readonly select_embedding: {
    readonly build_id: string;
    readonly expected_config_revision: (number) | (null);
  };
  readonly index_one: {
    readonly build_id: string;
    readonly config_revision: number;
  };
  readonly promote_index: {
    readonly build_id: string;
    readonly config_revision: number;
    readonly expected_active_build_id: (string) | (null);
  };
  readonly retry_index: {
    readonly build_id: string;
    readonly config_revision: number;
    readonly input: NativeKnowledgeIndexSource;
    readonly expected_attempt: number;
  };
  readonly process_one: {
    readonly workspace_id: string;
  };
  readonly retry_processing: {
    readonly source: NativeKnowledgeProcessingSource;
    readonly expected_attempt: number;
  };
  readonly create_community_build: {
    readonly idempotency_key: string;
    readonly min_community_size: number;
  };
  readonly select_community_build: {
    readonly build_id: string;
    readonly expected_selection_revision: number;
  };
  readonly process_community_one: {
    readonly build_id: string;
    readonly workspace_id: string;
  };
  readonly retry_community: {
    readonly build_id: string;
    readonly candidate_id: string;
    readonly expected_attempt: number;
  };
  readonly activate_community_build: {
    readonly build_id: string;
    readonly expected_selection_revision: number;
  };
};

// prettier-ignore
export type NativeKnowledgeProcessingQuery = ({
  readonly operation: "configuration";
}) | ({
  readonly operation: "entities";
  readonly request: NativeKnowledgeRetrievalRequest;
}) | ({
  readonly operation: "relationships";
  readonly request: NativeKnowledgeRetrievalRequest;
}) | ({
  readonly operation: "text";
  readonly literal: string;
  readonly request: NativeKnowledgeRetrievalRequest;
}) | ({
  readonly operation: "semantic";
  readonly build_id: string;
  readonly config_revision: number;
  readonly query: string;
  readonly limit: number;
}) | ({
  readonly operation: "failed_processing";
  readonly request: NativeKnowledgeDiagnosticRequest;
}) | ({
  readonly operation: "failed_index";
  readonly build_id: string;
  readonly config_revision: number;
  readonly request: NativeKnowledgeDiagnosticRequest;
}) | ({
  readonly operation: "processing_audits";
  readonly source: NativeKnowledgeProcessingSource;
  readonly request: NativeKnowledgeDiagnosticRequest;
}) | ({
  readonly operation: "processing_task";
  readonly source: NativeKnowledgeProcessingSource;
}) | ({
  readonly operation: "community_active";
}) | ({
  readonly operation: "community_build";
  readonly build_id: string;
  readonly offset: number;
  readonly limit: number;
}) | ({
  readonly operation: "community_audit";
  readonly build_id: string;
  readonly candidate_id: string;
  readonly attempt: number;
}) | ({
  readonly operation: "community_builds";
  readonly offset: number;
  readonly limit: number;
}) | ({
  readonly operation: "graph_source";
  readonly source: NativeKnowledgeProcessingSource;
  readonly expected_audit_attempt: number;
});

// prettier-ignore
export type NativeKnowledgeProcessingCommand = ({
  readonly operation: "configure_embedding";
  readonly build_id: string;
  readonly provider_id: string;
  readonly provider_revision: number;
  readonly model_id: string;
  readonly expected_config_revision: (number) | (null);
}) | ({
  readonly operation: "select_embedding";
  readonly build_id: string;
  readonly expected_config_revision: (number) | (null);
}) | ({
  readonly operation: "index_one";
  readonly build_id: string;
  readonly config_revision: number;
}) | ({
  readonly operation: "promote_index";
  readonly build_id: string;
  readonly config_revision: number;
  readonly expected_active_build_id: (string) | (null);
}) | ({
  readonly operation: "retry_index";
  readonly build_id: string;
  readonly config_revision: number;
  readonly input: NativeKnowledgeIndexSource;
  readonly expected_attempt: number;
}) | ({
  readonly operation: "process_one";
  readonly workspace_id: string;
}) | ({
  readonly operation: "retry_processing";
  readonly source: NativeKnowledgeProcessingSource;
  readonly expected_attempt: number;
}) | ({
  readonly operation: "create_community_build";
  readonly idempotency_key: string;
  readonly min_community_size: number;
}) | ({
  readonly operation: "select_community_build";
  readonly build_id: string;
  readonly expected_selection_revision: number;
}) | ({
  readonly operation: "process_community_one";
  readonly build_id: string;
  readonly workspace_id: string;
}) | ({
  readonly operation: "retry_community";
  readonly build_id: string;
  readonly candidate_id: string;
  readonly expected_attempt: number;
}) | ({
  readonly operation: "activate_community_build";
  readonly build_id: string;
  readonly expected_selection_revision: number;
});

// prettier-ignore
export type NativeKnowledgeStorageQueryMap = {
  readonly get: {
    readonly id: string;
  };
  readonly list: {
    readonly limit: number;
    readonly offset: number;
  };
  readonly changes: {
    readonly after_sequence: number;
    readonly limit: number;
  };
  readonly change: {
    readonly sequence: number;
  };
  readonly sync_status: Readonly<Record<never, never>>;
  readonly sync_outbox: {
    readonly limit: number;
    readonly after_sequence: number;
  };
  readonly remote_baseline: {
    readonly id: string;
  };
  readonly push_conflicts: {
    readonly limit: number;
  };
  readonly pull_conflicts: {
    readonly limit: number;
  };
  readonly pull_conflict_context: {
    readonly id: string;
  };
  readonly resolution_history: {
    readonly id: string;
    readonly limit: number;
  };
};

// prettier-ignore
export type NativeKnowledgeStorageQuery = ({
  readonly operation: "get";
  readonly id: string;
}) | ({
  readonly operation: "list";
  readonly limit: number;
  readonly offset: number;
}) | ({
  readonly operation: "changes";
  readonly after_sequence: number;
  readonly limit: number;
}) | ({
  readonly operation: "change";
  readonly sequence: number;
}) | ({
  readonly operation: "sync_status";
}) | ({
  readonly operation: "sync_outbox";
  readonly limit: number;
  readonly after_sequence: number;
}) | ({
  readonly operation: "remote_baseline";
  readonly id: string;
}) | ({
  readonly operation: "push_conflicts";
  readonly limit: number;
}) | ({
  readonly operation: "pull_conflicts";
  readonly limit: number;
}) | ({
  readonly operation: "pull_conflict_context";
  readonly id: string;
}) | ({
  readonly operation: "resolution_history";
  readonly id: string;
  readonly limit: number;
}) | ({
  readonly operation: "graph_pull_conflicts";
  readonly limit: number;
}) | ({
  readonly operation: "graph_push_conflicts";
  readonly limit: number;
}) | ({
  readonly operation: "graph_pull_conflict_context";
  readonly id: string;
}) | ({
  readonly operation: "graph_resolution_history";
  readonly id: string;
  readonly limit: number;
}) | ({
  readonly operation: "remote_graph_baseline";
  readonly id: string;
}) | ({
  readonly operation: "synced_graph_projection";
  readonly id: string;
}) | ({
  readonly operation: "synced_graph_projections";
  readonly limit: number;
  readonly offset: number;
});

// prettier-ignore
export type NativeKnowledgeCloudQuery = ({
  readonly operation: "conflict_context";
  readonly local_sequence: number;
}) | ({
  readonly operation: "resolution";
  readonly resolution_id: string;
}) | ({
  readonly operation: "resolution_by_key";
  readonly idempotency_key: string;
}) | ({
  readonly operation: "pending_resolutions";
  readonly before_resolution_id?: (string) | (null);
  readonly limit: number;
}) | ({
  readonly operation: "resolutions";
  readonly limit: number;
}) | ({
  readonly operation: "reconciliation_context";
  readonly resolution_id: string;
});

// prettier-ignore
export type NativeKnowledgeMutation = ({
  readonly operation: "create";
  readonly memory: NativeKnowledgeMutationMemory;
}) | ({
  readonly operation: "update";
  readonly memory: NativeKnowledgeMutationMemory;
  readonly expected_revision: number;
}) | ({
  readonly operation: "delete";
  readonly id: string;
  readonly expected_revision: number;
});

// prettier-ignore
export type NativeKnowledgeQueryRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly query: NativeKnowledgeStorageQuery;
};

// prettier-ignore
export type NativeKnowledgeMutationRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly mutation: NativeKnowledgeMutation;
};

// prettier-ignore
export type NativeKnowledgeSyncLinkRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly link: NativeKnowledgeLink;
};

// prettier-ignore
export type NativeKnowledgeSyncUnbindRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly policy: NativeKnowledgeUnbindPolicy;
};

// prettier-ignore
export type NativeKnowledgePushRequest = {
  readonly scope: NativeKnowledgeScope;
};

// prettier-ignore
export type NativeKnowledgePullRequest = {
  readonly scope: NativeKnowledgeScope;
};

// prettier-ignore
export type NativeKnowledgeResolveRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly resolution: NativeKnowledgeCloudResolution;
};

// prettier-ignore
export type NativeKnowledgeResumeRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly resolution_id: string;
};

// prettier-ignore
export type NativeKnowledgeReconcileRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly resolution_id: string;
  readonly reconciliation: NativeKnowledgeReconciliation;
};

// prettier-ignore
export type NativeKnowledgeCloudQueryRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly query: NativeKnowledgeCloudQuery;
};

// prettier-ignore
export type NativeKnowledgeResolutionRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly resolution: NativeKnowledgePullResolution;
};

// prettier-ignore
export type NativeKnowledgeProcessingQueryRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly query: NativeKnowledgeProcessingQuery;
};

// prettier-ignore
export type NativeKnowledgeProcessingCommandRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly command: NativeKnowledgeProcessingCommand;
};

// prettier-ignore
export type NativeKnowledgeEnvelope = {
  readonly contract_version: "1.0.0";
  readonly scope: NativeKnowledgeScope;
  readonly result: NativeKnowledgeJson;
};

// prettier-ignore
export type NativeKnowledgeErrorEnvelope = {
  readonly error: {
    readonly code: string;
    readonly message: string;
    readonly target: "desktop-sidecar";
    readonly resolution_id?: string;
  };
};

// prettier-ignore
export type NativeKnowledgeStorageResultMap = {
  readonly get: {
    readonly memory: NativeKnowledgeStoredMemory;
  };
  readonly list: {
    readonly items: readonly (NativeKnowledgeMemory)[];
    readonly offset: number;
    readonly limit: number;
    readonly has_more: boolean;
  };
  readonly changes: {
    readonly items: readonly (NativeKnowledgeChange)[];
    readonly next_sequence: number;
  };
  readonly change: {
    readonly change: NativeKnowledgeChange;
  };
  readonly sync_status: {
    readonly status: NativeKnowledgeStatus;
  };
  readonly sync_outbox: {
    readonly items: readonly ({
      readonly change_id: string;
      readonly local_change: {
        readonly sequence: number;
        readonly memory: NativeKnowledgeMemory;
        readonly deleted: boolean;
      };
    })[];
    readonly next_sequence: number;
  };
  readonly remote_baseline: {
    readonly version: (NativeKnowledgeRemote) | (null);
  };
  readonly push_conflicts: {
    readonly items: readonly (NativeKnowledgePushConflict)[];
  };
  readonly pull_conflicts: {
    readonly items: readonly (NativeKnowledgePullConflict)[];
  };
  readonly pull_conflict_context: {
    readonly context: (NativeKnowledgePullContext) | (null);
  };
  readonly resolution_history: {
    readonly items: readonly ({
      readonly request: NativeKnowledgePullResolution;
      readonly receipt: NativeKnowledgeLocalReceipt;
      readonly archive: NativeKnowledgePullContext;
    })[];
  };
};

// prettier-ignore
export type NativeKnowledgeProcessingCommandResultMap = {
  readonly configure_embedding: {
    readonly configuration: NativeKnowledgeEmbeddingConfiguration;
  };
  readonly select_embedding: {
    readonly configuration: NativeKnowledgeEmbeddingConfiguration;
  };
  readonly index_one: {
    readonly receipt: (NativeKnowledgeIndexReceipt) | (null);
  };
  readonly promote_index: {
    readonly configuration: NativeKnowledgeEmbeddingConfiguration;
    readonly active_build_id: string;
  };
  readonly retry_index: {
    readonly accepted: true;
    readonly input: NativeKnowledgeIndexSource;
    readonly attempt: number;
  };
  readonly process_one: {
    readonly receipt: (NativeKnowledgeProcessingReceipt) | (null);
  };
  readonly retry_processing: {
    readonly accepted: true;
    readonly source: NativeKnowledgeProcessingSource;
    readonly attempt: number;
  };
  readonly create_community_build: {
    readonly build: NativeKnowledgeCommunityBuildReceipt;
  };
  readonly select_community_build: {
    readonly selection: NativeKnowledgeCommunitySelection;
  };
  readonly process_community_one: {
    readonly receipt: (NativeKnowledgeCommunityAuditSummary) | (null);
  };
  readonly retry_community: {
    readonly accepted: true;
    readonly build_id: string;
    readonly candidate_id: string;
    readonly attempt: number;
  };
  readonly activate_community_build: {
    readonly activated: boolean;
    readonly build_id: string;
    readonly selection_revision: number;
  };
};

// prettier-ignore
export type NativeKnowledgeContextResponse = {
  readonly contract_version: "1.0.0";
  readonly scope: NativeKnowledgeScope;
};

// prettier-ignore
export type NativeKnowledgeCapabilitiesResponse = {
  readonly contract_version: "1.0.0";
  readonly scope: NativeKnowledgeScope;
  readonly actor_id: string;
  readonly result: NativeKnowledgeCapabilityEntry;
};

// prettier-ignore
export type NativeKnowledgeSyncConnectionRequest = {
  readonly scope: NativeKnowledgeScope;
};

// prettier-ignore
export type NativeKnowledgeSyncTenantsRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly expected_connection_revision: string;
};

// prettier-ignore
export type NativeKnowledgeSyncProjectsRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly expected_connection_revision: string;
  readonly tenant_id: string;
};

// prettier-ignore
export type NativeKnowledgeSyncEnrollmentRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly expected_connection_revision: string;
  readonly tenant_id: string;
  readonly project_id: string;
};

// prettier-ignore
export type NativeKnowledgeSyncTargetRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly expected_connection_revision: string;
  readonly tenant_id: string;
  readonly project_id: string;
  readonly expected_generation: NativeKnowledgeCloudGeneration;
};

// prettier-ignore
export type NativeKnowledgeDiagnosticRequest = {
  readonly cursor?: (string) | (null);
  readonly limit: number;
};

// prettier-ignore
export type NativeKnowledgeGraphResolutionRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly resolution: NativeKnowledgeGraphPullResolution;
};

// prettier-ignore
export type NativeKnowledgeGraphResolvePushRequest = {
  readonly scope: NativeKnowledgeScope;
  readonly conflict_id: string;
  readonly change_id: string;
  readonly expected_current_revision: number;
  readonly decision: "keep_current" | "use_proposed" | "merged" | "keep_both";
  readonly content: (NativeKnowledgeJson) | (null);
};
