// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.

// prettier-ignore
export type NativeKnowledgeJson = (null) | (boolean) | (number) | (string) | (readonly (NativeKnowledgeJson)[]) | ({
  readonly [key: string]: NativeKnowledgeJson;
});

// prettier-ignore
export type NativeKnowledgeObject = {
  readonly [key: string]: NativeKnowledgeJson;
};

// prettier-ignore
export type NativeKnowledgeScope = {
  readonly tenant_id: string;
  readonly project_id: string;
  readonly context_revision: number;
  readonly profile_id: string;
  readonly generation: number;
  readonly digest: string;
};

// prettier-ignore
export type NativeKnowledgeLink = {
  readonly remote_tenant_id: string;
  readonly remote_project_id: string;
  readonly remote_actor_id: string;
};

// prettier-ignore
export type NativeKnowledgeStatus = {
  readonly replica_id: string;
  readonly link: (NativeKnowledgeLink) | (null);
  readonly pending_changes: number;
};

// prettier-ignore
export type NativeKnowledgeMemory = {
  readonly id: string;
  readonly project_id: string;
  readonly title: string;
  readonly content: string;
  readonly author_id: string;
  readonly content_type: string;
  readonly tags: readonly (string)[];
  readonly entities: readonly (NativeKnowledgeJson)[];
  readonly version: number;
  readonly status: string;
  readonly created_at_ms: number;
  readonly embedding: (readonly (number)[]) | (null);
  readonly metadata: {
    readonly [key: string]: NativeKnowledgeJson;
  };
};

// prettier-ignore
export type NativeKnowledgeContent = {
  readonly title: string;
  readonly content: string;
  readonly content_type: ("text") | ("document") | ("image") | ("video");
  readonly tags: readonly (string)[];
  readonly metadata: NativeKnowledgeObject;
  readonly status: ("ENABLED") | ("DISABLED");
};

// prettier-ignore
export type NativeKnowledgeRemote = {
  readonly [key: string]: NativeKnowledgeJson;
  readonly memory_id: string;
  readonly revision: number;
  readonly deleted: boolean;
  readonly author_id: string;
  readonly created_at_ms: number;
  readonly content: NativeKnowledgeContent;
};

// prettier-ignore
export type NativeKnowledgeProposal = {
  readonly [key: string]: NativeKnowledgeJson;
  readonly memory_id: string;
  readonly operation: ("create") | ("update") | ("delete");
  readonly expected_revision: number;
  readonly content: (NativeKnowledgeContent) | (null);
};

// prettier-ignore
export type NativeKnowledgePushConflict = {
  readonly [key: string]: NativeKnowledgeJson;
  readonly id: string;
  readonly memory_id: string;
  readonly proposed: NativeKnowledgeProposal;
  readonly current: (NativeKnowledgeRemote) | (null);
  readonly resolved_change_id: (string) | (null);
};

// prettier-ignore
export type NativeKnowledgePullConflict = {
  readonly sequence: number;
  readonly memory_id: string;
  readonly remote: NativeKnowledgeRemote;
  readonly local: (NativeKnowledgeMemory) | (null);
  readonly local_deleted: boolean;
  readonly baseline: (NativeKnowledgeRemote) | (null);
};

// prettier-ignore
export type NativeKnowledgeGuard = {
  readonly expected_local_revision: number;
  readonly expected_remote_revision: number;
  readonly expected_baseline_revision: number;
  readonly conflict_sequences: readonly (number)[];
};

// prettier-ignore
export type NativeKnowledgeLocalChoice = ({
  readonly decision: ("use_local") | ("use_remote") | ("keep_both");
}) | ({
  readonly decision: "merged";
  readonly content: NativeKnowledgeContent;
});

// prettier-ignore
export type NativeKnowledgeCloudChoice = ({
  readonly decision: ("keep_current") | ("use_proposed");
}) | ({
  readonly decision: "merged";
  readonly content: NativeKnowledgeContent;
});

// prettier-ignore
export type NativeKnowledgePullResolution = {
  readonly expected_local_revision: number;
  readonly expected_remote_revision: number;
  readonly expected_baseline_revision: number;
  readonly conflict_sequences: readonly (number)[];
  readonly memory_id: string;
  readonly choice: NativeKnowledgeLocalChoice;
};

// prettier-ignore
export type NativeKnowledgeCloudResolution = {
  readonly local_sequence: number;
  readonly memory_id: string;
  readonly conflict_id: string;
  readonly guard: NativeKnowledgeGuard;
  readonly choice: NativeKnowledgeCloudChoice;
};

// prettier-ignore
export type NativeKnowledgeReconciliation = {
  readonly guard: NativeKnowledgeGuard;
  readonly choice: NativeKnowledgeLocalChoice;
};

// prettier-ignore
export type NativeKnowledgePullContext = {
  readonly memory_id: string;
  readonly conflict_sequences: readonly (number)[];
  readonly local: NativeKnowledgeMemory;
  readonly local_deleted: boolean;
  readonly local_metadata: NativeKnowledgeObject;
  readonly baseline: (NativeKnowledgeRemote) | (null);
  readonly remote: NativeKnowledgeRemote;
};

// prettier-ignore
export type NativeKnowledgeCloudContext = {
  readonly local_sequence: number;
  readonly memory_id: string;
  readonly conflict_id: string;
  readonly original_request: {
    readonly [key: string]: NativeKnowledgeJson;
    readonly memory_id: string;
    readonly operation: ("create") | ("update") | ("delete");
    readonly expected_revision: number;
    readonly content: (NativeKnowledgeContent) | (null);
    readonly change_id: string;
  };
  readonly cloud_conflict: NativeKnowledgePushConflict;
  readonly local: NativeKnowledgeMemory;
  readonly local_deleted: boolean;
  readonly local_metadata: NativeKnowledgeObject;
  readonly baseline: (NativeKnowledgeRemote) | (null);
  readonly remote: (NativeKnowledgeRemote) | (null);
  readonly conflict_sequences: readonly (number)[];
  readonly pending_sequences: readonly (number)[];
  readonly observed_cursor: number;
};

// prettier-ignore
export type NativeKnowledgeLocalReceipt = {
  readonly resolution_id: string;
  readonly memory_id: string;
  readonly local_revision: number;
  readonly remote_baseline_revision: number;
  readonly copy_memory_id: (string) | (null);
  readonly processing_sequences: readonly (number)[];
  readonly pending_push_sequences: readonly (number)[];
  readonly superseded_sequences: readonly (number)[];
  readonly conflict_sequences: readonly (number)[];
};

// prettier-ignore
export type NativeKnowledgeReconciliationReceipt = {
  readonly local_revision: number;
  readonly copy_memory_id: (string) | (null);
  readonly processing_sequences: readonly (number)[];
  readonly pending_push_sequences: readonly (number)[];
  readonly superseded_sequences: readonly (number)[];
  readonly conflict_sequences: readonly (number)[];
};

// prettier-ignore
export type NativeKnowledgeAppliedReceipt = {
  readonly [key: string]: NativeKnowledgeJson;
  readonly status: "applied";
  readonly change_id: string;
  readonly sequence: number;
  readonly version: NativeKnowledgeRemote;
};

// prettier-ignore
export type NativeKnowledgeResolvedReceipt = {
  readonly [key: string]: NativeKnowledgeJson;
  readonly status: "resolved";
  readonly change_id: string;
  readonly conflict_id: string;
  readonly version: (NativeKnowledgeRemote) | (null);
};

// prettier-ignore
export type NativeKnowledgeCloudReceipt = (NativeKnowledgeAppliedReceipt) | (NativeKnowledgeResolvedReceipt);

// prettier-ignore
export type NativeKnowledgeCloudOutcome = {
  readonly resolution_id: string;
  readonly receipt: NativeKnowledgeCloudReceipt;
  readonly pending_reconciliation: boolean;
  readonly replayed: boolean;
};

// prettier-ignore
export type NativeKnowledgeResolutionRecord = {
  readonly resolution_id: string;
  readonly local_sequence: number;
  readonly request_json: string;
  readonly command: NativeKnowledgeCloudResolution;
  readonly archive: NativeKnowledgeCloudContext;
  readonly receipt: (NativeKnowledgeCloudReceipt) | (null);
  readonly rejection: (NativeKnowledgeObject) | (null);
  readonly reconciliation: (NativeKnowledgeReconciliationReceipt) | (null);
  readonly reconciliation_command: (NativeKnowledgeReconciliation) | ({
    readonly source: "cloud_receipt";
  }) | (null);
  readonly reconciliation_archive: (NativeKnowledgeCloudContext) | (null);
};

// prettier-ignore
export type Page = {
  readonly limit: number;
};

// prettier-ignore
export type Id = {
  readonly id: string;
};

// prettier-ignore
export type ResolutionId = {
  readonly resolution_id: string;
};

// prettier-ignore
export type NativeKnowledgeProcessingSource = {
  readonly tenant_id: string;
  readonly project_id: string;
  readonly memory_id: string;
  readonly revision: number;
  readonly change_sequence: number;
};

// prettier-ignore
export type NativeKnowledgeRetrievalPosition = {
  readonly change_sequence: number;
  readonly item_index: number;
};

// prettier-ignore
export type NativeKnowledgeRetrievalCursor = {
  readonly tenant_id: string;
  readonly project_id: string;
  readonly kind: "entities" | "relationships" | "text";
  readonly source: (NativeKnowledgeProcessingSource) | (null);
  readonly literal: (string) | (null);
  readonly upper_change_sequence: number;
  readonly after: NativeKnowledgeRetrievalPosition;
};

// prettier-ignore
export type NativeKnowledgeEntity = {
  readonly name: string;
  readonly kind: string;
};

// prettier-ignore
export type NativeKnowledgeEntityReference = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly entity_index: number;
};

// prettier-ignore
export type NativeKnowledgeRetrievedEntity = {
  readonly reference: NativeKnowledgeEntityReference;
  readonly audit_attempt: number;
  readonly entity: NativeKnowledgeEntity;
};

// prettier-ignore
export type NativeKnowledgeRelationship = {
  readonly source_index: number;
  readonly target_index: number;
  readonly relation_type: string;
  readonly fact: string;
  readonly score: number;
};

// prettier-ignore
export type NativeKnowledgeRetrievedRelationship = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly relationship_index: number;
  readonly audit_attempt: number;
  readonly source_entity: NativeKnowledgeEntityReference;
  readonly target_entity: NativeKnowledgeEntityReference;
  readonly relationship: NativeKnowledgeRelationship;
};

// prettier-ignore
export type NativeKnowledgeTextHit = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly audit_attempt: number;
  readonly title: string;
  readonly content: string;
};

// prettier-ignore
export type NativeKnowledgeProcessingCoverage = {
  readonly current_sources: number;
  readonly applied_sources: number;
  readonly pending_sources: number;
  readonly failed_sources: number;
};

// prettier-ignore
export type NativeKnowledgeIndexCoverage = {
  readonly current_sources: number;
  readonly completed_sources: number;
  readonly failed_sources: number;
};

// prettier-ignore
export type NativeKnowledgeEmbeddingConfiguration = {
  readonly revision: number;
  readonly build_id: string;
  readonly provider_id: string;
  readonly provider_revision: number;
  readonly model_id: string;
  readonly dimensions: number;
  readonly input_contract_version: 1;
  readonly normalization_version: 1;
};

// prettier-ignore
export type NativeKnowledgeIndexSource = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly audit_attempt: number;
  readonly input_digest: string;
};

// prettier-ignore
export type NativeKnowledgeSemanticHit = {
  readonly input: NativeKnowledgeIndexSource;
  readonly score: number;
};

// prettier-ignore
export type NativeKnowledgeChange = {
  readonly sequence: number;
  readonly memory: NativeKnowledgeStoredMemory;
  readonly deleted: boolean;
};

// prettier-ignore
export type NativeKnowledgeMutationResult = {
  readonly receipt: NativeKnowledgeChange;
  readonly replayed: boolean;
  readonly processing_status: "accepted";
};

// prettier-ignore
export type NativeKnowledgeIndexFailure = "provider_unavailable" | "profile_changed" | "invalid_embedding" | "cancelled";

// prettier-ignore
export type NativeKnowledgeProcessingFailure = "provider_unavailable" | "invalid_extraction" | "cancelled" | "lease_lost" | "admission_changed" | "internal_failure";

// prettier-ignore
export type NativeKnowledgeIndexReceipt = {
  readonly input: NativeKnowledgeIndexSource;
  readonly attempt: number;
  readonly status: "indexed" | "failed";
  readonly failure: (NativeKnowledgeIndexFailure) | (null);
};

// prettier-ignore
export type NativeKnowledgeProcessingReceipt = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly attempt: number;
  readonly status: "applied" | "failed";
  readonly failure: (NativeKnowledgeProcessingFailure) | (null);
};

// prettier-ignore
export type NativeKnowledgeStoredMemory = {
  readonly id: string;
  readonly project_id: string;
  readonly title: string;
  readonly content: string;
  readonly author_id: string;
  readonly content_type: string;
  readonly tags: readonly (string)[];
  readonly entities: readonly (NativeKnowledgeEntity)[];
  readonly version: number;
  readonly status: string;
  readonly created_at_ms: number;
  readonly embedding: (readonly (number)[]) | (null);
  readonly metadata: {
    readonly [key: string]: NativeKnowledgeJson;
  };
};

// prettier-ignore
export type NativeKnowledgeMutationMemory = {
  readonly id: string;
  readonly project_id: string;
  readonly title: string;
  readonly content: string;
  readonly author_id: string;
  readonly content_type: string;
  readonly tags: readonly (string)[];
  readonly entities: readonly (NativeKnowledgeEntity)[];
  readonly version: number;
  readonly status: string;
  readonly created_at_ms: number;
  readonly embedding?: (readonly (number)[]) | (null);
  readonly metadata: {
    readonly [key: string]: NativeKnowledgeJson;
  };
};

// prettier-ignore
export type NativeKnowledgeCapabilityScope = {
  readonly tenant_id: (string) | (null);
  readonly project_id: (string) | (null);
  readonly workspace_id: (string) | (null);
  readonly instance_id: (string) | (null);
};

// prettier-ignore
export type NativeKnowledgeCapabilityEntry = {
  readonly availability: "available" | "degraded" | "unavailable" | "not_applicable";
  readonly reason_code: (string) | (null);
  readonly service_version: (string) | (null);
  readonly contract_version: (string) | (null);
  readonly allowed_actions: readonly ("activate_community_build" | "cloud_conflict_context" | "community_active" | "community_audit" | "community_build" | "configuration" | "configure_embedding" | "create" | "create_community_build" | "delete" | "entities" | "failed_index" | "failed_processing" | "get" | "index_one" | "list" | "pending_resolutions" | "process_community_one" | "process_one" | "processing_audits" | "promote_index" | "pull_conflict_context" | "pull_conflicts" | "push_conflicts" | "reconcile_resolution" | "reconciliation_context" | "relationships" | "remote_baseline" | "resolution" | "resolution_by_key" | "resolution_history" | "resolutions" | "resolve_pull" | "resolve_push" | "resume_resolution" | "retry_community" | "retry_index" | "select_embedding" | "select_community_build" | "semantic" | "sync_link" | "sync_outbox" | "sync_pull" | "sync_push" | "sync_status" | "text" | "update" | "view" | "retry_processing" | "processing_task" | "community_builds")[];
  readonly scope: NativeKnowledgeCapabilityScope;
  readonly authority_revision: (number) | (null);
  readonly retryable: boolean;
  readonly authority_source: "cloud_service" | "sidecar" | "electron" | "native_runtime" | "renderer";
  readonly supporting_authority_sources: readonly ("cloud_service" | "sidecar" | "electron" | "native_runtime" | "renderer")[];
  readonly provenance: "observed" | "declared";
};

// prettier-ignore
export type NativeKnowledgeCloudGenerationDescriptor = {
  readonly profile_id: string;
  readonly generation: number;
  readonly digest: string;
};

// prettier-ignore
export type NativeKnowledgeCloudGeneration = {
  readonly contract_version: "1.0.0";
  readonly descriptor: NativeKnowledgeCloudGenerationDescriptor;
};

// prettier-ignore
export type NativeKnowledgeSyncConnection = {
  readonly connection_revision: string;
  readonly authority: string;
  readonly actor_id: string;
};

// prettier-ignore
export type NativeKnowledgeSyncTenant = {
  readonly id: string;
  readonly name: string;
};

// prettier-ignore
export type NativeKnowledgeSyncProject = {
  readonly id: string;
  readonly tenant_id: string;
  readonly name: string;
};

// prettier-ignore
export type NativeKnowledgeSyncEnrollment = {
  readonly contract_version: "1.0.0";
  readonly tenant_id: string;
  readonly project_id: string;
  readonly actor_id: string;
  readonly enabled: boolean;
  readonly can_enroll: boolean;
  readonly bootstrap_count: number;
  readonly next_cursor: number;
  readonly replayed: boolean;
  readonly generation: NativeKnowledgeCloudGeneration;
};

// prettier-ignore
export type NativeKnowledgeSyncConnectionResult = {
  readonly connection: (NativeKnowledgeSyncConnection) | (null);
};

// prettier-ignore
export type NativeKnowledgeSyncTenantsResult = {
  readonly connection: NativeKnowledgeSyncConnection;
  readonly items: readonly (NativeKnowledgeSyncTenant)[];
};

// prettier-ignore
export type NativeKnowledgeSyncProjectsResult = {
  readonly connection: NativeKnowledgeSyncConnection;
  readonly tenant_id: string;
  readonly items: readonly (NativeKnowledgeSyncProject)[];
};

// prettier-ignore
export type NativeKnowledgeSyncEnrollmentResult = {
  readonly connection: NativeKnowledgeSyncConnection;
  readonly enrollment: NativeKnowledgeSyncEnrollment;
};

// prettier-ignore
export type NativeKnowledgeSyncBindingResult = {
  readonly connection: NativeKnowledgeSyncConnection;
  readonly enrollment: NativeKnowledgeSyncEnrollment;
  readonly status: NativeKnowledgeStatus;
  readonly association_state: "verified";
};

// prettier-ignore
export type NativeKnowledgeProcessingFailureDetail = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly attempt: number;
  readonly failure: "model_unconfigured" | "provider_unavailable" | "invalid_extraction" | "cancelled" | "processing_failed";
};

// prettier-ignore
export type NativeKnowledgeIndexFailureDetail = {
  readonly input: NativeKnowledgeIndexSource;
  readonly attempt: number;
  readonly failure: "provider_unavailable" | "profile_changed" | "invalid_embedding" | "cancelled";
};

// prettier-ignore
export type NativeKnowledgeAuditSummary = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly attempt: number;
  readonly agent_id: string;
  readonly provider_id: string;
  readonly model_id: string;
  readonly tool_name: string;
  readonly contract_version: number;
  readonly started_at_ms: number;
  readonly finished_at_ms: (number) | (null);
  readonly latency_ms: (number) | (null);
  readonly status: "running" | "applied" | "failed";
  readonly failure: ("provider_unavailable" | "invalid_extraction" | "cancelled" | "lease_lost" | "admission_changed" | "internal_failure") | (null);
};

// prettier-ignore
export type NativeKnowledgeProcessingTaskSnapshot = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly current: boolean;
  readonly task: ({
    readonly state: "pending" | "leased" | "completed" | "failed" | "superseded";
    readonly attempt: number;
    readonly failure: (NativeKnowledgeProcessingFailure) | (null);
  }) | (null);
};

// prettier-ignore
export type NativeKnowledgeCommunityFailure = "provider_unavailable" | "invalid_submission" | "cancelled" | "lease_lost" | "admission_changed" | "graph_changed" | "internal_failure";

// prettier-ignore
export type NativeKnowledgeCommunitySelection = {
  readonly requested_build_id: (string) | (null);
  readonly active_build_id: (string) | (null);
  readonly revision: number;
};

// prettier-ignore
export type NativeKnowledgeCommunityBuildReceipt = {
  readonly tenant_id: string;
  readonly project_id: string;
  readonly build_id: string;
  readonly graph_digest: string;
  readonly candidate_count: number;
  readonly state: "pending" | "completed_empty";
  readonly created_at_ms: number;
};

// prettier-ignore
export type NativeKnowledgeCommunityBuildStatus = {
  readonly build_id: string;
  readonly state: "pending" | "failed" | "completed" | "completed_empty";
  readonly candidate_count: number;
  readonly ready_count: number;
  readonly insufficient_evidence_count: number;
  readonly failed_count: number;
};

// prettier-ignore
export type NativeKnowledgeCommunityEvidence = {
  readonly source: NativeKnowledgeProcessingSource;
  readonly entity_index: number;
  readonly relationship_index: (number) | (null);
};

// prettier-ignore
export type NativeKnowledgeCommunityDecision = ({
  readonly status: "ready";
  readonly name: string;
  readonly summary: string;
  readonly rationale: string;
  readonly evidence: readonly (NativeKnowledgeCommunityEvidence)[];
}) | ({
  readonly status: "insufficient_evidence";
  readonly rationale: string;
  readonly evidence: readonly (NativeKnowledgeCommunityEvidence)[];
});

// prettier-ignore
export type NativeKnowledgeCommunitySubmission = {
  readonly build_id: string;
  readonly graph_digest: string;
  readonly candidate_id: string;
  readonly members: readonly (NativeKnowledgeEntityReference)[];
  readonly decision: NativeKnowledgeCommunityDecision;
};

// prettier-ignore
export type NativeKnowledgeCommunityResult = {
  readonly build_id: string;
  readonly candidate_id: string;
  readonly attempt: number;
  readonly submission: NativeKnowledgeCommunitySubmission;
  readonly finished_at_ms: number;
};

// prettier-ignore
export type NativeKnowledgeCommunityJobStatus = {
  readonly build_id: string;
  readonly candidate_id: string;
  readonly state: "pending" | "leased" | "failed" | "completed";
  readonly attempt: number;
  readonly failure: ("cancelled" | "worker_unavailable" | "execution_failed") | (null);
};

// prettier-ignore
export type NativeKnowledgeCommunityAuditSummary = {
  readonly build_id: string;
  readonly candidate_id: string;
  readonly attempt: number;
  readonly agent_id: string;
  readonly provider_id: string;
  readonly model_id: string;
  readonly tool_name: "submit_knowledge_community";
  readonly contract_version: 1;
  readonly started_at_ms: number;
  readonly finished_at_ms: (number) | (null);
  readonly latency_ms: (number) | (null);
  readonly status: "running" | "applied" | "failed";
  readonly failure: (NativeKnowledgeCommunityFailure) | (null);
  readonly response_digest: (string) | (null);
};

// prettier-ignore
export type NativeKnowledgeCommunityCandidateProgress = {
  readonly candidate_id: string;
  readonly member_count: number;
  readonly job: NativeKnowledgeCommunityJobStatus;
  readonly result: (NativeKnowledgeCommunityResult) | (null);
  readonly audit: (NativeKnowledgeCommunityAuditSummary) | (null);
};

// prettier-ignore
export type NativeKnowledgeCommunityBuildPage = {
  readonly build: NativeKnowledgeCommunityBuildReceipt;
  readonly status: NativeKnowledgeCommunityBuildStatus;
  readonly current_graph: boolean;
  readonly items: readonly (NativeKnowledgeCommunityCandidateProgress)[];
  readonly total: number;
  readonly offset: number;
  readonly limit: number;
};

// prettier-ignore
export type NativeKnowledgeCommunityBuildHistoryPage = {
  readonly items: readonly (NativeKnowledgeCommunityBuildReceipt)[];
  readonly total: number;
  readonly offset: number;
  readonly limit: number;
};
