// Generated by scripts/generate_native_project_schema_contract.py; edit canonical contracts.
// prettier-ignore
export type NativeProjectSchemaScope = {
  readonly tenant_id: string;
  readonly project_id: string;
  readonly context_revision: number;
  readonly profile_id: string;
  readonly generation: number;
  readonly digest: string;
};

// prettier-ignore
export type NativeProjectSchemaDocument = {
  readonly format_version: 1;
  readonly tenant_id: string;
  readonly project_id: string;
  readonly schema_id: PortableSchemaUuid;
  readonly revision: PortableSchemaRevision;
  readonly deleted: boolean;
  readonly entity_types: readonly (PortableSchemaType)[];
  readonly edge_types: readonly (PortableSchemaType)[];
  readonly mappings: readonly (PortableSchemaMapping)[];
  readonly tombstones: readonly (PortableSchemaTombstone)[];
};

// prettier-ignore
export type NativeProjectSchemaUuid = PortableSchemaUuid;

// prettier-ignore
export type NativeProjectSchemaReceipt = {
  readonly format_version: 1;
  readonly actor_id: string;
  readonly change_id: NativeProjectSchemaUuid;
  readonly sequence: number;
  readonly document: NativeProjectSchemaDocument;
};

// prettier-ignore
export type NativeProjectSchemaReadRequest = {
  readonly scope: NativeProjectSchemaScope;
};

// prettier-ignore
export type NativeProjectSchemaBootstrapRequest = {
  readonly scope: NativeProjectSchemaScope;
  readonly change_id: NativeProjectSchemaUuid;
  readonly expected_revision: 0;
  readonly document: NativeProjectSchemaDocument;
};

// prettier-ignore
export type NativeProjectSchemaReplaceRequest = {
  readonly scope: NativeProjectSchemaScope;
  readonly change_id: NativeProjectSchemaUuid;
  readonly expected_revision: number;
  readonly document: NativeProjectSchemaDocument;
};

// prettier-ignore
export type NativeProjectSchemaReceiptRequest = {
  readonly scope: NativeProjectSchemaScope;
  readonly change_id: NativeProjectSchemaUuid;
};

// prettier-ignore
export type NativeProjectSchemaHistoryRequest = {
  readonly scope: NativeProjectSchemaScope;
  readonly after_revision: number;
  readonly limit: number;
};

// prettier-ignore
export type NativeProjectSchemaReadResult = {
  readonly document: (NativeProjectSchemaDocument) | (null);
};

// prettier-ignore
export type NativeProjectSchemaMutationResult = {
  readonly receipt: NativeProjectSchemaReceipt;
};

// prettier-ignore
export type NativeProjectSchemaReceiptResult = {
  readonly receipt: (NativeProjectSchemaReceipt) | (null);
};

// prettier-ignore
export type NativeProjectSchemaHistoryResult = {
  readonly schema_id: (NativeProjectSchemaUuid) | (null);
  readonly after_revision: number;
  readonly upper_revision: number;
  readonly next_after_revision: number;
  readonly has_more: boolean;
  readonly items: readonly (NativeProjectSchemaReceipt)[];
};

// prettier-ignore
export type NativeProjectSchemaReadResponse = {
  readonly contract_version: "1.0.0";
  readonly authority: "native-project-schema";
  readonly operation: "schema_read";
  readonly actor_id: string;
  readonly scope: NativeProjectSchemaScope;
  readonly result: NativeProjectSchemaReadResult;
};

// prettier-ignore
export type NativeProjectSchemaBootstrapResponse = {
  readonly contract_version: "1.0.0";
  readonly authority: "native-project-schema";
  readonly operation: "schema_bootstrap";
  readonly actor_id: string;
  readonly scope: NativeProjectSchemaScope;
  readonly result: NativeProjectSchemaMutationResult;
};

// prettier-ignore
export type NativeProjectSchemaReplaceResponse = {
  readonly contract_version: "1.0.0";
  readonly authority: "native-project-schema";
  readonly operation: "schema_replace";
  readonly actor_id: string;
  readonly scope: NativeProjectSchemaScope;
  readonly result: NativeProjectSchemaMutationResult;
};

// prettier-ignore
export type NativeProjectSchemaReceiptResponse = {
  readonly contract_version: "1.0.0";
  readonly authority: "native-project-schema";
  readonly operation: "schema_receipt";
  readonly actor_id: string;
  readonly scope: NativeProjectSchemaScope;
  readonly result: NativeProjectSchemaReceiptResult;
};

// prettier-ignore
export type NativeProjectSchemaHistoryResponse = {
  readonly contract_version: "1.0.0";
  readonly authority: "native-project-schema";
  readonly operation: "schema_history";
  readonly actor_id: string;
  readonly scope: NativeProjectSchemaScope;
  readonly result: NativeProjectSchemaHistoryResult;
};

// prettier-ignore
export type NativeProjectSchemaCapabilitiesResponse = {
  readonly contract_version: "1.0.0";
  readonly authority: "native-project-schema";
  readonly operation: "schema_capabilities";
  readonly actor_id: string;
  readonly scope: NativeProjectSchemaScope;
  readonly result: {
  readonly route_id: "project-project-schema";
  readonly availability: "unavailable" | "degraded";
  readonly reason_code: (null) | (string);
  readonly allowed_actions: readonly ("schema_read" | "schema_bootstrap" | "schema_replace" | "schema_receipt" | "schema_history")[];
  readonly provenance: "observed";
  readonly authority_source: "sidecar";
};
};

// prettier-ignore
export type PortableSchemaUuid = string;

// prettier-ignore
export type PortableSchemaRevision = number;

// prettier-ignore
export type PortableSchemaType = {
  readonly id: PortableSchemaUuid;
  readonly status: "ENABLED" | "DISABLED";
  readonly source: string;
  readonly name: string;
  readonly description: string;
  readonly schema: {
  readonly [key: string]: PortableSchemaJsonValue;
};
};

// prettier-ignore
export type PortableSchemaMapping = {
  readonly id: PortableSchemaUuid;
  readonly status: "ENABLED" | "DISABLED";
  readonly source: string;
  readonly source_type_id: PortableSchemaUuid;
  readonly target_type_id: PortableSchemaUuid;
  readonly edge_type_id: PortableSchemaUuid;
};

// prettier-ignore
export type PortableSchemaTombstone = {
  readonly id: PortableSchemaUuid;
  readonly kind: "entity_type" | "edge_type" | "mapping";
  readonly deleted_revision: PortableSchemaRevision;
};

// prettier-ignore
export type PortableSchemaJsonValue = (null) | (boolean) | (number) | (string) | (readonly (PortableSchemaJsonValue)[]) | ({
  readonly [key: string]: PortableSchemaJsonValue;
});

// prettier-ignore
export type NativeProjectSchemaAction = "schema_read" | "schema_bootstrap" | "schema_replace" | "schema_receipt" | "schema_history";
// prettier-ignore
export type NativeProjectSchemaResponseMap = {readonly schema_read: NativeProjectSchemaReadResponse;readonly schema_bootstrap: NativeProjectSchemaBootstrapResponse;readonly schema_replace: NativeProjectSchemaReplaceResponse;readonly schema_receipt: NativeProjectSchemaReceiptResponse;readonly schema_history: NativeProjectSchemaHistoryResponse;};
// prettier-ignore
export type NativeProjectSchemaRequestMap = {readonly schema_read: NativeProjectSchemaReadRequest;readonly schema_bootstrap: NativeProjectSchemaBootstrapRequest;readonly schema_replace: NativeProjectSchemaReplaceRequest;readonly schema_receipt: NativeProjectSchemaReceiptRequest;readonly schema_history: NativeProjectSchemaHistoryRequest;};
