import {
  createDesktopRouteRegistry,
  type DesktopRouteDefinition,
  type DesktopRouteLoader,
  type DesktopRouteLocalPolicy,
  type DesktopRouteRegistry,
  type DesktopRouteScope,
} from './desktopRouteRegistry';

type CanonicalRouteMetadata = readonly [
  id: string,
  path: string,
  scope: readonly DesktopRouteScope[],
  navGroup: string,
  requiredPermission: readonly string[],
  localPolicy: DesktopRouteLocalPolicy,
];

const CANONICAL_ROUTE_METADATA = [
  [
    'agent-workspace-tenant-agent-workspace',
    '/tenant/:tenantId/agent-workspace',
    ['tenant'],
    'tenant-core-operations',
    [
      'authenticated',
      'tenant_scope',
      'conversation_read_access',
      'conversation_or_project_owner_for_roster_mutations',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-overview',
    '/tenant/:tenantId/overview',
    ['tenant'],
    'tenant-core-operations',
    ['authenticated', 'tenant_member'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-projects',
    '/tenant/:tenantId/projects',
    ['tenant'],
    'tenant-core-operations',
    [
      'authenticated',
      'project_membership_for_list',
      'tenant_admin_or_owner_for_create',
      'project_admin_or_owner_for_update',
      'project_owner_for_delete',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-workspaces',
    '/tenant/:tenantId/workspaces',
    ['tenant', 'workspace'],
    'tenant-core-operations',
    [
      'authenticated',
      'project_access',
      'workspace_access',
      'workspace_editor_for_update_and_agent_bindings',
      'workspace_owner_for_member_management',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-tasks',
    '/tenant/:tenantId/tasks',
    ['tenant'],
    'tenant-core-operations',
    ['authenticated', 'accessible_project_scope', 'task_access'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-analytics',
    '/tenant/:tenantId/analytics',
    ['tenant'],
    'tenant-core-operations',
    ['authenticated', 'tenant_member'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-agent-configuration',
    '/tenant/:tenantId/agents',
    ['tenant'],
    'tenant-agent-building',
    [
      'authenticated',
      'tenant_member',
      'tenant_admin_for_config_mutations',
      'conversation_access_for_trace_details',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-agent-definitions',
    '/tenant/:tenantId/agent-definitions',
    ['tenant'],
    'tenant-agent-building',
    [
      'authenticated',
      'tenant_member_for_read',
      'tenant_admin_for_mutations',
      'project_access_when_scoped',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-agent-bindings',
    '/tenant/:tenantId/agent-bindings',
    ['tenant'],
    'tenant-agent-building',
    ['authenticated', 'tenant_member_for_read', 'tenant_admin_for_mutations'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-skills',
    '/tenant/:tenantId/skills',
    ['tenant'],
    'tenant-agent-building',
    [
      'authenticated',
      'tenant_access',
      'tenant_admin_for_tenant_mutations',
      'project_member_for_project_reads',
      'project_contributor_for_project_mutations',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-evolution',
    '/tenant/:tenantId/evolution',
    ['tenant'],
    'tenant-agent-building',
    [
      'authenticated',
      'tenant_access',
      'tenant_admin_for_config_and_tenant_run',
      'tenant_admin_or_project_contributor_for_job_review',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-patterns',
    '/tenant/:tenantId/patterns',
    ['tenant'],
    'tenant-agent-building',
    ['authenticated', 'tenant_member_for_read', 'tenant_admin_for_delete'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-plugins',
    '/tenant/:tenantId/plugins',
    ['tenant'],
    'tenant-extensions-integrations',
    [
      'authenticated',
      'tenant_member_for_read',
      'tenant_admin_or_owner_for_plugin_mutations',
      'project_access_for_channel_configs',
      'project_admin_or_owner_for_channel_config_mutations',
      'project_member_for_channel_config_test',
      'desktop_tenant_admin_or_owner_for_channel_management',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-mcp-servers',
    '/tenant/:tenantId/mcp-servers',
    ['tenant'],
    'tenant-extensions-integrations',
    [
      'authenticated',
      'project_member_for_read',
      'project_owner_admin_or_member_for_mutations',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-acp',
    '/tenant/:tenantId/acp',
    ['tenant'],
    'tenant-extensions-integrations',
    ['authenticated', 'tenant_member_for_read', 'tenant_admin_for_acp_mutations'],
    'cloud_only',
  ],
  [
    'tenant-tenant-templates',
    '/tenant/:tenantId/templates',
    ['tenant'],
    'tenant-extensions-integrations',
    ['authenticated', 'tenant_member'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-providers',
    '/tenant/:tenantId/providers',
    ['tenant'],
    'tenant-extensions-integrations',
    [
      'authenticated',
      'tenant_assignment_access',
      'tenant_member_or_global_admin_for_usage',
      'global_admin_for_provider_mutations',
      'global_admin_for_system_actions',
      'project_workspace_access_for_routing',
    ],
    'native_equivalent',
  ],
  [
    'tenant-tenant-webhooks',
    '/tenant/:tenantId/webhooks',
    ['tenant'],
    'tenant-extensions-integrations',
    ['authenticated', 'tenant_admin', 'events_feature_for_event_type_catalog'],
    'cloud_only',
  ],
  [
    'tenant-tenant-runtimes',
    '/tenant/:tenantId/runtimes',
    ['tenant', 'global'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'global_admin', 'tenant_member'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-pool',
    '/tenant/:tenantId/pool',
    ['tenant', 'global'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'global_admin'],
    'cloud_only',
  ],
  [
    'tenant-tenant-instances',
    '/tenant/:tenantId/instances',
    ['tenant', 'instance'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'tenant_member', 'tenant_admin_for_mutations'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-clusters',
    '/tenant/:tenantId/clusters',
    ['tenant'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'tenant_member'],
    'cloud_only',
  ],
  [
    'tenant-tenant-deploy',
    '/tenant/:tenantId/deploy',
    ['tenant', 'instance'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'tenant_access'],
    'cloud_only',
  ],
  [
    'tenant-tenant-instance-templates',
    '/tenant/:tenantId/instance-templates',
    ['tenant'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'tenant_member'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-genes',
    '/tenant/:tenantId/genes',
    ['tenant', 'instance'],
    'tenant-runtime-infrastructure',
    ['authenticated', 'tenant_scope'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-users',
    '/tenant/:tenantId/users',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_member'],
    'cloud_only',
  ],
  [
    'tenant-tenant-audit-logs',
    '/tenant/:tenantId/audit-logs',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_access'],
    'cloud_only',
  ],
  [
    'tenant-tenant-events',
    '/tenant/:tenantId/events',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_access'],
    'native_equivalent',
  ],
  [
    'tenant-tenant-dead-letter-queue',
    '/tenant/:tenantId/dead-letter-queue',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'global_admin'],
    'cloud_only',
  ],
  [
    'tenant-tenant-trust-policies',
    '/tenant/:tenantId/trust-policies',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_workspace_access'],
    'cloud_only',
  ],
  [
    'tenant-tenant-decision-records',
    '/tenant/:tenantId/decision-records',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_workspace_access'],
    'cloud_only',
  ],
  [
    'tenant-tenant-billing',
    '/tenant/:tenantId/billing',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_admin_or_owner'],
    'cloud_only',
  ],
  [
    'tenant-tenant-org-settings',
    '/tenant/:tenantId/org-settings/info',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_access'],
    'cloud_only',
  ],
  [
    'tenant-tenant-settings',
    '/tenant/:tenantId/settings',
    ['tenant'],
    'tenant-governance-management',
    ['authenticated', 'tenant_member'],
    'cloud_only',
  ],
  [
    'project-project-overview',
    '/tenant/:tenantId/project/:projectId',
    ['tenant', 'project'],
    'project-workspace',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-workspaces',
    '/tenant/:tenantId/project/:projectId/workspaces',
    ['tenant', 'project', 'workspace'],
    'project-workspace',
    [
      'authenticated',
      'project_member',
      'workspace_member',
      'workspace_editor',
      'workspace_owner',
    ],
    'native_equivalent',
  ],
  [
    'project-blackboard-dynamic-project-blackboard',
    '/tenant/:tenantId/project/:projectId/blackboard',
    ['tenant', 'project', 'workspace'],
    'project-workspace',
    ['authenticated', 'workspace_member', 'workspace_editor', 'workspace_owner'],
    'native_equivalent',
  ],
  [
    'project-project-team',
    '/tenant/:tenantId/project/:projectId/team',
    ['tenant', 'project'],
    'project-workspace',
    ['authenticated', 'tenant_admin', 'project_member', 'project_admin'],
    'native_equivalent',
  ],
  [
    'project-project-memories',
    '/tenant/:tenantId/project/:projectId/memories',
    ['tenant', 'project'],
    'project-knowledge-base',
    [
      'authenticated',
      'project_member',
      'project_contributor',
      'memory_editor',
      'memory_admin',
    ],
    'native_equivalent',
  ],
  [
    'project-project-entities',
    '/tenant/:tenantId/project/:projectId/entities',
    ['tenant', 'project'],
    'project-knowledge-base',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-communities',
    '/tenant/:tenantId/project/:projectId/communities',
    ['tenant', 'project'],
    'project-knowledge-base',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-graph',
    '/tenant/:tenantId/project/:projectId/graph',
    ['tenant', 'project'],
    'project-knowledge-base',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-search',
    '/tenant/:tenantId/project/:projectId/advanced-search',
    ['tenant', 'project'],
    'project-discovery',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-schema',
    '/tenant/:tenantId/project/:projectId/schema',
    ['tenant', 'project'],
    'project-configuration',
    ['authenticated', 'project_member', 'project_contributor'],
    'native_equivalent',
  ],
  [
    'project-project-channels',
    '/tenant/:tenantId/project/:projectId/channels',
    ['tenant', 'project'],
    'project-configuration',
    [
      'authenticated',
      'tenant_member',
      'tenant_admin',
      'tenant_owner',
      'project_member',
      'project_admin',
      'project_owner',
    ],
    'native_equivalent',
  ],
  [
    'project-project-maintenance',
    '/tenant/:tenantId/project/:projectId/maintenance',
    ['tenant', 'project'],
    'project-configuration',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-cron-jobs',
    '/tenant/:tenantId/project/:projectId/cron-jobs',
    ['tenant', 'project'],
    'project-configuration',
    ['authenticated', 'project_member'],
    'native_equivalent',
  ],
  [
    'project-project-settings',
    '/tenant/:tenantId/project/:projectId/settings',
    ['tenant', 'project'],
    'project-configuration',
    ['authenticated', 'project_member', 'project_admin', 'project_owner'],
    'native_equivalent',
  ],
  [
    'project-agent-dashboard',
    '/tenant/:tenantId/project/:projectId/agent',
    ['tenant', 'project'],
    'project-workspace',
    ['authenticated'],
    'blocked_by_web_contract',
  ],
  [
    'project-agent-logs',
    '/tenant/:tenantId/project/:projectId/agent/logs',
    ['tenant', 'project'],
    'project-workspace',
    ['authenticated'],
    'blocked_by_web_contract',
  ],
  [
    'project-agent-patterns',
    '/tenant/:tenantId/project/:projectId/agent/patterns',
    ['tenant', 'project'],
    'project-workspace',
    ['authenticated'],
    'blocked_by_web_contract',
  ],
] as const satisfies readonly CanonicalRouteMetadata[];

export type CanonicalDesktopRouteId = (typeof CANONICAL_ROUTE_METADATA)[number][0];

export const CANONICAL_DESKTOP_ROUTE_IDS: readonly CanonicalDesktopRouteId[] =
  Object.freeze(CANONICAL_ROUTE_METADATA.map(([id]) => id));

const CANONICAL_DESKTOP_ROUTE_ID_SET = new Set<string>(CANONICAL_DESKTOP_ROUTE_IDS);

export function createDesktopCanonicalRouteCatalog<TModule>(
  loaders: Readonly<Record<string, unknown>>,
): DesktopRouteRegistry<TModule> {
  for (const id of Object.keys(loaders)) {
    if (!CANONICAL_DESKTOP_ROUTE_ID_SET.has(id)) {
      throw new Error(`desktop_route_loader_unknown:${id}`);
    }
  }
  for (const id of CANONICAL_DESKTOP_ROUTE_IDS) {
    if (!Object.hasOwn(loaders, id)) {
      throw new Error(`desktop_route_loader_missing:${id}`);
    }
    if (typeof loaders[id] !== 'function') {
      throw new Error(`desktop_route_loader_invalid:${id}`);
    }
  }

  const definitions = CANONICAL_ROUTE_METADATA.map(
    ([id, path, scope, navGroup, requiredPermission, localPolicy]) =>
      ({
        id,
        path,
        scope,
        navGroup,
        capability: id,
        requiredPermission,
        localPolicy,
        loader: loaders[id] as DesktopRouteLoader<TModule>,
      }) satisfies DesktopRouteDefinition<TModule>,
  );
  return createDesktopRouteRegistry(definitions);
}
