import { ProviderType } from '../types/memory';

export interface ProviderMeta {
  value: ProviderType;
  label: string;
  /** Lucide icon key, resolved to a component by `ProviderIcon` (see ICON_MAP there). */
  icon: string;
  description: string;
  apiKeyEnvVar: string;
  apiKeyPlaceholder: string;
  hasEmbedding: boolean;
  hasNativeRerank: boolean;
  baseUrlRequired: boolean;
  documentationUrl: string;
  hasRTC?: boolean;
}

export const PROVIDERS: ProviderMeta[] = [
  {
    value: 'openai',
    label: 'OpenAI',
    icon: 'bot',
    description: 'GPT-4, GPT-3.5, text-embedding models',
    apiKeyEnvVar: 'OPENAI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.openai.com/docs',
  },
  {
    value: 'openrouter',
    label: 'OpenRouter',
    icon: 'compass',
    description: 'Unified access to OpenAI/Anthropic/Meta and more',
    apiKeyEnvVar: 'OPENROUTER_API_KEY',
    apiKeyPlaceholder: 'sk-or-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://openrouter.ai/docs',
  },
  {
    value: 'anthropic',
    label: 'Anthropic',
    icon: 'brain',
    description: 'Claude 3.5/4 Sonnet, Haiku, Opus',
    apiKeyEnvVar: 'ANTHROPIC_API_KEY',
    apiKeyPlaceholder: 'sk-ant-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.anthropic.com',
  },
  {
    value: 'gemini',
    label: 'Google Gemini',
    icon: 'sparkles',
    description: 'Gemini Pro, Flash, text-embedding-004',
    apiKeyEnvVar: 'GEMINI_API_KEY',
    apiKeyPlaceholder: 'AIza...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://ai.google.dev/docs',
  },
  {
    value: 'dashscope',
    label: 'Alibaba Dashscope',
    icon: 'globe',
    description: 'Qwen-Max, Qwen-Plus, Qwen-Turbo, text-embedding-v3',
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://help.aliyun.com/zh/dashscope',
  },
  {
    value: 'dashscope_coding',
    label: 'Dashscope Coding',
    icon: 'code',
    description: 'Qwen3-Coder series with coding plan defaults',
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
  },
  {
    value: 'dashscope_embedding',
    label: 'Dashscope Embedding',
    icon: 'dna',
    description: 'Dashscope embedding-focused provider (text-embedding-v3)',
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://help.aliyun.com/zh/dashscope',
  },
  {
    value: 'dashscope_reranker',
    label: 'Dashscope Reranker',
    icon: 'book-open',
    description: 'Dashscope rerank-focused provider',
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: false,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://help.aliyun.com/zh/dashscope',
  },
  {
    value: 'kimi',
    label: 'Moonshot Kimi',
    icon: 'moon',
    description: 'Moonshot Kimi chat, embedding and rerank models',
    apiKeyEnvVar: 'KIMI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.moonshot.cn/docs',
  },
  {
    value: 'kimi_coding',
    label: 'Kimi Coding',
    icon: 'laptop',
    description: 'Kimi Coding plan models (k2p5, kimi-k2-thinking)',
    apiKeyEnvVar: 'KIMI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://www.kimi.com/coding/docs/en/third-party-agents.html',
  },
  {
    value: 'kimi_embedding',
    label: 'Kimi Embedding',
    icon: 'dna',
    description: 'Kimi embedding-focused provider (kimi-embedding-1)',
    apiKeyEnvVar: 'KIMI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.moonshot.cn/docs',
  },
  {
    value: 'kimi_reranker',
    label: 'Kimi Reranker',
    icon: 'book-open',
    description: 'Kimi rerank-focused provider (kimi-rerank-1)',
    apiKeyEnvVar: 'KIMI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.moonshot.cn/docs',
  },
  {
    value: 'deepseek',
    label: 'DeepSeek',
    icon: 'search',
    description: 'DeepSeek Chat and DeepSeek Coder models',
    apiKeyEnvVar: 'DEEPSEEK_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.deepseek.com/docs',
  },
  {
    value: 'minimax',
    label: 'MiniMax',
    icon: 'puzzle',
    description: 'abab6.5-chat, embo-01',
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.minimaxi.com/document',
  },
  {
    value: 'minimax_coding',
    label: 'MiniMax Coding',
    icon: 'wrench',
    description: 'MiniMax Coding plan models (M2.5 family)',
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.minimax.io/docs/coding-plan/intro',
  },
  {
    value: 'minimax_embedding',
    label: 'MiniMax Embedding',
    icon: 'dna',
    description: 'MiniMax embedding-focused provider (embo-01)',
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.minimaxi.com/document',
  },
  {
    value: 'minimax_reranker',
    label: 'MiniMax Reranker',
    icon: 'book-open',
    description: 'MiniMax rerank-focused provider',
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.minimaxi.com/document',
  },
  {
    value: 'zai',
    label: 'ZhipuAI 智谱', // i18n-ignore: brand name
    icon: 'gem',
    description: 'GLM-4-Plus, GLM-4-Flash, embedding-3',
    apiKeyEnvVar: 'ZAI_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://open.bigmodel.cn/dev/api',
  },
  {
    value: 'zai_coding',
    label: 'Z.AI Coding',
    icon: 'terminal',
    description: 'Z.AI coding plan models (GLM-5/4.7 family)',
    apiKeyEnvVar: 'ZAI_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.z.ai/devpack/overview',
  },
  {
    value: 'zai_embedding',
    label: 'Z.AI Embedding',
    icon: 'dna',
    description: 'Z.AI embedding-focused provider (embedding-3)',
    apiKeyEnvVar: 'ZAI_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://open.bigmodel.cn/dev/api',
  },
  {
    value: 'zai_reranker',
    label: 'Z.AI Reranker',
    icon: 'book-open',
    description: 'Z.AI rerank-focused provider',
    apiKeyEnvVar: 'ZAI_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://open.bigmodel.cn/dev/api',
  },
  {
    value: 'cohere',
    label: 'Cohere',
    icon: 'orbit',
    description: 'Command-R, embed-english-v3, native rerank',
    apiKeyEnvVar: 'COHERE_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.cohere.com',
  },
  {
    value: 'mistral',
    label: 'Mistral AI',
    icon: 'wind',
    description: 'Mistral-Large, Mistral-Small, mistral-embed',
    apiKeyEnvVar: 'MISTRAL_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.mistral.ai',
  },
  {
    value: 'groq',
    label: 'Groq',
    icon: 'zap',
    description: 'LLaMA 3, Mixtral (ultra-fast inference)',
    apiKeyEnvVar: 'GROQ_API_KEY',
    apiKeyPlaceholder: 'gsk_...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://console.groq.com/docs',
  },
  {
    value: 'azure_openai',
    label: 'Azure OpenAI',
    icon: 'cloud',
    description: 'Azure-hosted OpenAI models',
    apiKeyEnvVar: 'AZURE_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: true,
    documentationUrl: 'https://learn.microsoft.com/azure/ai-services/openai',
  },
  {
    value: 'bedrock',
    label: 'AWS Bedrock',
    icon: 'mountain',
    description: 'Claude, Titan, Llama on AWS',
    apiKeyEnvVar: 'AWS_ACCESS_KEY_ID',
    apiKeyPlaceholder: 'AKIA...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.aws.amazon.com/bedrock',
  },
  {
    value: 'vertex',
    label: 'Google Vertex AI',
    icon: 'network',
    description: 'Gemini on Google Cloud',
    apiKeyEnvVar: 'GOOGLE_APPLICATION_CREDENTIALS',
    apiKeyPlaceholder: 'JSON credentials',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://cloud.google.com/vertex-ai/docs',
  },
  {
    value: 'ollama',
    label: 'Ollama',
    icon: 'box',
    description: 'Local Ollama runtime (Open source models)',
    apiKeyEnvVar: 'OLLAMA_API_KEY',
    apiKeyPlaceholder: '(optional)',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://github.com/ollama/ollama',
  },
  {
    value: 'lmstudio',
    label: 'LM Studio',
    icon: 'monitor',
    description: 'Local OpenAI-compatible endpoint from LM Studio',
    apiKeyEnvVar: 'LMSTUDIO_API_KEY',
    apiKeyPlaceholder: '(optional)',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://lmstudio.ai/docs',
  },
  {
    value: 'volcengine',
    label: 'Volcengine 火山引擎',
    icon: 'flame',
    description: 'Doubao Seed 2.0 / 1.5 series, Vision, Embedding, Reranker, Seedream, Seedance',
    apiKeyEnvVar: 'VOLCENGINE_API_KEY',
    apiKeyPlaceholder: 'Enter your Volcengine API key',
    hasEmbedding: true,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://www.volcengine.com/docs/82379',
    hasRTC: true,
  },
  {
    value: 'volcengine_coding',
    label: 'Volcengine Coding',
    icon: 'code',
    description: 'Volcengine coding-optimized models',
    apiKeyEnvVar: 'VOLCENGINE_API_KEY',
    apiKeyPlaceholder: 'Enter your Volcengine API key',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://www.volcengine.com/docs/82379',
    hasRTC: true,
  },
  {
    value: 'volcengine_embedding',
    label: 'Volcengine Embedding',
    icon: 'dna',
    description: 'Volcengine embedding models (doubao-embedding)',
    apiKeyEnvVar: 'VOLCENGINE_API_KEY',
    apiKeyPlaceholder: 'Enter your Volcengine API key',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://www.volcengine.com/docs/82379',
    hasRTC: true,
  },
  {
    value: 'volcengine_reranker',
    label: 'Volcengine Reranker',
    icon: 'book-open',
    description: 'Volcengine reranking models',
    apiKeyEnvVar: 'VOLCENGINE_API_KEY',
    apiKeyPlaceholder: 'Enter your Volcengine API key',
    hasEmbedding: false,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://www.volcengine.com/docs/82379',
    hasRTC: true,
  },
];
