import { ProviderType } from '../types/memory';

export interface ProviderMeta {
  value: ProviderType;
  label: string;
  icon: string;
  description: string;
  apiKeyEnvVar: string;
  apiKeyPlaceholder: string;
  hasEmbedding: boolean;
  hasNativeRerank: boolean;
  baseUrlRequired: boolean;
  documentationUrl: string;
}

export const PROVIDERS: ProviderMeta[] = [
  {
    value: 'openai',
    label: 'OpenAI',
    icon: '🤖',
    description: 'GPT-4, GPT-3.5, text-embedding models',
    apiKeyEnvVar: 'OPENAI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.openai.com/docs',
  },
  {
    value: 'anthropic',
    label: 'Anthropic',
    icon: '🧠',
    description: 'Claude 3.5/4 Sonnet, Haiku, Opus',
    apiKeyEnvVar: 'ANTHROPIC_API_KEY',
    apiKeyPlaceholder: 'sk-ant-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.anthropic.com',
  },
  {
    value: 'gemini',
    label: 'Google Gemini',
    icon: '✨',
    description: 'Gemini Pro, Flash, text-embedding-004',
    apiKeyEnvVar: 'GEMINI_API_KEY',
    apiKeyPlaceholder: 'AIza...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://ai.google.dev/docs',
  },
  {
    value: 'dashscope',
    label: 'Alibaba Dashscope',
    icon: '🌐',
    description: 'Qwen-Max, Qwen-Plus, Qwen-Turbo, text-embedding-v3',
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://help.aliyun.com/zh/dashscope',
  },
  {
    value: 'kimi',
    label: 'Moonshot Kimi',
    icon: '🌙',
    description: 'Moonshot Kimi chat, embedding and rerank models',
    apiKeyEnvVar: 'KIMI_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.moonshot.cn/docs',
  },
  {
    value: 'deepseek',
    label: 'Deepseek',
    icon: '🔍',
    description: 'Deepseek-Chat, Deepseek-Coder (cost-effective)',
    apiKeyEnvVar: 'DEEPSEEK_API_KEY',
    apiKeyPlaceholder: 'sk-...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://platform.deepseek.com/docs',
  },
  {
    value: 'zai',
    label: 'ZhipuAI 智谱',
    icon: '🐲',
    description: 'GLM-4-Plus, GLM-4-Flash, embedding-3',
    apiKeyEnvVar: 'ZAI_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://open.bigmodel.cn/dev/api',
  },
  {
    value: 'cohere',
    label: 'Cohere',
    icon: '🔮',
    description: 'Command-R, embed-english-v3, native rerank',
    apiKeyEnvVar: 'COHERE_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: true,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.cohere.com',
  },
  {
    value: 'mistral',
    label: 'Mistral AI',
    icon: '🌪️',
    description: 'Mistral-Large, Mistral-Small, mistral-embed',
    apiKeyEnvVar: 'MISTRAL_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.mistral.ai',
  },
  {
    value: 'groq',
    label: 'Groq',
    icon: '⚡',
    description: 'LLaMA 3, Mixtral (ultra-fast inference)',
    apiKeyEnvVar: 'GROQ_API_KEY',
    apiKeyPlaceholder: 'gsk_...',
    hasEmbedding: false,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://console.groq.com/docs',
  },
  {
    value: 'azure_openai',
    label: 'Azure OpenAI',
    icon: '☁️',
    description: 'Azure-hosted OpenAI models',
    apiKeyEnvVar: 'AZURE_API_KEY',
    apiKeyPlaceholder: '...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: true,
    documentationUrl: 'https://learn.microsoft.com/azure/ai-services/openai',
  },
  {
    value: 'bedrock',
    label: 'AWS Bedrock',
    icon: '🏔️',
    description: 'Claude, Titan, Llama on AWS',
    apiKeyEnvVar: 'AWS_ACCESS_KEY_ID',
    apiKeyPlaceholder: 'AKIA...',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://docs.aws.amazon.com/bedrock',
  },
  {
    value: 'vertex',
    label: 'Google Vertex AI',
    icon: '📊',
    description: 'Gemini on Google Cloud',
    apiKeyEnvVar: 'GOOGLE_APPLICATION_CREDENTIALS',
    apiKeyPlaceholder: 'JSON credentials',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://cloud.google.com/vertex-ai/docs',
  },
  {
    value: 'ollama',
    label: 'Ollama',
    icon: '🦙',
    description: 'Local Ollama runtime (Open source models)',
    apiKeyEnvVar: 'OLLAMA_API_KEY',
    apiKeyPlaceholder: '(optional)',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://github.com/ollama/ollama',
  },
  {
    value: 'lmstudio',
    label: 'LM Studio',
    icon: '🖥️',
    description: 'Local OpenAI-compatible endpoint from LM Studio',
    apiKeyEnvVar: 'LMSTUDIO_API_KEY',
    apiKeyPlaceholder: '(optional)',
    hasEmbedding: true,
    hasNativeRerank: false,
    baseUrlRequired: false,
    documentationUrl: 'https://lmstudio.ai/docs',
  },
];
