"""FastAPI routers for the MemStack API."""

from src.infrastructure.adapters.primary.web.routers import (
    agent_websocket,
    ai_tools,
    auth,
    background_tasks,
    billing,
    data_export,
    enhanced_search,
    episodes,
    graph,
    llm_providers,
    maintenance,
    memories,
    notifications,
    project_sandbox,
    projects,
    recall,
    sandbox,
    schema,
    shares,
    support,
    tasks,
    tenants,
)

__all__ = [
    "agent_websocket",
    "auth",
    "tenants",
    "projects",
    "memories",
    "graph",
    "schema",
    "episodes",
    "recall",
    "enhanced_search",
    "data_export",
    "maintenance",
    "tasks",
    "ai_tools",
    "background_tasks",
    "billing",
    "llm_providers",
    "notifications",
    "project_sandbox",
    "sandbox",
    "shares",
    "support",
]
