"""FastAPI routers for the MemStack API."""

from src.infrastructure.adapters.primary.web.routers import (
    admin_dlq,
    ai_tools,
    auth,
    background_tasks,
    billing,
    blackboard,
    clusters,
    data_export,
    deploy,
    enhanced_search,
    episodes,
    genes,
    graph,
    instance_templates,
    instances,
    llm_providers,
    maintenance,
    memories,
    notifications,
    project_sandbox,
    projects,
    recall,
    sandbox,
    schema,
    shares,
    support,
    tasks,
    tenants,
    topology,
    workspace_tasks,
    workspaces,
)

# agent_websocket is imported lazily to avoid circular imports
# with the new websocket module

__all__ = [
    "admin_dlq",
    "ai_tools",
    "auth",
    "background_tasks",
    "billing",
    "blackboard",
    "clusters",
    "data_export",
    "deploy",
    "enhanced_search",
    "episodes",
    "genes",
    "graph",
    "instance_templates",
    "instances",
    "llm_providers",
    "maintenance",
    "memories",
    "notifications",
    "project_sandbox",
    "projects",
    "recall",
    "sandbox",
    "schema",
    "shares",
    "support",
    "tasks",
    "tenants",
    "topology",
    "workspace_tasks",
    "workspaces",
]
