"""Fence internal project schema commands without enrolling projects or wiring APIs.

Revision ID: 1a3218f58274
Revises: 32ed76ad9e43
Create Date: 2026-09-08 18:15:12.144284

Column/FK changes were autogenerated, then dependency ordering was reviewed.
PostgreSQL CHECK/trigger/function DDL is reviewed migration support, because
Alembic autogeneration does not discover the command protocol itself.
"""

from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa

from alembic import op

revision: str = "1a3218f58274"
down_revision: str | Sequence[str] | None = "32ed76ad9e43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

LIVE = ("entity_types", "edge_types", "edge_type_maps")
HISTORY = ("project_schema_changes", "project_schema_receipts")
FENCED = (*LIVE, "project_schema_heads", *HISTORY, "project_schema_tombstones")


def _functions() -> None:
    directory = Path(__file__).resolve().parents[1] / "schema_command_v1"
    for name in ("validation", "snapshots", "head", "fences"):
        # Each frozen support statement is one dollar-quoted CREATE FUNCTION.
        # Execute individually: asyncpg rejects multi-command prepares.
        for statement in (directory / f"{name}.sql").read_text().split("\n$$;"):
            if statement.strip():
                op.execute(statement + "\n$$;")


def _triggers() -> None:
    for table in LIVE:
        op.execute(
            f"CREATE TRIGGER project_schema_row_guard BEFORE INSERT OR UPDATE OR DELETE "
            f"ON {table} FOR EACH ROW EXECUTE FUNCTION project_schema_guard_row()"
        )
    op.execute(
        "CREATE TRIGGER project_schema_head_guard BEFORE INSERT OR UPDATE OR DELETE "
        "ON project_schema_heads FOR EACH ROW EXECUTE FUNCTION project_schema_guard_head()"
    )
    op.execute(
        "CREATE TRIGGER project_schema_head_history AFTER INSERT OR UPDATE "
        "ON project_schema_heads FOR EACH ROW EXECUTE FUNCTION project_schema_append_history()"
    )
    for table in HISTORY:
        op.execute(
            f"CREATE TRIGGER project_schema_history_guard BEFORE INSERT OR UPDATE OR DELETE "
            f"ON {table} FOR EACH ROW EXECUTE FUNCTION project_schema_guard_history()"
        )
    op.execute(
        "CREATE TRIGGER project_schema_tombstone_guard BEFORE INSERT OR UPDATE OR DELETE "
        "ON project_schema_tombstones FOR EACH ROW EXECUTE FUNCTION project_schema_guard_tombstone()"
    )
    op.execute(
        "CREATE TRIGGER project_schema_project_guard BEFORE UPDATE OR DELETE "
        "ON projects FOR EACH ROW EXECUTE FUNCTION project_schema_guard_project()"
    )
    for table in FENCED:
        op.execute(
            f"CREATE TRIGGER project_schema_truncate_guard BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION project_schema_guard_truncate()"
        )
        op.execute(
            f"CREATE CONSTRAINT TRIGGER project_schema_commit_guard AFTER INSERT OR UPDATE OR DELETE "
            f"ON {table} DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION project_schema_check_commit()"
        )


def upgrade() -> None:
    # Referenced unique keys must precede the autogenerated composite FKs.
    op.create_unique_constraint("uq_edge_type_project_id", "edge_types", ["project_id", "id"])
    op.create_unique_constraint("uq_entity_type_project_id", "entity_types", ["project_id", "id"])
    for field in ("source_type_id", "target_type_id", "edge_type_id"):
        op.add_column("edge_type_maps", sa.Column(field, sa.String(length=36), nullable=True))
    for name, field, target in (
        ("source", "source_type_id", "entity_types"),
        ("target", "target_type_id", "entity_types"),
        ("edge", "edge_type_id", "edge_types"),
    ):
        op.create_foreign_key(
            f"fk_schema_mapping_{name}_id",
            "edge_type_maps",
            target,
            ["project_id", field],
            ["project_id", "id"],
            initially="DEFERRED",
            deferrable=True,
        )
    op.drop_constraint("ck_project_schema_head_closed", "project_schema_heads", type_="check")
    op.create_check_constraint(
        "ck_project_schema_head_state",
        "project_schema_heads",
        "(mode = 'legacy' AND schema_id IS NULL AND revision IS NULL "
        "AND sequence = 0 AND NOT deleted) OR "
        "(mode = 'active' AND schema_id IS NOT NULL "
        "AND revision BETWEEN 1 AND 2147483647 AND sequence = revision)",
    )
    _functions()
    _triggers()


def downgrade() -> None:
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM project_schema_heads WHERE mode='active')
                OR EXISTS (SELECT 1 FROM project_schema_changes)
                OR EXISTS (SELECT 1 FROM project_schema_receipts)
                OR EXISTS (SELECT 1 FROM project_schema_tombstones)
                OR EXISTS (SELECT 1 FROM edge_type_maps WHERE source_type_id IS NOT NULL
                    OR target_type_id IS NOT NULL OR edge_type_id IS NOT NULL) THEN
                RAISE EXCEPTION USING MESSAGE='project_schema_command_rollback_requires_empty_state',
                    ERRCODE='23514';
            END IF;
        END $$
    """)
    for table in FENCED:
        op.execute(f"DROP TRIGGER project_schema_commit_guard ON {table}")
        op.execute(f"DROP TRIGGER project_schema_truncate_guard ON {table}")
    for table in LIVE:
        op.execute(f"DROP TRIGGER project_schema_row_guard ON {table}")
    for table in HISTORY:
        op.execute(f"DROP TRIGGER project_schema_history_guard ON {table}")
    op.execute("DROP TRIGGER project_schema_head_history ON project_schema_heads")
    op.execute("DROP TRIGGER project_schema_head_guard ON project_schema_heads")
    op.execute("DROP TRIGGER project_schema_tombstone_guard ON project_schema_tombstones")
    op.execute("DROP TRIGGER project_schema_project_guard ON projects")
    for signature in (
        "project_schema_check_commit()",
        "project_schema_guard_truncate()",
        "project_schema_guard_project()",
        "project_schema_guard_tombstone()",
        "project_schema_guard_history()",
        "project_schema_guard_row()",
        "project_schema_append_history()",
        "project_schema_guard_head()",
        "project_schema_successor(jsonb,jsonb)",
        "project_schema_members(jsonb)",
        "project_schema_current_document(text)",
        "project_schema_build_document(text,text,bigint,boolean,boolean)",
        "project_schema_document(jsonb)",
        "project_schema_portable_json(json)",
        "project_schema_definition(json)",
        "project_schema_json_metrics(json,integer)",
        "project_schema_text(jsonb,integer,boolean)",
        "project_schema_uuid(text)",
        "project_schema_assert(boolean,text)",
    ):
        op.execute(f"DROP FUNCTION {signature}")
    op.drop_constraint("ck_project_schema_head_state", "project_schema_heads", type_="check")
    op.create_check_constraint(
        "ck_project_schema_head_closed",
        "project_schema_heads",
        "mode = 'legacy' AND schema_id IS NULL AND revision IS NULL "
        "AND sequence = 0 AND NOT deleted",
    )
    for name in ("target", "edge", "source"):
        op.drop_constraint(f"fk_schema_mapping_{name}_id", "edge_type_maps", type_="foreignkey")
    for name in ("edge_type_id", "target_type_id", "source_type_id"):
        op.drop_column("edge_type_maps", name)
    op.drop_constraint("uq_entity_type_project_id", "entity_types", type_="unique")
    op.drop_constraint("uq_edge_type_project_id", "edge_types", type_="unique")
