"""add gene_reviews table

Revision ID: 28a01da0cee6
Revises: 02ebbece83c2
Create Date: 2026-03-27 23:01:53.873350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28a01da0cee6'
down_revision: Union[str, Sequence[str], None] = '02ebbece83c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gene_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes_market.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_gene_review_user_gene', 'gene_reviews', ['gene_id', 'user_id'], unique=True, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_gene_review_user_gene', table_name='gene_reviews', postgresql_where='deleted_at IS NULL')
    op.drop_table('gene_reviews')
    # ### end Alembic commands ###
