"""add durable scoped subagent run snapshots

Revision ID: 2d6a9c18e4b7
Revises: f3a9c51e7b24
Create Date: 2026-09-14 12:42:15.554016

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2d6a9c18e4b7"
down_revision: Union[str, Sequence[str], None] = "f3a9c51e7b24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subagent_run_snapshots_v2",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("runs", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id"),
    )
    op.create_index(
        op.f("ix_subagent_run_snapshots_v2_project_id"),
        "subagent_run_snapshots_v2",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subagent_run_snapshots_v2_tenant_id"),
        "subagent_run_snapshots_v2",
        ["tenant_id"],
        unique=False,
    )
    # Preserve the legacy global table; copy only rows with a real owner.
    # Dangling legacy conversations remain recoverable in the original table.
    op.execute("""
        DO $$
        BEGIN
          IF to_regclass('subagent_run_snapshots') IS NOT NULL THEN
            INSERT INTO subagent_run_snapshots_v2
              (conversation_id, tenant_id, project_id, runs, updated_at)
            SELECT c.id, c.tenant_id, c.project_id, entry.value::json, legacy.updated_at
            FROM subagent_run_snapshots legacy
            CROSS JOIN LATERAL jsonb_each(legacy.payload::jsonb -> 'conversations') entry
            JOIN conversations c ON c.id = entry.key
            WHERE legacy.id = 1
            ON CONFLICT (conversation_id) DO NOTHING;
          END IF;
        END $$
    """)


def downgrade() -> None:
    """Remove only the new snapshot relation; legacy storage remains untouched."""
    op.drop_index("ix_subagent_run_snapshots_v2_tenant_id", table_name="subagent_run_snapshots_v2")
    op.drop_index("ix_subagent_run_snapshots_v2_project_id", table_name="subagent_run_snapshots_v2")
    op.drop_table("subagent_run_snapshots_v2")
