"""add closed project schema storage

Revision ID: 32ed76ad9e43
Revises: 7c90e5134285
Create Date: 2026-09-08 17:21:09.680012

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32ed76ad9e43"
down_revision: str | Sequence[str] | None = "7c90e5134285"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reviewed dependency ordering: composite FK targets must exist first.
    op.create_unique_constraint("uq_projects_schema_scope", "projects", ["id", "tenant_id"])
    op.create_table(
        "project_schema_heads",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(length=16), server_default="legacy", nullable=False),
        sa.Column("schema_id", sa.String(length=36), nullable=True),
        sa.Column("format_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=True),
        sa.Column("sequence", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode = 'legacy' AND schema_id IS NULL AND revision IS NULL AND sequence = 0 AND NOT deleted",
            name="ck_project_schema_head_closed",
        ),
        sa.CheckConstraint("format_version = 1", name="ck_project_schema_head_format"),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="fk_project_schema_head_scope",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id"),
        sa.UniqueConstraint("schema_id", name="uq_project_schema_head_identity"),
        sa.UniqueConstraint(
            "tenant_id", "project_id", "schema_id", name="uq_project_schema_head_scope"
        ),
    )
    op.create_table(
        "project_schema_migration_findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("inspection_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("record_kind", sa.String(length=16), nullable=False),
        sa.Column("record_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("related_records", sa.JSON(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "record_kind IN ('project', 'entity_type', 'edge_type', 'mapping')",
            name="ck_project_schema_finding_kind",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tenant_id"],
            ["projects.id", "projects.tenant_id"],
            name="fk_project_schema_finding_scope",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_project_schema_finding_scan",
        "project_schema_migration_findings",
        ["tenant_id", "project_id", "inspection_id"],
        unique=False,
    )
    op.create_table(
        "project_schema_changes",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("schema_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("change_id", sa.String(length=36), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_kind IN ('bootstrap', 'mutation')", name="ck_project_schema_change_source"
        ),
        sa.CheckConstraint(
            "sequence > 0 AND revision BETWEEN 1 AND 2147483647",
            name="ck_project_schema_change_version",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id", "schema_id"],
            [
                "project_schema_heads.tenant_id",
                "project_schema_heads.project_id",
                "project_schema_heads.schema_id",
            ],
            name="fk_project_schema_change_head",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "project_id", "sequence"),
        sa.UniqueConstraint("schema_id", "revision", name="uq_project_schema_change_revision"),
        sa.UniqueConstraint(
            "tenant_id",
            "project_id",
            "actor_id",
            "change_id",
            name="uq_project_schema_change_request",
        ),
    )
    op.create_table(
        "project_schema_receipts",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("schema_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("change_id", sa.String(length=36), nullable=False),
        sa.Column("request_json", sa.Text(), nullable=False),
        sa.Column("receipt_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id", "schema_id"],
            [
                "project_schema_heads.tenant_id",
                "project_schema_heads.project_id",
                "project_schema_heads.schema_id",
            ],
            name="fk_project_schema_receipt_head",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "project_id", "schema_id", "actor_id", "change_id"),
    )
    op.create_table(
        "project_schema_tombstones",
        sa.Column("schema_id", sa.String(length=36), nullable=False),
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("deleted_revision", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('entity_type', 'edge_type', 'mapping')",
            name="ck_project_schema_tombstone_kind",
        ),
        sa.CheckConstraint(
            "deleted_revision BETWEEN 1 AND 2147483647", name="ck_project_schema_tombstone_revision"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id", "schema_id"],
            [
                "project_schema_heads.tenant_id",
                "project_schema_heads.project_id",
                "project_schema_heads.schema_id",
            ],
            name="fk_project_schema_tombstone_head",
        ),
        sa.PrimaryKeyConstraint("schema_id", "member_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Do not erase findings or any unexpected accepted history during rollback.
    op.execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM project_schema_changes)
        OR EXISTS (SELECT 1 FROM project_schema_receipts)
        OR EXISTS (SELECT 1 FROM project_schema_tombstones)
        OR EXISTS (SELECT 1 FROM project_schema_migration_findings)
      THEN
        RAISE EXCEPTION 'project_schema_storage_not_empty';
      END IF;
    END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_schema_tombstones")
    op.drop_table("project_schema_receipts")
    op.drop_table("project_schema_changes")
    op.drop_index("ix_project_schema_finding_scan", table_name="project_schema_migration_findings")
    op.drop_table("project_schema_migration_findings")
    op.drop_table("project_schema_heads")
    op.drop_constraint("uq_projects_schema_scope", "projects", type_="unique")
    # ### end Alembic commands ###
