"""add unified plugin marketplace records

Revision ID: 37d3b107b19c
Revises: 71e6b3a29c84
Create Date: 2026-09-23 09:07:19.421662

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37d3b107b19c"
down_revision: str | Sequence[str] | None = "71e6b3a29c84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_marketplace_records_v3",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("record_key", sa.String(length=256), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "project_id", "kind", "record_key", name="uq_marketplace_v3_scope_key"
        ),
    )
    op.create_index(
        op.f("ix_plugin_marketplace_records_v3_tenant_id"),
        "plugin_marketplace_records_v3",
        ["tenant_id"],
        unique=False,
    )


def downgrade() -> None:
    """Remove only marketplace-owned state."""
    op.drop_index(
        "ix_plugin_marketplace_records_v3_tenant_id", table_name="plugin_marketplace_records_v3"
    )
    op.drop_table("plugin_marketplace_records_v3")
