"""add exact automation permission receipts

Revision ID: 72847abc4b82
Revises: b353e93ff302
Create Date: 2026-09-07 18:30:18.421752

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72847abc4b82"
down_revision: str | Sequence[str] | None = "b353e93ff302"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agistack_automation_permission_intents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("actor_user_id", sa.String(), nullable=False),
        sa.Column("actor_api_key_id", sa.String(), nullable=True),
        sa.Column("runtime_revision", sa.BigInteger(), nullable=False),
        sa.Column("invocation_id", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("tool_version", sa.String(), nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("decision_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("expires_at > created_at", name="ck_automation_permission_expiry"),
        sa.CheckConstraint("runtime_revision > 0", name="ck_automation_permission_revision"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invocation_id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_table(
        "agistack_automation_permission_receipts",
        sa.Column("intent_id", sa.String(), nullable=False),
        sa.Column("responder_user_id", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("answer", sa.String(length=20), nullable=False),
        sa.Column("authority_revision", sa.BigInteger(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("answer IN ('allow_once', 'deny')", name="ck_permission_answer"),
        sa.CheckConstraint("authority_revision > 0", name="ck_permission_answer_revision"),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["agistack_automation_permission_intents.id"],
        ),
        sa.PrimaryKeyConstraint("intent_id"),
        sa.UniqueConstraint(
            "responder_user_id", "idempotency_key", name="uq_permission_answer_key"
        ),
    )
    op.create_table(
        "agistack_automation_permission_consumptions",
        sa.Column("intent_id", sa.String(), nullable=False),
        sa.Column("invocation_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("max_uses", sa.BigInteger(), nullable=False),
        sa.Column("use_count", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('awaiting_dispatch_binding', 'reserved', 'dispatched', 'completed', 'outcome_unknown', 'revoked')",
            name="ck_permission_consumption_status",
        ),
        sa.CheckConstraint(
            "max_uses = 1 AND use_count BETWEEN 0 AND 1", name="ck_permission_one_use"
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["agistack_automation_permission_receipts.intent_id"],
        ),
        sa.PrimaryKeyConstraint("intent_id"),
        sa.UniqueConstraint("invocation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agistack_automation_permission_consumptions")
    op.drop_table("agistack_automation_permission_receipts")
    op.drop_table("agistack_automation_permission_intents")
    # ### end Alembic commands ###
