"""add scheduler deployment cutover barrier

Revision ID: 7c90e5134285
Revises: b36acb66634d
Create Date: 2026-09-08 09:53:44.055512

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c90e5134285"
down_revision: str | Sequence[str] | None = "b36acb66634d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agistack_cron_scheduler_owners",
        sa.Column(
            "cutover_phase", sa.String(length=20), server_default="unverified", nullable=False
        ),
    )
    op.add_column(
        "agistack_cron_scheduler_owners",
        sa.Column("cutover_revision", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "agistack_cron_scheduler_owners",
        sa.Column("cutover_evidence", sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    )
    op.create_check_constraint(
        "ck_cron_scheduler_cutover_phase",
        "agistack_cron_scheduler_owners",
        "cutover_phase IN ('unverified', 'prepared', 'blocked', 'verified')",
    )
    op.create_check_constraint(
        "ck_cron_scheduler_cutover_revision",
        "agistack_cron_scheduler_owners",
        "cutover_revision >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("LOCK TABLE agistack_cron_scheduler_owners IN ACCESS EXCLUSIVE MODE")
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM agistack_cron_scheduler_owners
                WHERE cutover_phase <> 'unverified' OR cutover_revision <> 0
                   OR owner_kind = 'rust' OR lease_token IS NOT NULL
            ) THEN
                RAISE EXCEPTION 'Cannot remove a prepared or owned scheduler cutover barrier';
            END IF;
        END $$
    """)
    op.drop_constraint(
        "ck_cron_scheduler_cutover_revision", "agistack_cron_scheduler_owners", type_="check"
    )
    op.drop_constraint(
        "ck_cron_scheduler_cutover_phase", "agistack_cron_scheduler_owners", type_="check"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agistack_cron_scheduler_owners", "cutover_evidence")
    op.drop_column("agistack_cron_scheduler_owners", "cutover_revision")
    op.drop_column("agistack_cron_scheduler_owners", "cutover_phase")
    # ### end Alembic commands ###
