"""add instance cluster gene deploy template models

Revision ID: 91c6f36287e1
Revises: 13210a8c06aa
Create Date: 2026-03-26 22:17:48.458715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "91c6f36287e1"
down_revision: Union[str, Sequence[str], None] = "13210a8c06aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("compute_provider", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("health_status", sa.String(), nullable=True),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("proxy_endpoint", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("provider_config", sa.JSON(), nullable=False),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_clusters_tenant", "clusters", ["tenant_id"], unique=False)
    op.create_table(
        "genes_market",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_ref", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("synergies", sa.JSON(), nullable=False),
        sa.Column("parent_gene_id", sa.String(), nullable=True),
        sa.Column("created_by_instance_id", sa.String(), nullable=True),
        sa.Column("install_count", sa.Integer(), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=False),
        sa.Column("effectiveness_score", sa.Float(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="ix_genes_market_slug"),
    )
    op.create_index("ix_genes_market_category", "genes_market", ["category"], unique=False)
    op.create_index("ix_genes_market_tenant", "genes_market", ["tenant_id"], unique=False)
    op.create_table(
        "genomes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("gene_slugs", sa.JSON(), nullable=False),
        sa.Column("config_override", sa.JSON(), nullable=False),
        sa.Column("install_count", sa.Integer(), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="ix_genomes_slug"),
    )
    op.create_index("ix_genomes_tenant", "genomes", ["tenant_id"], unique=False)
    op.create_table(
        "instance_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("image_version", sa.String(), nullable=True),
        sa.Column("default_config", sa.JSON(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("install_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="ix_instance_templates_slug"),
    )
    op.create_index(
        "ix_instance_templates_tenant", "instance_templates", ["tenant_id"], unique=False
    )
    op.create_table(
        "gene_ratings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("gene_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes_market.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gene_id", "user_id", name="uq_gene_ratings_gene_user"),
    )
    op.create_table(
        "genome_ratings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("genome_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["genome_id"],
            ["genomes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("genome_id", "user_id", name="uq_genome_ratings_genome_user"),
    )
    op.create_table(
        "instances",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("cluster_id", sa.String(), nullable=True),
        sa.Column("namespace", sa.String(), nullable=True),
        sa.Column("image_version", sa.String(), nullable=False),
        sa.Column("replicas", sa.Integer(), nullable=False),
        sa.Column("cpu_request", sa.String(), nullable=False),
        sa.Column("cpu_limit", sa.String(), nullable=False),
        sa.Column("mem_request", sa.String(), nullable=False),
        sa.Column("mem_limit", sa.String(), nullable=False),
        sa.Column("service_type", sa.String(), nullable=False),
        sa.Column("ingress_domain", sa.String(), nullable=True),
        sa.Column("proxy_token", sa.String(), nullable=True),
        sa.Column("env_vars", sa.JSON(), nullable=False),
        sa.Column("quota_cpu", sa.String(), nullable=True),
        sa.Column("quota_memory", sa.String(), nullable=True),
        sa.Column("quota_max_pods", sa.Integer(), nullable=True),
        sa.Column("storage_class", sa.String(), nullable=True),
        sa.Column("storage_size", sa.String(), nullable=True),
        sa.Column("advanced_config", sa.JSON(), nullable=False),
        sa.Column("llm_providers", sa.JSON(), nullable=False),
        sa.Column("pending_config", sa.JSON(), nullable=False),
        sa.Column("available_replicas", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("health_status", sa.String(), nullable=True),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("compute_provider", sa.String(), nullable=True),
        sa.Column("runtime", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=True),
        sa.Column("hex_position_q", sa.Integer(), nullable=True),
        sa.Column("hex_position_r", sa.Integer(), nullable=True),
        sa.Column("agent_display_name", sa.String(), nullable=True),
        sa.Column("agent_label", sa.String(), nullable=True),
        sa.Column("theme_color", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="ix_instances_slug"),
    )
    op.create_index("ix_instances_tenant", "instances", ["tenant_id"], unique=False)
    op.create_index("ix_instances_workspace", "instances", ["workspace_id"], unique=False)
    op.create_table(
        "template_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("template_id", sa.String(), nullable=False),
        sa.Column("item_type", sa.String(), nullable=False),
        sa.Column("item_slug", sa.String(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["instance_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_template_items_template", "template_items", ["template_id"], unique=False)
    op.create_table(
        "deploy_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("image_version", sa.String(), nullable=True),
        sa.Column("replicas", sa.Integer(), nullable=True),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deploy_records_instance", "deploy_records", ["instance_id"], unique=False)
    op.create_index("ix_deploy_records_status", "deploy_records", ["status"], unique=False)
    op.create_table(
        "evolution_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("gene_id", sa.String(), nullable=True),
        sa.Column("genome_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("gene_name", sa.String(), nullable=False),
        sa.Column("gene_slug", sa.String(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes_market.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genome_id"],
            ["genomes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_evolution_events_instance", "evolution_events", ["instance_id"], unique=False
    )
    op.create_table(
        "gene_effect_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("gene_id", sa.String(), nullable=False),
        sa.Column("metric_type", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes_market.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_gene_effect_logs_instance_gene",
        "gene_effect_logs",
        ["instance_id", "gene_id"],
        unique=False,
    )
    op.create_table(
        "instance_genes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("gene_id", sa.String(), nullable=False),
        sa.Column("genome_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("installed_version", sa.String(), nullable=True),
        sa.Column("learning_output", sa.Text(), nullable=True),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("agent_self_eval", sa.Text(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("variant_published", sa.Boolean(), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes_market.id"],
        ),
        sa.ForeignKeyConstraint(
            ["genome_id"],
            ["genomes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_instance_genes_gene", "instance_genes", ["gene_id"], unique=False)
    op.create_index("ix_instance_genes_instance", "instance_genes", ["instance_id"], unique=False)
    op.create_table(
        "instance_members",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_id", "user_id", name="uq_instance_members_user_instance"),
    )
    op.create_index(
        "ix_instance_members_instance", "instance_members", ["instance_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_instance_members_instance", table_name="instance_members")
    op.drop_table("instance_members")
    op.drop_index("ix_instance_genes_instance", table_name="instance_genes")
    op.drop_index("ix_instance_genes_gene", table_name="instance_genes")
    op.drop_table("instance_genes")
    op.drop_index("ix_gene_effect_logs_instance_gene", table_name="gene_effect_logs")
    op.drop_table("gene_effect_logs")
    op.drop_index("ix_evolution_events_instance", table_name="evolution_events")
    op.drop_table("evolution_events")
    op.drop_index("ix_deploy_records_status", table_name="deploy_records")
    op.drop_index("ix_deploy_records_instance", table_name="deploy_records")
    op.drop_table("deploy_records")
    op.drop_index("ix_template_items_template", table_name="template_items")
    op.drop_table("template_items")
    op.drop_index("ix_instances_workspace", table_name="instances")
    op.drop_index("ix_instances_tenant", table_name="instances")
    op.drop_table("instances")
    op.drop_table("genome_ratings")
    op.drop_table("gene_ratings")
    op.drop_index("ix_instance_templates_tenant", table_name="instance_templates")
    op.drop_table("instance_templates")
    op.drop_index("ix_genomes_tenant", table_name="genomes")
    op.drop_table("genomes")
    op.drop_index("ix_genes_market_tenant", table_name="genes_market")
    op.drop_index("ix_genes_market_category", table_name="genes_market")
    op.drop_table("genes_market")
    op.drop_index("ix_clusters_tenant", table_name="clusters")
    op.drop_table("clusters")
    # ### end Alembic commands ###
