"""Create the PostgreSQL schema required by the vendored Avernet BCS stores.

Revision ID: a9c0d1e2f3a4
Revises: b4e6f8a0c2d4
Create Date: 2026-08-10

The BCS binary never applies this DDL. MemStack Alembic remains the only Cloud
schema authority, while Desktop Local uses the BCS SQLite migration path.
"""

from collections.abc import Iterable

import sqlalchemy as sa

from alembic import op

revision = "a9c0d1e2f3a4"
down_revision = "b4e6f8a0c2d4"
branch_labels = None
depends_on = None

SCHEMA = "avernet"

_TABLE_DDL: tuple[str, ...] = (
    """
    CREATE TABLE avernet.bcs_actor_relations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        from_id VARCHAR(256) NOT NULL,
        to_id VARCHAR(256) NOT NULL,
        env VARCHAR(32) NOT NULL,
        kinds BIGINT NOT NULL DEFAULT 0 CHECK (kinds >= 0),
        allow BIGINT NOT NULL DEFAULT 0 CHECK (allow >= 0),
        deny BIGINT NOT NULL DEFAULT 0 CHECK (deny >= 0),
        is_creator BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT uq_bcs_actor_relations_from_to_env UNIQUE (from_id, to_id, env)
    )
    """,
    """
    CREATE TABLE avernet.bcs_bots (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        bot_uuid VARCHAR(256) NOT NULL,
        name VARCHAR(1024) NOT NULL,
        bot_info TEXT,
        session_token VARCHAR(512),
        registered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(64) NOT NULL,
        visibility VARCHAR(32) NOT NULL DEFAULT 'public',
        created_by VARCHAR(512),
        actor_kind VARCHAR(16) NOT NULL DEFAULT 'bot',
        status VARCHAR(16) NOT NULL DEFAULT 'online',
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        agent_code VARCHAR(256),
        CONSTRAINT uq_bcs_bots_session_token UNIQUE (session_token),
        CONSTRAINT uq_bcs_bots_bot_env UNIQUE (bot_uuid, env)
    )
    """,
    """
    CREATE TABLE avernet.bcs_collaboration_definitions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        definition_id VARCHAR(128) NOT NULL,
        version INTEGER NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT,
        source_format VARCHAR(16) NOT NULL DEFAULT 'yaml',
        content_hash CHAR(64) NOT NULL,
        blob_id VARCHAR(128),
        yaml_text TEXT,
        normalized_json JSONB,
        metadata_json JSONB,
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        created_by VARCHAR(128),
        CONSTRAINT uq_bcs_collaboration_definitions_version
            UNIQUE (env, definition_id, version)
    )
    """,
    """
    CREATE TABLE avernet.bcs_collaboration_definition_blobs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        blob_id VARCHAR(128) NOT NULL,
        content_hash CHAR(64) NOT NULL,
        content_encoding VARCHAR(32) NOT NULL DEFAULT 'identity',
        content_size BIGINT NOT NULL CHECK (content_size >= 0),
        content BYTEA,
        external_uri VARCHAR(1024),
        created_by VARCHAR(128),
        CONSTRAINT uq_bcs_collaboration_definition_blobs_id UNIQUE (env, blob_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_collaboration_events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        state_machine_run_id VARCHAR(128) NOT NULL,
        node_id VARCHAR(128),
        attempt INTEGER,
        event_type VARCHAR(64) NOT NULL,
        payload_json JSONB,
        created_at_ms BIGINT NOT NULL CHECK (created_at_ms >= 0),
        record_status VARCHAR(16) NOT NULL DEFAULT 'active'
    )
    """,
    """
    CREATE TABLE avernet.bcs_collaboration_templates (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        template_id VARCHAR(128) NOT NULL,
        source_type VARCHAR(16) NOT NULL DEFAULT 'system',
        visibility VARCHAR(16) NOT NULL DEFAULT 'public',
        owner_user_id VARCHAR(32),
        priority BIGINT NOT NULL DEFAULT 4294967295 CHECK (priority >= 0),
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        created_by VARCHAR(128),
        updated_by VARCHAR(128),
        CONSTRAINT uq_bcs_collaboration_templates_id UNIQUE (env, template_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_collaboration_template_contents (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        template_id VARCHAR(128) NOT NULL,
        lang VARCHAR(64) NOT NULL,
        name VARCHAR(256) NOT NULL,
        description TEXT,
        participant_summary_json TEXT NOT NULL,
        definition_json TEXT NOT NULL,
        yaml_text TEXT NOT NULL,
        yaml_sha256 CHAR(64) NOT NULL,
        version BIGINT NOT NULL DEFAULT 1 CHECK (version >= 0),
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        CONSTRAINT uq_bcs_collaboration_template_contents_lang
            UNIQUE (env, template_id, lang)
    )
    """,
    """
    CREATE TABLE avernet.bcs_collaboration_template_tags (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        template_id VARCHAR(128) NOT NULL,
        tag VARCHAR(64) NOT NULL,
        CONSTRAINT uq_bcs_collaboration_template_tags_tag UNIQUE (env, template_id, tag)
    )
    """,
    """
    CREATE TABLE avernet.bcs_friendships (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        left_bot VARCHAR(255) NOT NULL,
        right_bot VARCHAR(255) NOT NULL,
        env VARCHAR(32) NOT NULL DEFAULT 'dev',
        CONSTRAINT uq_bcs_friendships_pair UNIQUE (env, left_bot, right_bot)
    )
    """,
    """
    CREATE TABLE avernet.bcs_friend_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        request_id VARCHAR(64) NOT NULL,
        from_bot VARCHAR(255) NOT NULL,
        to_bot VARCHAR(255) NOT NULL,
        status VARCHAR(32) NOT NULL DEFAULT 'pending',
        env VARCHAR(32) NOT NULL DEFAULT 'dev',
        CONSTRAINT uq_bcs_friend_requests_id UNIQUE (request_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_groups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        group_id VARCHAR(64) NOT NULL,
        label VARCHAR(4096),
        status VARCHAR(64) NOT NULL,
        driver_bot VARCHAR(512) NOT NULL,
        originator VARCHAR(512),
        env VARCHAR(64) NOT NULL,
        routing_policy_json TEXT,
        context TEXT,
        group_kind VARCHAR(16) NOT NULL DEFAULT 'normal',
        dm_pair_key VARCHAR(513),
        service_group_uuid VARCHAR(256),
        service_mode VARCHAR(128),
        version INTEGER NOT NULL DEFAULT 1,
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        lifecycle_status VARCHAR(16) NOT NULL DEFAULT 'active',
        group_strategy VARCHAR(32) NOT NULL DEFAULT 'chat',
        participants TEXT,
        service_spec TEXT,
        created_by VARCHAR(128),
        visibility VARCHAR(32) NOT NULL DEFAULT 'private',
        CONSTRAINT uq_bcs_groups_group_env UNIQUE (group_id, env),
        CONSTRAINT uq_bcs_groups_dm_pair UNIQUE (env, dm_pair_key)
    )
    """,
    """
    CREATE TABLE avernet.bcs_group_participants (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        group_id VARCHAR(64) NOT NULL,
        bot_uuid VARCHAR(256) NOT NULL,
        role VARCHAR(256) NOT NULL,
        env VARCHAR(64) NOT NULL,
        actor_kind VARCHAR(16) NOT NULL DEFAULT 'bot',
        mode VARCHAR(16) NOT NULL DEFAULT 'auto',
        CONSTRAINT uq_bcs_group_participants_actor UNIQUE (env, group_id, bot_uuid)
    )
    """,
    """
    CREATE TABLE avernet.bcs_group_runtime_bindings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        group_id VARCHAR(64) NOT NULL,
        group_version INTEGER NOT NULL,
        next_group_version INTEGER NOT NULL DEFAULT 2147483647,
        default_definition_id VARCHAR(128),
        default_definition_version INTEGER,
        definition_content_hash CHAR(64),
        definition_blob_id VARCHAR(128),
        auto_start_on_service_invocation BOOLEAN NOT NULL DEFAULT FALSE,
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        updated_by VARCHAR(128),
        participant_bindings_json JSONB,
        CONSTRAINT uq_bcs_group_runtime_bindings_version
            UNIQUE (env, group_id, group_version)
    )
    """,
    """
    CREATE TABLE avernet.bcs_group_sessions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        session_id VARCHAR(64) NOT NULL,
        group_id VARCHAR(64) NOT NULL,
        env VARCHAR(32) NOT NULL DEFAULT 'prod',
        status VARCHAR(16) NOT NULL DEFAULT 'running',
        session_kind VARCHAR(32) NOT NULL DEFAULT 'chat',
        session_title VARCHAR(256),
        group_version INTEGER,
        caller_id VARCHAR(256),
        input TEXT,
        output TEXT,
        error_message TEXT,
        callback_status VARCHAR(32),
        activation_count INTEGER NOT NULL DEFAULT 1,
        caller_principal VARCHAR(128),
        created_by VARCHAR(128),
        participants TEXT NOT NULL,
        completed_at BIGINT CHECK (completed_at >= 0),
        meta TEXT,
        current_msg_seq BIGINT NOT NULL DEFAULT 0,
        participant_join_seq JSONB,
        CONSTRAINT uq_bcs_group_sessions_id UNIQUE (env, session_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_messages (
        message_id VARCHAR(64) PRIMARY KEY,
        group_id VARCHAR(64) NOT NULL,
        session_id VARCHAR(128) NOT NULL,
        session_seq BIGINT NOT NULL,
        env VARCHAR(32) NOT NULL,
        sender_id VARCHAR(256) NOT NULL,
        sender_type VARCHAR(32) NOT NULL,
        message_type VARCHAR(64) NOT NULL,
        content TEXT NOT NULL,
        client_msg_id VARCHAR(256),
        status VARCHAR(32) NOT NULL DEFAULT 'normal',
        created_at BIGINT NOT NULL CHECK (created_at >= 0),
        ttl_until BIGINT CHECK (ttl_until >= 0),
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        run_id VARCHAR(256) NOT NULL DEFAULT '',
        owner_bot_id VARCHAR(256),
        workspace_id VARCHAR(128),
        mentions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
        parent_message_id VARCHAR(128),
        metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        source_hash CHAR(64),
        CONSTRAINT ck_bcs_messages_source_hash
            CHECK (source_hash IS NULL OR source_hash ~ '^[0-9a-f]{64}$'),
        CONSTRAINT uq_bcs_messages_session_seq UNIQUE (session_id, session_seq)
    )
    """,
    """
    CREATE TABLE avernet.bcs_providers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        provider_id VARCHAR(256) NOT NULL,
        env VARCHAR(64) NOT NULL,
        name VARCHAR(1024) NOT NULL,
        config TEXT NOT NULL,
        disabled BOOLEAN NOT NULL DEFAULT FALSE,
        created_by VARCHAR(256) NOT NULL,
        owners TEXT NOT NULL,
        CONSTRAINT uq_bcs_providers_id UNIQUE (env, provider_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_provider_bot_bindings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        bot_uuid VARCHAR(256) NOT NULL,
        provider_id VARCHAR(256) NOT NULL,
        provider_bot_ref VARCHAR(256) NOT NULL,
        env VARCHAR(64) NOT NULL,
        disabled BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT uq_bcs_provider_bot_bindings_ref
            UNIQUE (env, provider_id, provider_bot_ref),
        CONSTRAINT uq_bcs_provider_bot_bindings_bot UNIQUE (env, bot_uuid)
    )
    """,
    """
    CREATE TABLE avernet.bcs_provider_credentials (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        provider_id VARCHAR(256) NOT NULL,
        env VARCHAR(64) NOT NULL,
        credential_kind VARCHAR(128) NOT NULL,
        secret_value VARCHAR(512) NOT NULL,
        disabled BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT uq_bcs_provider_credentials_kind
            UNIQUE (env, provider_id, credential_kind)
    )
    """,
    """
    CREATE TABLE avernet.bcs_channel_bindings (
        id VARCHAR(64) PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        channel_type VARCHAR(32) NOT NULL,
        account_ref VARCHAR(128) NOT NULL,
        target_json TEXT NOT NULL,
        group_chat_scope VARCHAR(32),
        visibility VARCHAR(32) NOT NULL,
        env VARCHAR(32) NOT NULL,
        status VARCHAR(16) NOT NULL,
        created_by VARCHAR(256),
        config_json TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE avernet.bcs_channel_conversations (
        binding_id VARCHAR(64) NOT NULL,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        im_conversation_id VARCHAR(256) NOT NULL,
        im_conversation_type VARCHAR(16) NOT NULL,
        session_scope VARCHAR(32) NOT NULL,
        im_user_id VARCHAR(128) NOT NULL DEFAULT '',
        bcs_session_id VARCHAR(128) NOT NULL,
        last_active_at BIGINT NOT NULL CHECK (last_active_at >= 0),
        PRIMARY KEY (binding_id, im_conversation_id, session_scope, im_user_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_channel_im_participants (
        channel_type VARCHAR(32) NOT NULL,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        account_ref VARCHAR(128) NOT NULL,
        im_user_id VARCHAR(128) NOT NULL,
        actor_id VARCHAR(256) NOT NULL,
        display_name VARCHAR(256),
        PRIMARY KEY (channel_type, account_ref, im_user_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_human_input_requests (
        request_id VARCHAR(512) PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        session_id VARCHAR(128) NOT NULL,
        run_id VARCHAR(128) NOT NULL,
        node_id VARCHAR(128) NOT NULL,
        binding_id VARCHAR(64) NOT NULL,
        channel_type VARCHAR(32) NOT NULL,
        account_ref VARCHAR(128) NOT NULL,
        notification_mode VARCHAR(32) NOT NULL,
        reply_scope_key VARCHAR(768) NOT NULL,
        active_slot_key VARCHAR(768),
        assignee_actor_id VARCHAR(256) NOT NULL,
        im_conversation_id VARCHAR(256) NOT NULL,
        im_conversation_type VARCHAR(16) NOT NULL,
        im_user_id VARCHAR(128),
        node_display_name VARCHAR(256) NOT NULL,
        notification_text TEXT NOT NULL,
        deadline_ms BIGINT NOT NULL CHECK (deadline_ms >= 0),
        status VARCHAR(32) NOT NULL,
        provider_message_ref VARCHAR(256),
        delivery_attempts BIGINT NOT NULL DEFAULT 0 CHECK (delivery_attempts >= 0),
        last_delivery_error TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        activated_at BIGINT CHECK (activated_at >= 0),
        responded_at BIGINT CHECK (responded_at >= 0),
        CONSTRAINT uq_bcs_human_input_requests_active_slot UNIQUE (active_slot_key)
    )
    """,
    """
    CREATE TABLE avernet.bcs_session_participants (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        session_id VARCHAR(64) NOT NULL,
        group_id VARCHAR(64) NOT NULL,
        bot_uuid VARCHAR(256) NOT NULL,
        role VARCHAR(64) NOT NULL,
        env VARCHAR(32) NOT NULL DEFAULT 'prod',
        collected BOOLEAN NOT NULL DEFAULT FALSE,
        collected_at TIMESTAMPTZ,
        CONSTRAINT uq_bcs_session_participants_actor UNIQUE (env, session_id, bot_uuid)
    )
    """,
    """
    CREATE TABLE avernet.bcs_state_machine_definition_snapshots (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        run_id VARCHAR(128) NOT NULL,
        group_id VARCHAR(64) NOT NULL,
        session_id VARCHAR(64) NOT NULL,
        group_version INTEGER NOT NULL,
        definition_id VARCHAR(128) NOT NULL,
        definition_version INTEGER NOT NULL,
        definition_content_hash CHAR(64) NOT NULL,
        snapshot_blob_id VARCHAR(128),
        snapshot_json JSONB,
        source_format VARCHAR(16) NOT NULL DEFAULT 'yaml',
        resolved_participant_bindings_json JSONB,
        CONSTRAINT uq_bcs_state_machine_definition_snapshots_run UNIQUE (env, run_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_state_machine_delivery_correlations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        state_machine_run_id VARCHAR(128) NOT NULL,
        node_id VARCHAR(128) NOT NULL,
        attempt INTEGER NOT NULL,
        assignee_bot_id VARCHAR(128) NOT NULL,
        delivery_request_id VARCHAR(191) NOT NULL,
        bot_delivery_run_id VARCHAR(191),
        created_at_ms BIGINT NOT NULL CHECK (created_at_ms >= 0),
        updated_at_ms BIGINT NOT NULL CHECK (updated_at_ms >= 0),
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        CONSTRAINT uq_bcs_state_machine_delivery_request
            UNIQUE (env, delivery_request_id),
        CONSTRAINT uq_bcs_state_machine_delivery_bot_run
            UNIQUE (env, bot_delivery_run_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_state_machine_node_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        run_id VARCHAR(128) NOT NULL,
        node_id VARCHAR(128) NOT NULL,
        status VARCHAR(32) NOT NULL,
        attempt INTEGER NOT NULL DEFAULT 0,
        node_timeout_ms BIGINT CHECK (node_timeout_ms >= 0),
        timeout_deadline_ms BIGINT CHECK (timeout_deadline_ms >= 0),
        max_attempts INTEGER NOT NULL DEFAULT 1,
        assignee_bot_id VARCHAR(128) NOT NULL,
        delivery_request_id VARCHAR(191),
        bot_delivery_run_id VARCHAR(191),
        artifact_text TEXT,
        error_message TEXT,
        started_at_ms BIGINT CHECK (started_at_ms >= 0),
        completed_at_ms BIGINT CHECK (completed_at_ms >= 0),
        outcome VARCHAR(128),
        responded_by VARCHAR(256),
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        CONSTRAINT uq_bcs_state_machine_node_runs_node UNIQUE (env, run_id, node_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_state_machine_runs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        run_id VARCHAR(128) NOT NULL,
        definition_id VARCHAR(128) NOT NULL,
        definition_version INTEGER NOT NULL,
        group_id VARCHAR(64) NOT NULL,
        group_version INTEGER NOT NULL,
        session_id VARCHAR(64) NOT NULL,
        created_by VARCHAR(128),
        status VARCHAR(32) NOT NULL,
        input_json JSONB,
        output_text TEXT,
        error_message TEXT,
        created_at_ms BIGINT NOT NULL CHECK (created_at_ms >= 0),
        updated_at_ms BIGINT NOT NULL CHECK (updated_at_ms >= 0),
        completed_at_ms BIGINT CHECK (completed_at_ms >= 0),
        record_status VARCHAR(16) NOT NULL DEFAULT 'active',
        CONSTRAINT uq_bcs_state_machine_runs_id UNIQUE (env, run_id)
    )
    """,
    """
    CREATE TABLE avernet.bcs_user_identities (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id VARCHAR(128) NOT NULL,
        auth_source VARCHAR(64) NOT NULL,
        external_user_id VARCHAR(512) NOT NULL,
        user_name VARCHAR(256),
        external_user_name VARCHAR(256),
        avatar VARCHAR(1024),
        token VARCHAR(64),
        token_expire_at TIMESTAMPTZ,
        env VARCHAR(64) NOT NULL,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_bcs_user_identities_user UNIQUE (user_id),
        CONSTRAINT uq_bcs_user_identities_external
            UNIQUE (auth_source, external_user_id, env)
    )
    """,
    """
    CREATE TABLE avernet.bcs_organizations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(64) NOT NULL,
        code VARCHAR(256) NOT NULL,
        name VARCHAR(256) NOT NULL,
        description TEXT,
        managing_provider_id VARCHAR(256) NOT NULL,
        disabled BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT uq_bcs_organizations_code UNIQUE (env, code)
    )
    """,
    """
    CREATE TABLE avernet.bcs_organization_members (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(64) NOT NULL,
        organization_code VARCHAR(256) NOT NULL,
        bot_uuid VARCHAR(256) NOT NULL,
        role VARCHAR(256),
        disabled BOOLEAN NOT NULL DEFAULT FALSE,
        CONSTRAINT uq_bcs_organization_members_actor
            UNIQUE (env, organization_code, bot_uuid)
    )
    """,
    """
    CREATE TABLE avernet.bcs_session_files (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        gmt_create TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        gmt_modified TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        env VARCHAR(32) NOT NULL,
        file_id VARCHAR(32) NOT NULL,
        session_id VARCHAR(64) NOT NULL,
        owner_actor_kind VARCHAR(16) NOT NULL,
        owner_actor_id VARCHAR(256) NOT NULL,
        file_name VARCHAR(512) NOT NULL,
        mime_type VARCHAR(256) NOT NULL,
        size BIGINT NOT NULL CHECK (size >= 0),
        sha256 CHAR(64),
        storage_backend VARCHAR(32) NOT NULL,
        object_handle TEXT NOT NULL,
        status VARCHAR(16) NOT NULL,
        CONSTRAINT uq_bcs_session_files_session UNIQUE (env, session_id, file_id),
        CONSTRAINT uq_bcs_session_files_id UNIQUE (env, file_id)
    )
    """,
)

_INDEXES: tuple[tuple[str, str, tuple[str, ...]], ...] = (
    ("ix_bcs_actor_relations_to_env", "bcs_actor_relations", ("to_id", "env")),
    ("ix_bcs_actor_relations_creator", "bcs_actor_relations", ("from_id", "env", "is_creator")),
    ("ix_bcs_bots_actor_kind", "bcs_bots", ("actor_kind",)),
    ("ix_bcs_bots_agent_code", "bcs_bots", ("agent_code",)),
    ("ix_bcs_collab_definition_hash", "bcs_collaboration_definitions", ("env", "content_hash")),
    ("ix_bcs_collab_events_run", "bcs_collaboration_events", ("env", "state_machine_run_id", "id")),
    (
        "ix_bcs_templates_status",
        "bcs_collaboration_templates",
        ("env", "record_status", "priority"),
    ),
    ("ix_bcs_friendships_left", "bcs_friendships", ("env", "left_bot")),
    ("ix_bcs_friendships_right", "bcs_friendships", ("env", "right_bot")),
    ("ix_bcs_friend_requests_from", "bcs_friend_requests", ("env", "from_bot", "status")),
    ("ix_bcs_friend_requests_to", "bcs_friend_requests", ("env", "to_bot", "status")),
    ("ix_bcs_groups_driver", "bcs_groups", ("env", "driver_bot")),
    ("ix_bcs_groups_visibility", "bcs_groups", ("env", "visibility")),
    ("ix_bcs_group_participants_bot", "bcs_group_participants", ("env", "bot_uuid")),
    (
        "ix_bcs_group_bindings_current",
        "bcs_group_runtime_bindings",
        ("env", "group_id", "record_status", "next_group_version"),
    ),
    ("ix_bcs_group_sessions_status", "bcs_group_sessions", ("env", "group_id", "status")),
    (
        "ix_bcs_group_sessions_kind",
        "bcs_group_sessions",
        ("env", "group_id", "session_kind", "status"),
    ),
    ("ix_bcs_messages_group_created", "bcs_messages", ("env", "group_id", "created_at")),
    ("ix_bcs_messages_session_created", "bcs_messages", ("env", "session_id", "created_at")),
    (
        "ix_bcs_provider_credentials_lookup",
        "bcs_provider_credentials",
        ("env", "credential_kind", "secret_value"),
    ),
    (
        "ix_bcs_channel_bindings_account",
        "bcs_channel_bindings",
        ("channel_type", "account_ref", "status"),
    ),
    (
        "ix_bcs_channel_conversations_session",
        "bcs_channel_conversations",
        ("binding_id", "bcs_session_id"),
    ),
    (
        "ix_bcs_human_input_scope",
        "bcs_human_input_requests",
        ("reply_scope_key", "status", "deadline_ms"),
    ),
    (
        "ix_bcs_session_participants_bot",
        "bcs_session_participants",
        ("env", "group_id", "bot_uuid"),
    ),
    (
        "ix_bcs_session_participants_collected",
        "bcs_session_participants",
        ("env", "group_id", "bot_uuid", "collected", "collected_at"),
    ),
    (
        "ix_bcs_sm_delivery_node",
        "bcs_state_machine_delivery_correlations",
        ("env", "state_machine_run_id", "node_id", "attempt"),
    ),
    ("ix_bcs_sm_nodes_status", "bcs_state_machine_node_runs", ("env", "run_id", "status")),
    (
        "ix_bcs_sm_nodes_timeout",
        "bcs_state_machine_node_runs",
        ("env", "status", "timeout_deadline_ms"),
    ),
    ("ix_bcs_sm_runs_session", "bcs_state_machine_runs", ("env", "session_id")),
    (
        "ix_bcs_sm_runs_group_status",
        "bcs_state_machine_runs",
        ("env", "group_id", "status", "created_at_ms"),
    ),
    ("ix_bcs_user_identities_external", "bcs_user_identities", ("external_user_id", "env")),
    ("ix_bcs_organizations_provider", "bcs_organizations", ("env", "managing_provider_id")),
    ("ix_bcs_organization_members_bot", "bcs_organization_members", ("env", "bot_uuid")),
    ("ix_bcs_session_files_session", "bcs_session_files", ("env", "session_id", "gmt_create")),
)

_MODIFIED_TABLES: tuple[str, ...] = tuple(
    table_name
    for table_name in [
        "bcs_actor_relations",
        "bcs_bots",
        "bcs_collaboration_definitions",
        "bcs_collaboration_definition_blobs",
        "bcs_collaboration_events",
        "bcs_collaboration_templates",
        "bcs_collaboration_template_contents",
        "bcs_collaboration_template_tags",
        "bcs_friendships",
        "bcs_friend_requests",
        "bcs_groups",
        "bcs_group_participants",
        "bcs_group_runtime_bindings",
        "bcs_group_sessions",
        "bcs_messages",
        "bcs_providers",
        "bcs_provider_bot_bindings",
        "bcs_provider_credentials",
        "bcs_channel_bindings",
        "bcs_channel_conversations",
        "bcs_channel_im_participants",
        "bcs_human_input_requests",
        "bcs_session_participants",
        "bcs_state_machine_definition_snapshots",
        "bcs_state_machine_delivery_correlations",
        "bcs_state_machine_node_runs",
        "bcs_state_machine_runs",
        "bcs_user_identities",
        "bcs_organizations",
        "bcs_organization_members",
        "bcs_session_files",
    ]
)


def _execute_all(statements: Iterable[str]) -> None:
    for statement in statements:
        op.execute(sa.text(statement))


def upgrade() -> None:
    op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS avernet"))
    _execute_all(_TABLE_DDL)
    for name, table_name, columns in _INDEXES:
        op.create_index(name, table_name, list(columns), schema=SCHEMA)

    op.execute(
        sa.text(
            """
            CREATE FUNCTION avernet.touch_gmt_modified() RETURNS TRIGGER
            LANGUAGE plpgsql AS $$
            BEGIN
                NEW.gmt_modified = CURRENT_TIMESTAMP;
                RETURN NEW;
            END;
            $$
            """
        )
    )
    for table_name in _MODIFIED_TABLES:
        op.execute(
            sa.text(
                f"""
                CREATE TRIGGER trg_{table_name}_touch_gmt_modified
                BEFORE UPDATE ON avernet.{table_name}
                FOR EACH ROW EXECUTE FUNCTION avernet.touch_gmt_modified()
                """
            )
        )


def downgrade() -> None:
    op.execute(sa.text("DROP SCHEMA IF EXISTS avernet CASCADE"))
