"""add durable legacy cron admissions

Revision ID: b36acb66634d
Revises: 72847abc4b82
Create Date: 2026-09-07 21:27:17.687708

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b36acb66634d"
down_revision: str | Sequence[str] | None = "72847abc4b82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agistack_legacy_cron_admissions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scope_id", sa.String(length=100), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("owner_epoch", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("execution_phase", sa.String(length=20), nullable=False),
        sa.Column("execution_nonce", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("admitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(execution_phase IN ('ready', 'waiting') AND execution_nonce IS NULL) OR (execution_phase IN ('running', 'terminal') AND execution_nonce IS NOT NULL)",
            name="ck_legacy_cron_admission_nonce",
        ),
        sa.CheckConstraint(
            "(status = 'active' AND execution_phase <> 'terminal') OR (status IN ('success', 'failed') AND execution_phase = 'terminal')",
            name="ck_legacy_cron_admission_phase_status",
        ),
        sa.CheckConstraint(
            "(status = 'active' AND terminal_at IS NULL) OR (status IN ('success', 'failed') AND terminal_at IS NOT NULL)",
            name="ck_legacy_cron_admission_terminal",
        ),
        sa.CheckConstraint(
            "execution_phase IN ('ready', 'running', 'waiting', 'terminal')",
            name="ck_legacy_cron_admission_phase",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'success', 'failed')", name="ck_legacy_cron_admission_status"
        ),
        sa.CheckConstraint("owner_epoch >= 0", name="ck_legacy_cron_admission_epoch"),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["agistack_cron_scheduler_owners.scope_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(
        "ix_legacy_cron_admission_scope_status",
        "agistack_legacy_cron_admissions",
        ["scope_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Retain drain evidence until every legacy execution is terminal."""
    op.execute("LOCK TABLE agistack_legacy_cron_admissions IN ACCESS EXCLUSIVE MODE")
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM agistack_legacy_cron_admissions WHERE status = 'active') THEN
                RAISE EXCEPTION 'Cannot remove unresolved legacy cron admissions';
            END IF;
        END $$
    """)
    op.drop_index(
        "ix_legacy_cron_admission_scope_status", table_name="agistack_legacy_cron_admissions"
    )
    op.drop_table("agistack_legacy_cron_admissions")
