"""Add immutable HTTP schema mutation receipts

Revision ID: bfa08f458c13
Revises: 1a3218f58274
Create Date: 2026-09-08 19:36:33.269295

"""

from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa08f458c13"
down_revision: str | Sequence[str] | None = "1a3218f58274"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_schema_http_receipts",
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("schema_id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=False),
        sa.Column("change_id", sa.String(length=36), nullable=False),
        sa.Column("original_request_json", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "project_id", "schema_id", "actor_id", "change_id"],
            [
                "project_schema_receipts.tenant_id",
                "project_schema_receipts.project_id",
                "project_schema_receipts.schema_id",
                "project_schema_receipts.actor_id",
                "project_schema_receipts.change_id",
            ],
            name="fk_project_schema_http_receipt_command",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "project_id", "schema_id", "actor_id", "change_id"),
        sa.UniqueConstraint(
            "tenant_id",
            "project_id",
            "actor_id",
            "change_id",
            name="uq_project_schema_http_request",
        ),
    )
    # ### end Alembic commands ###
    directory = Path(__file__).resolve().parents[1] / "schema_http_mutation_v1"
    for name in ("materialize", "receipts"):
        for statement in (directory / f"{name}.sql").read_text().split("\n$$;"):
            if statement.strip():
                op.execute(statement + "\n$$;")
    op.execute(
        "CREATE TRIGGER project_schema_http_head_guard BEFORE INSERT OR UPDATE "
        "ON project_schema_heads FOR EACH ROW EXECUTE FUNCTION project_schema_guard_http_head()"
    )
    op.execute(
        "CREATE TRIGGER project_schema_http_receipt_guard BEFORE INSERT OR UPDATE OR DELETE "
        "ON project_schema_http_receipts FOR EACH ROW EXECUTE FUNCTION project_schema_guard_http_receipt()"
    )
    op.execute(
        "CREATE TRIGGER project_schema_http_truncate_guard BEFORE TRUNCATE "
        "ON project_schema_http_receipts FOR EACH STATEMENT EXECUTE FUNCTION project_schema_guard_truncate()"
    )
    for table in (
        "entity_types",
        "edge_types",
        "edge_type_maps",
        "project_schema_heads",
        "project_schema_http_receipts",
    ):
        op.execute(
            f"CREATE CONSTRAINT TRIGGER project_schema_http_commit_guard AFTER INSERT OR UPDATE OR DELETE "
            f"ON {table} DEFERRABLE INITIALLY DEFERRED FOR EACH ROW "
            "EXECUTE FUNCTION project_schema_check_http_commit()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Accepted HTTP receipts cannot be discarded to restore the old write adapter.
    bind = op.get_bind()
    if bind.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM project_schema_http_receipts) OR EXISTS "
            "(SELECT 1 FROM project_schema_receipts WHERE request_json::jsonb ? 'http_mutation')"
        )
    ).scalar_one():
        raise RuntimeError("project_schema_http_downgrade_has_accepted_history")
    for table in (
        "entity_types",
        "edge_types",
        "edge_type_maps",
        "project_schema_heads",
        "project_schema_http_receipts",
    ):
        op.execute(f"DROP TRIGGER project_schema_http_commit_guard ON {table}")
    op.execute("DROP TRIGGER project_schema_http_head_guard ON project_schema_heads")
    op.execute("DROP TRIGGER project_schema_http_receipt_guard ON project_schema_http_receipts")
    op.execute("DROP TRIGGER project_schema_http_truncate_guard ON project_schema_http_receipts")
    for function in (
        "project_schema_check_http_commit()",
        "project_schema_finalize_http(text,text,text,text,text)",
        "project_schema_guard_http_receipt()",
        "project_schema_http_response(text,text,text,text,text)",
        "project_schema_guard_http_head()",
        "project_schema_http_materialize(jsonb,jsonb,text)",
    ):
        op.execute(f"DROP FUNCTION {function}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_schema_http_receipts")
    # ### end Alembic commands ###
