"""Persist exact scope-private ProfileSource revisions.

Revision ID: c69d15e50ba3
Revises: b58c04d49a92

Generated against isolated PostgreSQL and reviewed as a single-table addition.
"""

import sqlalchemy as sa

from alembic import op

revision = "c69d15e50ba3"
down_revision = "b58c04d49a92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create immutable scoped ProfileSource revisions."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_plugin_v2_profile_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("profile_id", sa.String(length=255), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("digest", sa.String(length=71), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "scope_key",
            sa.String(length=64),
            server_default="0c7db1f10e1daaad62b5a58e3cd779dc19ded0fbdd5b44d760e95e9f0fdcb659",
            nullable=False,
        ),
        sa.Column("scope_kind", sa.String(length=16), server_default="root", nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=True),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "(scope_kind = 'root' AND tenant_id IS NULL AND project_id IS NULL AND session_id IS NULL) OR (scope_kind = 'tenant' AND tenant_id IS NOT NULL AND project_id IS NULL AND session_id IS NULL) OR (scope_kind = 'project' AND tenant_id IS NOT NULL AND project_id IS NOT NULL AND session_id IS NULL) OR (scope_kind = 'session' AND tenant_id IS NOT NULL AND project_id IS NOT NULL AND session_id IS NOT NULL)",
            name="ck_plugin_v2_profile_source_scope_shape",
        ),
        sa.CheckConstraint(
            "(tenant_id IS NULL OR length(trim(tenant_id)) > 0) AND (project_id IS NULL OR length(trim(project_id)) > 0) AND (session_id IS NULL OR length(trim(session_id)) > 0)",
            name="ck_plugin_v2_profile_source_scope_ids",
        ),
        sa.CheckConstraint("length(digest) = 71", name="ck_plugin_v2_source_digest"),
        sa.CheckConstraint("length(scope_key) = 64", name="ck_plugin_v2_profile_source_scope_key"),
        sa.CheckConstraint("revision > 0", name="ck_plugin_v2_source_revision"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scope_key", "source_id", "revision", name="uq_plugin_v2_source_revision"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove exact source storage."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_plugin_v2_profile_sources")
    # ### end Alembic commands ###
