"""Allow generation-catalog agent definitions to own bindings.

Revision ID: ce113f52d916
Revises: e83f7c901b52
Create Date: 2026-09-07 12:00:38.345381

Autogenerated against the current schema, then limited to the obsolete SQL-only
agent definition foreign key. Definition validity and tenant scope remain enforced
by AgentBindingServiceV2 through the active generation's definition resolver.
"""

from alembic import op

revision: str = "ce113f52d916"
down_revision: str | None = "e83f7c901b52"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Retire the SQL-only constraint without altering existing binding rows."""
    op.drop_constraint("agent_bindings_agent_id_fkey", "agent_bindings", type_="foreignkey")


def downgrade() -> None:
    """Restore SQL-only references; existing catalog-only bindings must be removed first."""
    op.create_foreign_key(
        "agent_bindings_agent_id_fkey",
        "agent_bindings",
        "agent_definitions",
        ["agent_id"],
        ["id"],
    )
