"""Persist exact scoped publication source bindings.

Revision ID: d72e6b8f0a41
Revises: c69d15e50ba3

Generated by Alembic against isolated PostgreSQL; reviewed single-table addition.
"""

import sqlalchemy as sa

from alembic import op

revision = "d72e6b8f0a41"
down_revision = "c69d15e50ba3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_plugin_v2_publication_sources",
        sa.Column("publication_id", sa.String(length=36), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "scope_key",
            sa.String(length=64),
            server_default="0c7db1f10e1daaad62b5a58e3cd779dc19ded0fbdd5b44d760e95e9f0fdcb659",
            nullable=False,
        ),
        sa.Column("scope_kind", sa.String(length=16), server_default="root", nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=True),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "(scope_kind = 'root' AND tenant_id IS NULL AND project_id IS NULL AND session_id IS NULL) OR (scope_kind = 'tenant' AND tenant_id IS NOT NULL AND project_id IS NULL AND session_id IS NULL) OR (scope_kind = 'project' AND tenant_id IS NOT NULL AND project_id IS NOT NULL AND session_id IS NULL) OR (scope_kind = 'session' AND tenant_id IS NOT NULL AND project_id IS NOT NULL AND session_id IS NOT NULL)",
            name="ck_plugin_v2_publication_source_scope_shape",
        ),
        sa.CheckConstraint(
            "(tenant_id IS NULL OR length(trim(tenant_id)) > 0) AND (project_id IS NULL OR length(trim(project_id)) > 0) AND (session_id IS NULL OR length(trim(session_id)) > 0)",
            name="ck_plugin_v2_publication_source_scope_ids",
        ),
        sa.CheckConstraint(
            "length(scope_key) = 64", name="ck_plugin_v2_publication_source_scope_key"
        ),
        sa.ForeignKeyConstraint(
            ["scope_key", "publication_id"],
            ["platform_plugin_v2_publications.scope_key", "platform_plugin_v2_publications.id"],
            name="fk_plugin_v2_publication_source_scope",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("publication_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_plugin_v2_publication_sources")
    # ### end Alembic commands ###
