"""Preserve actual outcomes before superseding blocked publication attempts.

Revision ID: e83f7c901b52
Revises: d72e6b8f0a41

Generated by Alembic against isolated PostgreSQL; reviewed single-table addition.
"""

import sqlalchemy as sa

from alembic import op

revision = "e83f7c901b52"
down_revision = "d72e6b8f0a41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_plugin_v2_outcome_supersessions",
        sa.Column("data_plane_id", sa.String(length=255), nullable=False),
        sa.Column("outcome_publication_id", sa.String(length=36), nullable=False),
        sa.Column("replacement_publication_id", sa.String(length=36), nullable=False),
        sa.Column("receipt_payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "scope_key",
            sa.String(length=64),
            server_default="0c7db1f10e1daaad62b5a58e3cd779dc19ded0fbdd5b44d760e95e9f0fdcb659",
            nullable=False,
        ),
        sa.Column("scope_kind", sa.String(length=16), server_default="root", nullable=False),
        sa.Column("tenant_id", sa.String(length=255), nullable=True),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "(scope_kind = 'root' AND tenant_id IS NULL AND project_id IS NULL AND session_id IS NULL) OR (scope_kind = 'tenant' AND tenant_id IS NOT NULL AND project_id IS NULL AND session_id IS NULL) OR (scope_kind = 'project' AND tenant_id IS NOT NULL AND project_id IS NOT NULL AND session_id IS NULL) OR (scope_kind = 'session' AND tenant_id IS NOT NULL AND project_id IS NOT NULL AND session_id IS NOT NULL)",
            name="ck_plugin_v2_outcome_supersession_scope_shape",
        ),
        sa.CheckConstraint(
            "(tenant_id IS NULL OR length(trim(tenant_id)) > 0) AND (project_id IS NULL OR length(trim(project_id)) > 0) AND (session_id IS NULL OR length(trim(session_id)) > 0)",
            name="ck_plugin_v2_outcome_supersession_scope_ids",
        ),
        sa.CheckConstraint(
            "length(scope_key) = 64", name="ck_plugin_v2_outcome_supersession_scope_key"
        ),
        sa.CheckConstraint(
            "length(trim(data_plane_id)) > 0", name="ck_plugin_v2_supersession_plane"
        ),
        sa.CheckConstraint(
            "outcome_publication_id <> replacement_publication_id",
            name="ck_plugin_v2_supersession_distinct",
        ),
        sa.ForeignKeyConstraint(
            ["scope_key", "outcome_publication_id"],
            ["platform_plugin_v2_publications.scope_key", "platform_plugin_v2_publications.id"],
            name="fk_plugin_v2_supersession_outcome",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scope_key", "replacement_publication_id"],
            ["platform_plugin_v2_publications.scope_key", "platform_plugin_v2_publications.id"],
            name="fk_plugin_v2_supersession_replacement",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "scope_key", "data_plane_id", "outcome_publication_id", "replacement_publication_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_plugin_v2_outcome_supersessions")
    # ### end Alembic commands ###
