"""add event_logs and webhooks tables

Revision ID: fa8dab0f9da1
Revises: 28a01da0cee6
Create Date: 2026-03-27 23:13:50.311537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa8dab0f9da1'
down_revision: Union[str, Sequence[str], None] = '28a01da0cee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_event_logs_created_at'), 'tenant_event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenant_event_logs_event_type'), 'tenant_event_logs', ['event_type'], unique=False)
    op.create_index('ix_tenant_event_logs_tenant_created', 'tenant_event_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhooks_tenant_name', 'webhooks', ['tenant_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhooks_tenant_name', table_name='webhooks', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('webhooks')
    op.drop_index('ix_tenant_event_logs_tenant_created', table_name='tenant_event_logs')
    op.drop_index(op.f('ix_tenant_event_logs_event_type'), table_name='tenant_event_logs')
    op.drop_index(op.f('ix_tenant_event_logs_created_at'), table_name='tenant_event_logs')
    op.drop_table('tenant_event_logs')
    # ### end Alembic commands ###
