//! Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.
use super::contracts::{ProcessingCommand, ProcessingQuery};
pub(super) const READ_ACTIONS: &[&str] = &[
    "cloud_conflict_context",
    "configuration",
    "entities",
    "get",
    "list",
    "pending_resolutions",
    "pull_conflict_context",
    "pull_conflicts",
    "push_conflicts",
    "reconciliation_context",
    "relationships",
    "remote_baseline",
    "resolution",
    "resolution_by_key",
    "resolution_history",
    "resolutions",
    "semantic",
    "sync_outbox",
    "sync_status",
    "text",
    "view",
];
pub(super) const WRITE_ACTIONS: &[&str] = &[
    "configure_embedding",
    "create",
    "delete",
    "index_one",
    "process_one",
    "promote_index",
    "reconcile_resolution",
    "resolve_pull",
    "resolve_push",
    "resume_resolution",
    "retry_index",
    "select_embedding",
    "sync_link",
    "sync_pull",
    "sync_push",
    "update",
];
impl ProcessingQuery {
    pub(super) fn capability_action(&self) -> &'static str {
        match self {
            Self::Configuration { .. } => "configuration",
            Self::Entities { .. } => "entities",
            Self::Relationships { .. } => "relationships",
            Self::Text { .. } => "text",
            Self::Semantic { .. } => "semantic",
        }
    }
}
impl ProcessingCommand {
    pub(super) fn capability_action(&self) -> &'static str {
        match self {
            Self::ConfigureEmbedding { .. } => "configure_embedding",
            Self::SelectEmbedding { .. } => "select_embedding",
            Self::IndexOne { .. } => "index_one",
            Self::PromoteIndex { .. } => "promote_index",
            Self::RetryIndex { .. } => "retry_index",
            Self::ProcessOne { .. } => "process_one",
        }
    }
}
