//! Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct KnowledgeOperationScopeV2 {
    pub(crate) tenant_id: String,
    pub(crate) project_id: String,
    pub(crate) context_revision: u64,
    pub(crate) profile_id: String,
    pub(crate) generation: u64,
    pub(crate) digest: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "operation", rename_all = "snake_case", deny_unknown_fields)]
pub(crate) enum ProcessingQuery {
    Configuration {},
    Entities {
        request: agistack_core::knowledge::retrieval::RetrievalRequest,
    },
    Relationships {
        request: agistack_core::knowledge::retrieval::RetrievalRequest,
    },
    Text {
        literal: String,
        request: agistack_core::knowledge::retrieval::RetrievalRequest,
    },
    Semantic {
        build_id: String,
        config_revision: u64,
        query: String,
        limit: usize,
    },
    FailedProcessing {
        request: agistack_core::knowledge::diagnostics::DiagnosticRequest,
    },
    FailedIndex {
        build_id: String,
        config_revision: u64,
        request: agistack_core::knowledge::diagnostics::DiagnosticRequest,
    },
    ProcessingAudits {
        source: agistack_core::knowledge::processing::ProcessingSource,
        request: agistack_core::knowledge::diagnostics::DiagnosticRequest,
    },
    ProcessingTask {
        source: agistack_core::knowledge::processing::ProcessingSource,
    },
    CommunityActive {},
    CommunityBuild {
        build_id: String,
        offset: u32,
        limit: u32,
    },
    CommunityAudit {
        build_id: String,
        candidate_id: String,
        attempt: u32,
    },
    CommunityBuilds {
        offset: u32,
        limit: u32,
    },
    GraphSource {
        source: agistack_core::knowledge::processing::ProcessingSource,
        expected_audit_attempt: u32,
    },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "operation", rename_all = "snake_case", deny_unknown_fields)]
pub(crate) enum ProcessingCommand {
    ConfigureEmbedding {
        build_id: String,
        provider_id: String,
        provider_revision: u64,
        model_id: String,
        #[serde(deserialize_with = "required_nullable")]
        expected_config_revision: Option<u64>,
    },
    SelectEmbedding {
        build_id: String,
        #[serde(deserialize_with = "required_nullable")]
        expected_config_revision: Option<u64>,
    },
    IndexOne {
        build_id: String,
        config_revision: u64,
    },
    PromoteIndex {
        build_id: String,
        config_revision: u64,
        #[serde(deserialize_with = "required_nullable")]
        expected_active_build_id: Option<String>,
    },
    RetryIndex {
        build_id: String,
        config_revision: u64,
        input: agistack_core::knowledge::index::IndexSource,
        expected_attempt: u32,
    },
    ProcessOne {
        workspace_id: String,
    },
    RetryProcessing {
        source: agistack_core::knowledge::processing::ProcessingSource,
        expected_attempt: u32,
    },
    CreateCommunityBuild {
        idempotency_key: String,
        min_community_size: usize,
    },
    SelectCommunityBuild {
        build_id: String,
        expected_selection_revision: u64,
    },
    ProcessCommunityOne {
        build_id: String,
        workspace_id: String,
    },
    RetryCommunity {
        build_id: String,
        candidate_id: String,
        expected_attempt: u32,
    },
    ActivateCommunityBuild {
        build_id: String,
        expected_selection_revision: u64,
    },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "operation", rename_all = "snake_case", deny_unknown_fields)]
pub(crate) enum KnowledgeQuery {
    Get { id: String },
    List { limit: usize, offset: usize },
    Changes { after_sequence: u64, limit: usize },
    Change { sequence: u64 },
    SyncStatus {},
    SyncOutbox { limit: usize, after_sequence: u64 },
    RemoteBaseline { id: String },
    PushConflicts { limit: usize },
    PullConflicts { limit: usize },
    PullConflictContext { id: String },
    ResolutionHistory { id: String, limit: usize },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "operation", rename_all = "snake_case", deny_unknown_fields)]
pub(crate) enum CloudQuery {
    ConflictContext {
        local_sequence: u64,
    },
    Resolution {
        resolution_id: String,
    },
    ResolutionByKey {
        idempotency_key: String,
    },
    PendingResolutions {
        before_resolution_id: Option<String>,
        limit: usize,
    },
    Resolutions {
        limit: usize,
    },
    ReconciliationContext {
        resolution_id: String,
    },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct QueryRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) query: KnowledgeQuery,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct MutationRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) mutation: agistack_core::knowledge::MemoryMutation,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncLinkRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) link: agistack_core::knowledge::sync::KnowledgeSyncLink,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct PushRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct PullRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ResolveRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) resolution:
        agistack_core::knowledge::sync::cloud_resolution::KnowledgeCloudResolutionCommand,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ResumeRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) resolution_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ReconcileRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) resolution_id: String,
    pub(crate) reconciliation:
        agistack_core::knowledge::sync::cloud_resolution::KnowledgeCloudReconciliationCommand,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct CloudQueryRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) query: CloudQuery,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ResolutionRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) resolution:
        agistack_core::knowledge::sync::resolution::KnowledgePullConflictResolution,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ProcessingQueryRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) query: ProcessingQuery,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct ProcessingCommandRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) command: ProcessingCommand,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncCloudGenerationDescriptor {
    pub(crate) profile_id: String,
    pub(crate) generation: u64,
    pub(crate) digest: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncCloudGeneration {
    pub(crate) contract_version: String,
    pub(crate) descriptor: SyncCloudGenerationDescriptor,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncCloudConnectionProjection {
    pub(crate) connection_revision: String,
    pub(crate) authority: String,
    pub(crate) actor_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncCloudTenant {
    pub(crate) id: String,
    pub(crate) name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncCloudProject {
    pub(crate) id: String,
    pub(crate) tenant_id: String,
    pub(crate) name: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncCloudEnrollment {
    pub(crate) contract_version: String,
    pub(crate) tenant_id: String,
    pub(crate) project_id: String,
    pub(crate) actor_id: String,
    pub(crate) enabled: bool,
    pub(crate) can_enroll: bool,
    pub(crate) bootstrap_count: u64,
    pub(crate) next_cursor: u64,
    pub(crate) replayed: bool,
    pub(crate) generation: SyncCloudGeneration,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncConnectionRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncTenantsRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) expected_connection_revision: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncProjectsRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) expected_connection_revision: String,
    pub(crate) tenant_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncEnrollmentRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) expected_connection_revision: String,
    pub(crate) tenant_id: String,
    pub(crate) project_id: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SyncTargetRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) expected_connection_revision: String,
    pub(crate) tenant_id: String,
    pub(crate) project_id: String,
    pub(crate) expected_generation: SyncCloudGeneration,
}

fn required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Deserialize<'de>,
{
    Option::<T>::deserialize(deserializer)
}
