//! Generated by scripts/generate_native_project_schema_contract.py; edit canonical contracts.
use crate::local_runtime::knowledge_authority_v2::KnowledgeOperationScopeV2;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SchemaReadRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
}
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SchemaBootstrapRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) change_id: String,
    pub(crate) expected_revision: u32,
    pub(crate) document: Box<serde_json::value::RawValue>,
}
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SchemaReplaceRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) change_id: String,
    pub(crate) expected_revision: u32,
    pub(crate) document: Box<serde_json::value::RawValue>,
}
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SchemaReceiptRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) change_id: String,
}
#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct SchemaHistoryRequest {
    pub(crate) scope: KnowledgeOperationScopeV2,
    pub(crate) after_revision: u32,
    pub(crate) limit: u32,
}
