//! Generated by scripts/generate_native_project_schema_contract.py; edit canonical contracts.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum SchemaAction {
    Read,
    Bootstrap,
    Replace,
    Receipt,
    History,
}
impl SchemaAction {
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            Self::Read => "schema_read",
            Self::Bootstrap => "schema_bootstrap",
            Self::Replace => "schema_replace",
            Self::Receipt => "schema_receipt",
            Self::History => "schema_history",
        }
    }
    pub(crate) fn path(self) -> &'static str {
        match self {
            Self::Read => "/api/v1/knowledge/schema/read",
            Self::Bootstrap => "/api/v1/knowledge/schema/bootstrap",
            Self::Replace => "/api/v1/knowledge/schema/replace",
            Self::Receipt => "/api/v1/knowledge/schema/receipt",
            Self::History => "/api/v1/knowledge/schema/history",
        }
    }
    #[cfg(test)]
    pub(crate) fn method(self) -> &'static str {
        match self {
            Self::Read => "POST",
            Self::Bootstrap => "POST",
            Self::Replace => "POST",
            Self::Receipt => "POST",
            Self::History => "POST",
        }
    }
    pub(crate) fn is_write(self) -> bool {
        matches!(self, Self::Bootstrap | Self::Replace)
    }
}
pub(crate) const SCHEMA_ACTIONS: &[SchemaAction] = &[
    SchemaAction::Read,
    SchemaAction::Bootstrap,
    SchemaAction::Replace,
    SchemaAction::Receipt,
    SchemaAction::History,
];
pub(crate) const MAX_REQUEST_BYTES: usize = 2097152;
pub(crate) const MAX_RESPONSE_BYTES: usize = 2097152;
pub(crate) const MAX_DOCUMENT_BYTES: usize = 1048576;
