"""Autogenerated HTTP-receipt migration on the dedicated schema QA database."""

from __future__ import annotations

import importlib.util
from contextlib import asynccontextmanager
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext

from src.domain.model.project_schema.http_mutations import SchemaHttpMutation, SchemaHttpOperation
from src.tests.integration.project_schema_command_support import SCOPE
from src.tests.integration.test_project_schema_m0 import (
    live_schema_pg as _live_schema_pg,
    schema_command_pg as _schema_command_pg,
    schema_host as _schema_host,
    schema_storage_pg as _schema_storage_pg,
)

schema_storage_pg = _schema_storage_pg
schema_command_pg = _schema_command_pg
live_schema_pg = _live_schema_pg
schema_host = _schema_host


def http_revision(connection, direction):
    path = (
        Path(__file__).resolve().parents[3]
        / "alembic/versions/bfa08f458c13_add_immutable_http_schema_mutation_.py"
    )
    spec = importlib.util.spec_from_file_location("schema_http_migration", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    with Operations.context(MigrationContext.configure(connection)):
        getattr(module, direction)()


@pytest.fixture
async def schema_http_pg(live_schema_pg):
    engine, sessions = live_schema_pg
    async with engine.begin() as connection:
        await connection.run_sync(http_revision, "upgrade")
    yield engine, sessions


def mutation(operation, *, target=None, fields=None, expected="1", change=None, scope=SCOPE):
    return SchemaHttpMutation.from_fields(
        scope=scope,
        operation=SchemaHttpOperation(operation),
        target_id=target,
        fields=fields or {},
        expected_revision=expected,
        change_id=change or str(uuid4()),
    )


@asynccontextmanager
async def http_client(host, sessions):
    from types import SimpleNamespace

    from fastapi import FastAPI
    from httpx import ASGITransport, AsyncClient

    from src.infrastructure.adapters.primary.web.dependencies import get_current_user
    from src.infrastructure.adapters.primary.web.routers import schema
    from src.infrastructure.adapters.secondary.persistence.database import get_db
    from src.infrastructure.plugins.v2.boundary import pin_generation_v2

    app = FastAPI()
    app.include_router(schema.router)
    app.dependency_overrides[get_current_user] = lambda: SimpleNamespace(id="owner")

    async def session_dependency():
        async with sessions() as db:
            yield db

    app.dependency_overrides[get_db] = session_dependency
    async with (
        pin_generation_v2(host),
        AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client,
    ):
        yield client


def headers(revision=1, change_id=None):
    return {
        "X-Project-Schema-Expected-Revision": str(revision),
        "X-Project-Schema-Change-Id": change_id or str(uuid4()),
    }
