"""Frozen source column groups and reusable projection SQL."""

from __future__ import annotations

WORKSPACE_SOURCE_COLUMNS = (
    "id",
    "tenant_id",
    "project_id",
    "name",
    "description",
    "created_by",
    "is_archived",
    "metadata_json",
    "office_status",
    "hex_layout_config_json",
    "default_blocking_categories_json",
    "created_at",
    "updated_at",
)
TASK_SOURCE_COLUMNS = (
    "id",
    "workspace_id",
    "title",
    "description",
    "created_by",
    "assignee_user_id",
    "assignee_agent_id",
    "status",
    "priority",
    "estimated_effort",
    "blocker_reason",
    "metadata_json",
    "created_at",
    "updated_at",
    "completed_at",
    "archived_at",
)
ATTEMPT_SOURCE_COLUMNS = (
    "id",
    "workspace_task_id",
    "root_goal_task_id",
    "workspace_id",
    "attempt_number",
    "status",
    "conversation_id",
    "worker_agent_id",
    "leader_agent_id",
    "candidate_summary",
    "candidate_artifacts_json",
    "candidate_verifications_json",
    "leader_feedback",
    "adjudication_reason",
    "created_at",
    "updated_at",
    "completed_at",
)
TOPOLOGY_NODE_SOURCE_COLUMNS = (
    "id",
    "workspace_id",
    "node_type",
    "ref_id",
    "title",
    "position_x",
    "position_y",
    "hex_q",
    "hex_r",
    "status",
    "tags_json",
    "data_json",
    "created_at",
    "updated_at",
)
TOPOLOGY_EDGE_SOURCE_COLUMNS = (
    "id",
    "workspace_id",
    "source_node_id",
    "target_node_id",
    "label",
    "source_hex_q",
    "source_hex_r",
    "target_hex_q",
    "target_hex_r",
    "direction",
    "auto_created",
    "data_json",
    "created_at",
    "updated_at",
)
MESSAGE_SOURCE_COLUMNS = (
    "id",
    "workspace_id",
    "sender_id",
    "sender_type",
    "content",
    "mentions_json",
    "parent_message_id",
    "metadata_json",
    "created_at",
)
AUTHORITY_SOURCE_COLUMNS = (
    "workspace_id",
    "tenant_id",
    "project_id",
    "revision",
    "created_at",
    "updated_at",
)
PIPELINE_CONTRACT_SOURCE_COLUMNS = (
    "id",
    "workspace_id",
    "plan_id",
    "provider",
    "code_root",
    "commands_json",
    "env_json",
    "trigger_policy_json",
    "timeout_seconds",
    "auto_deploy",
    "preview_port",
    "health_url",
    "status",
    "metadata_json",
    "created_at",
    "updated_at",
)
PIPELINE_CONTRACT_JSON_COLUMNS = {
    "commands_json",
    "env_json",
    "trigger_policy_json",
    "metadata_json",
}
PIPELINE_RUN_SOURCE_COLUMNS = (
    "id",
    "contract_id",
    "workspace_id",
    "plan_id",
    "node_id",
    "attempt_id",
    "commit_ref",
    "provider",
    "status",
    "reason",
    "started_at",
    "completed_at",
    "metadata_json",
    "created_at",
    "updated_at",
)
PIPELINE_STAGE_SOURCE_COLUMNS = (
    "id",
    "run_id",
    "workspace_id",
    "stage",
    "status",
    "command",
    "exit_code",
    "stdout_preview",
    "stderr_preview",
    "log_ref",
    "artifact_refs_json",
    "started_at",
    "completed_at",
    "duration_ms",
    "metadata_json",
    "created_at",
    "updated_at",
)
DEPLOYMENT_SOURCE_COLUMNS = (
    "id",
    "workspace_id",
    "plan_id",
    "node_id",
    "pipeline_run_id",
    "provider",
    "status",
    "command",
    "pid",
    "process_group_id",
    "port",
    "service_id",
    "service_name",
    "service_url",
    "ws_preview_url",
    "required",
    "preview_url",
    "health_url",
    "restart_count",
    "last_healthy_at",
    "rollback_ref",
    "log_ref",
    "metadata_json",
    "created_at",
    "updated_at",
)

_WORKSPACE_SQL = "SELECT w.*, w.tenant_id AS _tenant_id, w.project_id AS _project_id, w.id AS _workspace_id FROM workspaces w"
_MEMBER_SQL = "SELECT m.*, w.tenant_id AS _tenant_id, w.project_id AS _project_id, w.id AS _workspace_id, u.created_at AS actor_created_at, u.updated_at AS actor_updated_at FROM workspace_members m JOIN workspaces w ON w.id = m.workspace_id JOIN users u ON u.id = m.user_id"
_PRINCIPAL_IDENTITY_SQL = "SELECT m.id, m.workspace_id, m.user_id, w.tenant_id AS _tenant_id, w.project_id AS _project_id, w.id AS _workspace_id, u.email, u.full_name, u.is_active, u.created_at AS user_created_at, u.updated_at AS user_updated_at FROM workspace_members m JOIN workspaces w ON w.id = m.workspace_id JOIN users u ON u.id = m.user_id"
_AGENT_SQL = "SELECT a.*, w.tenant_id AS _tenant_id, w.project_id AS _project_id, w.id AS _workspace_id, w.created_by AS workspace_created_by, d.name AS agent_name FROM workspace_agents a JOIN workspaces w ON w.id = a.workspace_id LEFT JOIN agent_definitions d ON d.id = a.agent_id"
