#!/usr/bin/env python3
"""Generate native knowledge request DTOs and client views from one JSON Schema."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any, cast

if __package__:
    from .native_knowledge_capability_catalog import render_capability_catalog
    from .native_knowledge_runtime_schema import render_connection_schema, render_processing_schema
else:
    from native_knowledge_capability_catalog import render_capability_catalog
    from native_knowledge_runtime_schema import render_connection_schema, render_processing_schema

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "shared/schemas/knowledge/native-knowledge.v1.schema.json"
RUST = ROOT / "agi-stack/apps/desktop/sidecar/src/local_runtime/knowledge_authority_v2/contracts.rs"
TYPESCRIPT = (
    ROOT / "agi-stack/apps/desktop/src/features/project-knowledge/nativeKnowledgeGenerated.ts"
)
Node = dict[str, Any]


def ts_type(node: Node, depth: int = 0) -> str:
    """Render only the declared schema subset, rejecting unsupported constructs."""
    if "$ref" in node:
        return str(node["$ref"]).rsplit("/", 1)[1]
    if "const" in node:
        return json.dumps(node["const"], ensure_ascii=False)
    if "enum" in node:
        return " | ".join(json.dumps(item) for item in node["enum"])
    for keyword, joiner in [("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")]:
        if keyword in node:
            return joiner.join(f"({ts_type(item, depth)})" for item in node[keyword])
    return ts_shape(node, depth)


def ts_shape(node: Node, depth: int) -> str:
    kind = node.get("type")
    if kind in {"null", "string", "boolean", "number", "integer"}:
        return "number" if kind == "integer" else str(kind)
    if kind == "array":
        return f"readonly ({ts_type(node['items'], depth)})[]"
    if kind == "object":
        return ts_object(node, depth)
    raise ValueError(f"unsupported TypeScript schema: {node}")


def ts_object(node: Node, depth: int) -> str:
    lines: list[str] = []
    if isinstance(node.get("additionalProperties"), dict):
        lines.append(f"readonly [key: string]: {ts_type(node['additionalProperties'], depth + 1)};")
    for name, value in node.get("properties", {}).items():
        optional = "" if name in node.get("required", []) else "?"
        lines.append(f"readonly {name}{optional}: {ts_type(value, depth + 1)};")
    if not lines:
        return "Readonly<Record<never, never>>"
    padding = "  " * (depth + 1)
    return "{\n" + "\n".join(padding + line for line in lines) + "\n" + "  " * depth + "}"


def rust_type(node: Node, definitions: Node) -> str:
    if "x-rust-type" in node:
        return str(node["x-rust-type"])
    if "$ref" in node:
        target = definitions[str(node["$ref"]).rsplit("/", 1)[1]]
        if "x-rust-name" in target:
            return str(target["x-rust-name"])
        return rust_type(target, definitions)
    if "anyOf" in node:
        values = [item for item in node["anyOf"] if item.get("type") != "null"]
        if len(values) == 1 and len(node["anyOf"]) == 2:
            return f"Option<{rust_type(values[0], definitions)}>"
    if node.get("type") == "array":
        return f"Vec<{rust_type(node['items'], definitions)}>"
    primitive = {"string": "String", "integer": "u64", "number": "f64", "boolean": "bool"}
    if node.get("type") in primitive:
        return primitive[node["type"]]
    raise ValueError(f"unsupported Rust schema: {node}")


def rust_fields(node: Node, definitions: Node, padding: str, public: bool) -> list[str]:
    result: list[str] = []
    for name, value in node.get("properties", {}).items():
        if name == node.get("x-rust-tag"):
            continue
        kind = rust_type(value, definitions)
        if name not in node.get("required", []) and not kind.startswith("Option<"):
            kind = f"Option<{kind}>"
        if name in node.get("required", []) and kind.startswith("Option<"):
            result.append(f'{padding}#[serde(deserialize_with = "required_nullable")]')
        result.append(f"{padding}{'pub(crate) ' if public else ''}{name}: {kind},")
    return result


def render_rust(definitions: Node) -> str:
    lines = [
        "//! Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.",
        "use serde::{Deserialize, Serialize};",
        "",
    ]
    for node in definitions.values():
        name = node.get("x-rust-name")
        if not name:
            continue
        lines.append("#[derive(Clone, Debug, Deserialize, Serialize)]")
        if "x-rust-tag" in node:
            tag = node["x-rust-tag"]
            lines.append(f'#[serde(tag = "{tag}", rename_all = "snake_case", deny_unknown_fields)]')
            lines.append(f"pub(crate) enum {name} {{")
            for variant in node["oneOf"]:
                value = variant["properties"][tag]["const"]
                variant_name = "".join(part.capitalize() for part in value.split("_"))
                lines.append(f"    {variant_name} {{")
                lines.extend(
                    rust_fields({**variant, "x-rust-tag": tag}, definitions, "        ", False)
                )
                lines.append("    },")
            lines.append("}")
        else:
            lines.extend(["#[serde(deny_unknown_fields)]", f"pub(crate) struct {name} {{"])
            lines.extend(rust_fields(node, definitions, "    ", True))
            lines.append("}")
        lines.append("")
    lines.extend(
        [
            "fn required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>",
            "where D: serde::Deserializer<'de>, T: Deserialize<'de>,",
            "{ Option::<T>::deserialize(deserializer) }",
        ]
    )
    return subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        input="\n".join(lines),
        text=True,
        check=True,
        capture_output=True,
    ).stdout


def render_typescript(definitions: Node, imports: list[str] | None = None) -> str:
    lines = ["// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema."]
    if imports:
        lines.append(
            "import type { " + ", ".join(imports) + " } from './nativeKnowledgeDataGenerated';"
        )
    for name, node in definitions.items():
        lines.extend(["", "// prettier-ignore", f"export type {name} = {ts_type(node)};"])
    return "\n".join(lines) + "\n"


def load_definitions() -> Node:
    schema = json.loads(SCHEMA.read_text())
    result = {}
    for name, node in schema["$defs"].items():
        document, pointer = node["$ref"].split("#", 1)
        data = json.loads((SCHEMA.parent / document).read_text())
        result[name] = data["$defs"][pointer.rsplit("/", 1)[1]]
    # Internal renderers consume normalized local references; the schema itself
    # retains resolvable external references for ordinary JSON Schema validators.
    return json.loads(
        json.dumps(result).replace("native-knowledge.v1.schema.json#/$defs/", "#/$defs/")
    )


def referenced_names(node: Node) -> set[str]:
    names: set[str] = set()
    if "$ref" in node:
        names.add(str(node["$ref"]).rsplit("/", 1)[1])
    for value in node.values():
        if isinstance(value, dict):
            names.update(referenced_names(cast("Node", value)))
        elif isinstance(value, list):
            for item in cast("list[Any]", value):
                if isinstance(item, dict):
                    names.update(referenced_names(cast("Node", item)))
    return names


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    definitions = load_definitions()
    rpc = {
        name: node
        for name, node in definitions.items()
        if name.endswith(("Map", "Query", "Request", "Command", "Mutation", "Envelope", "Response"))
    }
    data = {name: node for name, node in definitions.items() if name not in rpc}
    imports = sorted(
        set[str]().union(*(referenced_names(node) for node in rpc.values())) & data.keys()
    )
    capability_rust, capability_ts = render_capability_catalog(
        json.loads(SCHEMA.read_text()), definitions
    )
    outputs = {
        RUST.with_name("capabilities_generated.rs"): capability_rust,
        TYPESCRIPT.with_name("nativeKnowledgeCapabilityActionsGenerated.ts"): capability_ts,
        RUST: render_rust(definitions),
        TYPESCRIPT.with_name(
            "nativeKnowledgeConnectionSchemaGenerated.ts"
        ): render_connection_schema(definitions),
        TYPESCRIPT.with_name(
            "nativeKnowledgeProcessingSchemaGenerated.ts"
        ): render_processing_schema(definitions),
        TYPESCRIPT: "\n".join(
            [
                "// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.",
                "export type * from './nativeKnowledgeDataGenerated';",
                "export type * from './nativeKnowledgeRpcGenerated';",
                "",
            ]
        ),
        TYPESCRIPT.with_name("nativeKnowledgeDataGenerated.ts"): render_typescript(data),
        TYPESCRIPT.with_name("nativeKnowledgeRpcGenerated.ts"): render_typescript(rpc, imports),
    }
    stale: list[str] = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            _ = path.write_text(content)
    if stale:
        parser.exit(1, "stale native knowledge DTOs: " + ", ".join(stale) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
