#!/usr/bin/env python3
"""Generate native schema DTOs/actions/types from canonical local contracts only."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "contracts/project-schema-v1/native-rpc.schema.json"
DOCUMENT = SOURCE.with_name("document.schema.json")
SCOPE = ROOT / "shared/schemas/knowledge/native-knowledge-definitions-1.v1.schema.json"
RUST = ROOT / "agi-stack/apps/desktop/sidecar/src/local_runtime/knowledge_authority_v2"
TS = ROOT / "agi-stack/apps/desktop/src/features/project-administration"
Node = dict[str, Any]
SCOPE_REF = "../../shared/schemas/knowledge/native-knowledge-definitions-1.v1.schema.json#/$defs/NativeKnowledgeScope"


def canonical_definitions(source: Node, document: Node) -> Node:
    """Resolve only these three repository-owned contracts, never remote schemas."""
    names = {name: "PortableSchema" + name[0].upper() + name[1:] for name in document["$defs"]}

    def remap(value: object, portable: bool = False) -> object:
        if isinstance(value, list):
            return [remap(item, portable) for item in cast("list[object]", value)]
        if not isinstance(value, dict):
            return value
        result = {
            key: remap(item, portable)
            for key, item in cast("dict[str, object]", value).items()
            if key not in {"$schema", "$id", "$defs", "title", "$comment", "x-rust-name"}
        }
        reference = result.get("$ref")
        if reference == SCOPE_REF:
            return json.loads(SCOPE.read_text())["$defs"]["NativeKnowledgeScope"] | {
                "x-rust-type": "KnowledgeOperationScopeV2"
            }
        if reference == "document.schema.json":
            return cast("Node", remap(document, True)) | {
                key: item for key, item in result.items() if key != "$ref"
            }
        if (
            isinstance(reference, str) and reference.startswith("document.schema.json#/$defs/")
        ) or (isinstance(reference, str) and portable and reference.startswith("#/$defs/")):
            result["$ref"] = "#/$defs/" + names[reference.rsplit("/", 1)[1]]
        elif isinstance(reference, str) and not reference.startswith("#/$defs/"):
            raise ValueError(f"unapproved schema reference: {reference}")
        return result

    result = {name: cast("Node", remap(node)) for name, node in source["$defs"].items()}
    result.update(
        {names[name]: cast("Node", remap(node, True)) for name, node in document["$defs"].items()}
    )
    for name, node in source["$defs"].items():
        if "x-rust-name" in node:
            result[name]["x-rust-name"] = node["x-rust-name"]
    return result


def ts_type(node: Node) -> str:  # noqa: PLR0911 - closed JSON Schema shape cases
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    for union in ["anyOf", "oneOf"]:
        if union in node:
            return " | ".join(f"({ts_type(item)})" for item in node[union])
    kind = node.get("type")
    if kind == "array":
        return f"readonly ({ts_type(node['items'])})[]"
    if kind == "object":
        fields = [
            f"readonly {name}{'' if name in node.get('required', []) else '?'}: {ts_type(field)};"
            for name, field in node.get("properties", {}).items()
        ]
        if isinstance(node.get("additionalProperties"), dict):
            fields.append(f"readonly [key: string]: {ts_type(node['additionalProperties'])};")
        return "{\n  " + "\n  ".join(fields) + "\n}"
    if kind in {"integer", "number", "string", "boolean", "null"}:
        return "number" if kind == "integer" else kind
    raise ValueError(f"unsupported TypeScript shape: {node}")


def rust_type(node: Node, definitions: Node) -> str:
    if "x-rust-type" in node:
        return node["x-rust-type"]
    if "$ref" in node:
        return rust_type(definitions[node["$ref"].rsplit("/", 1)[1]], definitions)
    if node.get("type") == "string":
        return "String"
    raise ValueError(f"unsupported request field: {node}")


def rustfmt(source: str) -> str:
    return subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        input=source,
        text=True,
        capture_output=True,
        check=True,
    ).stdout


def render(source: Node, document: Node) -> dict[Path, str]:
    definitions = canonical_definitions(source, document)
    banner = (
        "Generated by scripts/generate_native_project_schema_contract.py; edit canonical contracts."
    )
    rust = [
        f"//! {banner}",
        "use serde::{Deserialize, Serialize};",
        "use crate::local_runtime::knowledge_authority_v2::KnowledgeOperationScopeV2;",
    ]
    for node in definitions.values():
        if not node.get("x-rust-name", "").startswith("Schema"):
            continue
        rust.extend(
            [
                "#[derive(Clone, Debug, Deserialize, Serialize)]",
                "#[serde(deny_unknown_fields)]",
                f"pub(crate) struct {node['x-rust-name']} {{",
            ]
        )
        rust.extend(
            f"pub(crate) {name}: {rust_type(field, definitions)},"
            for name, field in node["properties"].items()
        )
        rust.append("}")
    actions = source["x-actions"]
    variants = {name: name.removeprefix("schema_").capitalize() for name in actions}
    action_rust = [
        f"//! {banner}",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]",
        "pub(crate) enum SchemaAction {" + ",".join(variants.values()) + "}",
        "impl SchemaAction {",
        "pub(crate) fn as_str(self) -> &'static str { match self {",
    ]
    action_rust.extend(f'Self::{variant} => "{name}",' for name, variant in variants.items())
    action_rust.extend(["} }", "pub(crate) fn path(self) -> &'static str { match self {"])
    action_rust.extend(
        f'Self::{variants[name]} => "{metadata["path"]}",' for name, metadata in actions.items()
    )
    action_rust.extend(
        ["} }", "#[cfg(test)]", "pub(crate) fn method(self) -> &'static str { match self {"]
    )
    action_rust.extend(
        f'Self::{variants[name]} => "{metadata["method"]}",' for name, metadata in actions.items()
    )
    action_rust.extend(
        [
            "} }",
            "pub(crate) fn is_write(self) -> bool { matches!(self, "
            + " | ".join(
                "Self::" + variants[name]
                for name, metadata in actions.items()
                if metadata["access"] == "write"
            )
            + ") }",
            "}",
            "pub(crate) const SCHEMA_ACTIONS: &[SchemaAction] = &["
            + ",".join("SchemaAction::" + variant for variant in variants.values())
            + "];",
        ]
    )
    constants = {
        "REQUEST_BYTES": source["x-maxRequestBytes"],
        "RESPONSE_BYTES": source["x-maxResponseBytes"],
        "DOCUMENT_BYTES": document["x-maxWireBytes"],
    }
    action_rust.extend(
        f"pub(crate) const MAX_{name}: usize = {value};" for name, value in constants.items()
    )
    types = [f"// {banner}"]
    types.extend(
        f"// prettier-ignore\nexport type {name} = {ts_type(node)};\n"
        for name, node in definitions.items()
    )
    types.append(
        "// prettier-ignore\nexport type NativeProjectSchemaAction = "
        + " | ".join(json.dumps(name) for name in actions)
        + ";"
    )
    types.append(
        "// prettier-ignore\nexport type NativeProjectSchemaResponseMap = {"
        + "".join(f"readonly {name}: {metadata['response']};" for name, metadata in actions.items())
        + "};"
    )
    types.append(
        "// prettier-ignore\nexport type NativeProjectSchemaRequestMap = {"
        + "".join(f"readonly {name}: {metadata['request']};" for name, metadata in actions.items())
        + "};"
    )
    runtime = [
        f"// {banner}",
        "// References are local and closed; opaque user schemas are never evaluated as validators.",
        "// prettier-ignore",
        "export const NATIVE_PROJECT_SCHEMA_DEFINITIONS = "
        + json.dumps(definitions, separators=(",", ":"))
        + " as const;",
        "// prettier-ignore",
        "export const NATIVE_PROJECT_SCHEMA_ACTIONS = "
        + json.dumps(actions, separators=(",", ":"))
        + " as const;",
    ]
    runtime.append(
        "// prettier-ignore\nexport const NATIVE_PROJECT_SCHEMA_CAPABILITIES = "
        + json.dumps(source["x-capabilities"], separators=(",", ":"))
        + " as const;"
    )
    runtime.extend(
        f"export const MAX_SCHEMA_{name} = {value};" for name, value in constants.items()
    )
    return {
        RUST / "project_schema_contracts.rs": rustfmt("\n".join(rust)),
        RUST / "project_schema_actions_generated.rs": rustfmt("\n".join(action_rust)),
        TS / "nativeProjectSchemaGenerated.ts": "\n".join(types) + "\n",
        TS / "nativeProjectSchemaSchemaGenerated.ts": "\n".join(runtime) + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = render(json.loads(SOURCE.read_text()), json.loads(DOCUMENT.read_text()))
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(
                    f"stale generated native schema contract: {path.relative_to(ROOT)}"
                )
        else:
            _ = path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
