"""Render the processing schema as runtime checks without a second contract."""

from __future__ import annotations

import json
from typing import Any

Node = dict[str, Any]
ROOT_NAMES = (
    "NativeKnowledgeScope",
    "NativeKnowledgeProcessingQuery",
    "NativeKnowledgeProcessingCommand",
    "NativeKnowledgeProcessingResultMap",
    "NativeKnowledgeProcessingCommandResultMap",
)
SUPPORTED = frozenset(
    {
        "$ref",
        "const",
        "enum",
        "anyOf",
        "oneOf",
        "type",
        "minimum",
        "maximum",
        "items",
        "additionalProperties",
        "properties",
        "required",
        "x-rust-name",
        "x-rust-tag",
        "x-rust-type",
    }
)


def runtime_check(node: Node, pending: list[str]) -> str:
    """Fail on unhandled schema constraints instead of silently weakening checks."""
    if node.keys() - SUPPORTED:
        raise ValueError(f"unsupported processing schema keywords: {node.keys() - SUPPORTED}")
    if "$ref" in node:
        name = str(node["$ref"]).rsplit("/", 1)[1]
        pending.append(name)
        return f"(value) => definitions.{name}!(value)"
    if "const" in node:
        return "s.literal(" + json.dumps(node["const"]) + ")"
    if "enum" in node:
        return "s.literal(" + ", ".join(map(json.dumps, node["enum"])) + ")"
    for keyword, test in [("anyOf", "> 0"), ("oneOf", "=== 1")]:
        if keyword in node:
            choices = ", ".join(runtime_check(item, pending) for item in node[keyword])
            return f"(value) => ([{choices}] as s.NativeCheck[]).filter((test) => test(value)).length {test}"
    return runtime_shape(node, pending)


def runtime_shape(node: Node, pending: list[str]) -> str:
    kind = node.get("type")
    if kind == "integer":
        return f"s.integer({node.get('minimum', 0)}, {node.get('maximum', 9007199254740991)})"
    if kind == "number":
        bounds = [
            f"value {operator} {node[key]}"
            for key, operator in [("minimum", ">="), ("maximum", "<=")]
            if key in node
        ]
        return "(value) => typeof value === 'number' && Number.isFinite(value)" + (
            " && " + " && ".join(bounds) if bounds else ""
        )
    if kind in {"null", "string", "boolean"}:
        return {"null": "s.literal(null)", "string": "s.text", "boolean": "s.bool"}[kind]
    if kind == "array":
        return f"s.array({runtime_check(node['items'], pending)})"
    if kind == "object":
        return runtime_object(node, pending)
    raise ValueError(f"unsupported processing runtime schema: {node}")


def runtime_object(node: Node, pending: list[str]) -> str:
    if node.get("additionalProperties") is not False:
        raise ValueError("processing wire objects must reject unknown fields")
    fields: list[list[str]] = [[], []]
    for name, field in node.get("properties", {}).items():
        fields[0 if name in node.get("required", []) else 1].append(
            f"{json.dumps(name)}: {runtime_check(field, pending)}"
        )
    return "s.object({" + ", ".join(fields[0]) + "}, {" + ", ".join(fields[1]) + "})"


def render_processing_schema(definitions: Node) -> str:
    """Resolve the reachable schema closure and generate exact structural checks."""
    pending: list[str] = list(ROOT_NAMES)
    rendered: dict[str, str] = {}
    while pending:
        name = pending.pop(0)
        if name not in rendered:
            rendered[name] = runtime_check(definitions[name], pending)
    lines = [
        "// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.",
        "import * as s from './nativeKnowledgeSchema';",
        "// prettier-ignore",
        "export const definitions: Readonly<Record<string, s.NativeCheck>> = Object.freeze({",
        *(f"  {name}: {value}," for name, value in rendered.items()),
        "});",
    ]
    for export, name in [
        ("processingResults", "NativeKnowledgeProcessingResultMap"),
        ("processingCommandResults", "NativeKnowledgeProcessingCommandResultMap"),
    ]:
        lines.extend(
            [
                "// prettier-ignore",
                f"export const {export}: Readonly<Record<string, s.NativeCheck>> = Object.freeze({{",
                *(
                    f"  {name}: {runtime_check(node, pending)},"
                    for name, node in definitions[name]["properties"].items()
                ),
                "});",
            ]
        )
    return "\n".join(lines) + "\n"
