"""Generate explicit native action metadata shared by publication and admission."""

from __future__ import annotations

import json
import subprocess
from typing import Any


def render_capability_catalog(
    schema: dict[str, Any], definitions: dict[str, Any]
) -> tuple[str, str]:
    actions: dict[str, str] = schema["x-capability-actions"]
    required = {"view", "list"}
    for name in [
        "NativeKnowledgeRequestMap",
        "NativeKnowledgeProcessingQueryMap",
        "NativeKnowledgeProcessingCommandMap",
    ]:
        required.update(definitions[name]["properties"])
    if required != actions.keys() or set(actions.values()) != {"read", "write"}:
        raise ValueError("capability actions must exactly cover the native operation contract")
    local = schema["x-local-acceptance-actions"]
    if len(set(local)) != len(local) or not set(local) <= actions.keys():
        raise ValueError("local acceptance actions must be unique declared operations")
    reads = sorted(name for name, access in actions.items() if access == "read")
    writes = sorted(name for name, access in actions.items() if access == "write")
    rust = [
        "//! Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.",
        "use super::contracts::{ProcessingQuery, ProcessingCommand};",
        f"pub(super) const READ_ACTIONS: &[&str] = &{json.dumps(reads)};",
        f"pub(super) const WRITE_ACTIONS: &[&str] = &{json.dumps(writes)};",
        f"pub(super) const LOCAL_ACCEPTANCE_ACTIONS: &[&str] = &{json.dumps(sorted(local))};",
    ]
    for name, access in [
        ("NativeKnowledgeProcessingQuery", "read"),
        ("NativeKnowledgeProcessingCommand", "write"),
    ]:
        node = definitions[name]
        rust.extend(
            [
                f"impl {node['x-rust-name']} {{",
                "pub(super) fn capability_action(&self) -> &'static str { match self {",
            ]
        )
        for variant in node["oneOf"]:
            action = variant["properties"]["operation"]["const"]
            if actions[action] != access:
                raise ValueError("processing query/command access conflicts with its route")
            variant_name = "".join(part.capitalize() for part in action.split("_"))
            rust.append(f'Self::{variant_name} {{ .. }} => "{action}",')
        rust.append("} } }")
    rust_source = subprocess.run(
        ["rustfmt", "--edition", "2021", "--emit", "stdout"],
        input="\n".join(rust),
        text=True,
        check=True,
        capture_output=True,
    ).stdout
    ts = [
        "// Generated by scripts/generate_native_knowledge_contract.py; edit the JSON Schema.",
        "// prettier-ignore",
        f"export const NATIVE_KNOWLEDGE_READ_ACTIONS = Object.freeze({json.dumps(reads)} as const);",
        "// prettier-ignore",
        f"export const NATIVE_KNOWLEDGE_WRITE_ACTIONS = Object.freeze({json.dumps(writes)} as const);",
    ]
    return rust_source, "\n".join(ts) + "\n"
