import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { test } from 'node:test';
const require=createRequire(import.meta.url), ROOT='/tmp/agistack-desktop-test-dist';
const m=require(`${ROOT}/src/plugins/desktopInstanceTemplatesAuthorityModuleV2.js`);
const runtime=require('@agistack/plugin-runtime');
const config=(mode='cloud')=>({apiBaseUrl:'https://cloud.test',deviceAuthorizationBaseUrl:'https://cloud.test',apiKey:'x',localApiToken:'y',tenantId:'t1',projectId:'p1',workspaceId:'',workspaceRoot:'',mode});
const scope=(authority='cloud')=>({authority,tenantId:'t1'}), page=()=>({templates:[],total:0,page:1,pageSize:20});
function service(events,pending){return {bindOperation(c,s){events.push(['bind',c,s]);return {list:async(q,signal)=>{events.push(['list',q,signal]);return pending?pending():page();},get:async()=>({}),listItems:async()=>[],create:async()=>({}),delete:async()=>{},publish:async()=>({}),clone:async()=>({}),probe:async()=>({availability:'available',reasonCode:null,allowedActions:['view'],authorityRevision:null})};}};}
function actions(value,life=[],releaseError){return {async acquireServiceOperationLease(request){life.push(['acquire',request]);return {status:'accepted',digest:'d',useService:(fn)=>fn(value),async release(){life.push(['release']);if(releaseError)throw releaseError;}};}};}
test('catalog/config/service and all operations use tenant leases with frozen inputs',async()=>{const entry=runtime.PLUGIN_MODULE_CATALOG_V2.modules.find(x=>x.module_ref===m.DESKTOP_INSTANCE_TEMPLATES_AUTHORITY_MODULE_REF_V2);assert.equal(m.desktopInstanceTemplatesAuthorityDefinitionV2.contractDigest,entry.contract_digest);assert.throws(()=>m.applyDesktopInstanceTemplatesAuthorityV2({provide(){}},{strategy:'bad'}));const events=[],life=[],ops=m.createDesktopInstanceTemplatesOperationsV2(()=>actions(service(events),life));await ops.list({config:config(),scope:scope(),query:{page:1}});await ops.get({config:config(),scope:scope(),id:'x'});await ops.listItems({config:config(),scope:scope(),id:'x'});await ops.create({config:config(),scope:scope(),input:{name:'n',slug:'s',description:null,defaultConfig:{}}});await ops.delete({config:config(),scope:scope(),id:'x'});await ops.publish({config:config(),scope:scope(),id:'x'});await ops.clone({config:config(),scope:scope(),id:'x',newName:'copy'});await ops.probe({config:config(),scope:scope()});assert.equal(life.filter(x=>x[0]==='acquire').length,8);for(const [,r]of life.filter(x=>x[0]==='acquire'))assert.deepEqual(r.scope,{kind:'tenant',tenant_id:'t1'});});
test('Local probe is not applicable',async()=>{let provider;m.applyDesktopInstanceTemplatesAuthorityV2({provide(_k,v){provider=v;}},{strategy:'desktop-vault-broker'});assert.equal((await provider.bindOperation(config('local'),scope('local')).probe()).availability,'not_applicable');});
test('HMR pins old generation, revokes escaped authority, and preserves error precedence',async()=>{let finish,escaped;const old=[],next=[];let current=actions(service(old,()=>new Promise(r=>{finish=r;})));const ops=m.createDesktopInstanceTemplatesOperationsV2(()=>current),first=ops.list({config:config(),scope:scope()});while(!finish)await new Promise(r=>setImmediate(r));current=actions(service(next));finish(page());await first;await ops.list({config:config(),scope:scope()});await m.withDesktopInstanceTemplatesAuthorityOperationV2(actions(service([])),{config:config(),scope:scope()},async a=>{escaped=a;return page();});await assert.rejects(()=>escaped.list({}),e=>e.code==='desktop_instance_templates_operation_released');const primary=new Error('primary'),release=new Error('release');await assert.rejects(()=>m.withDesktopInstanceTemplatesAuthorityOperationV2(actions(service([],async()=>{throw primary;}),[],release),{config:config(),scope:scope()},a=>a.list({})),primary);await assert.rejects(()=>m.withDesktopInstanceTemplatesAuthorityOperationV2(actions(service([]),[],release),{config:config(),scope:scope()},a=>a.list({})),release);assert.throws(()=>m.createDesktopInstanceTemplatesOperationsV2(()=>null).probe({config:config(),scope:scope()}));});
