/**
 * FileDownloadButton component
 *
 * Renders a download button for files generated by CodeExecutorTool.
 * Files are accessed via S3 presigned URLs returned from the backend.
 */

import React from 'react';

import { DownloadOutlined, FileOutlined, FilePdfOutlined } from '@ant-design/icons';
import { Button, Tooltip } from 'antd';

interface FileDownloadButtonProps {
  /** The filename to display */
  filename: string;
  /** The presigned URL for download */
  url: string;
  /** Optional file size in bytes */
  size?: number;
}

const formatFileSize = (bytes?: number): string => {
  if (bytes === undefined) return '';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

const getFileIcon = (filename: string) => {
  const ext = filename.toLowerCase().split('.').pop();
  switch (ext) {
    case 'pdf':
      return <FilePdfOutlined />;
    default:
      return <FileOutlined />;
  }
};

export const FileDownloadButton: React.FC<FileDownloadButtonProps> = ({ filename, url, size }) => {
  const handleDownload = () => {
    // Open in new tab - browser will handle download based on Content-Disposition
    window.open(url, '_blank');
  };

  const sizeText = formatFileSize(size);
  const tooltipText = sizeText ? `Download ${filename} (${sizeText})` : `Download ${filename}`;

  return (
    <Tooltip title={tooltipText}>
      <Button
        type="primary"
        icon={<DownloadOutlined />}
        onClick={handleDownload}
        size="small"
        style={{ marginRight: 8, marginBottom: 4 }}
      >
        {getFileIcon(filename)} {filename}
      </Button>
    </Tooltip>
  );
};

export default FileDownloadButton;
