/**
 * WorkPlanCard component (T052)
 *
 * Displays the work-level plan generated by the agent,
 * showing all steps with their status and dependencies.
 *
 * PERFORMANCE: Wrapped with React.memo to prevent unnecessary re-renders.
 */

import React, { useState, memo } from "react";

import {
  CheckCircleOutlined,
  LoadingOutlined,
  CloseCircleOutlined,
  ClockCircleOutlined,
  CaretDownOutlined,
  CaretRightOutlined,
  ThunderboltOutlined,
} from "@ant-design/icons";
import {
  Card,
  Collapse,
  Progress,
  Tag,
  Space,
  Typography,
  Tooltip,
  Button,
} from "antd";

import type { WorkPlan, PlanStatus } from "../../types/agent";

const { Text } = Typography;

interface WorkPlanCardProps {
  workPlan: WorkPlan;
}

const statusConfig: Record<
  PlanStatus,
  { color: string; icon: React.ReactNode; label: string }
> = {
  planning: {
    color: "default",
    icon: <ClockCircleOutlined />,
    label: "Planning",
  },
  in_progress: {
    color: "processing",
    icon: <LoadingOutlined />,
    label: "In Progress",
  },
  completed: {
    color: "success",
    icon: <CheckCircleOutlined />,
    label: "Completed",
  },
  failed: { color: "error", icon: <CloseCircleOutlined />, label: "Failed" },
};

const getStepStatus = (
  stepNumber: number,
  currentIndex: number,
  planStatus: PlanStatus
): "completed" | "running" | "pending" | "failed" => {
  if (planStatus === "failed") return "failed";
  if (planStatus === "completed") return "completed";
  if (stepNumber < currentIndex) return "completed";
  if (stepNumber === currentIndex) return "running";
  return "pending";
};

const stepStatusConfig: Record<
  "completed" | "running" | "pending" | "failed",
  { icon: React.ReactNode; class: string }
> = {
  completed: { icon: <CheckCircleOutlined />, class: "step-completed" },
  running: { icon: <LoadingOutlined />, class: "step-running" },
  pending: { icon: <ClockCircleOutlined />, class: "step-pending" },
  failed: { icon: <CloseCircleOutlined />, class: "step-failed" },
};

export const WorkPlanCard = memo<WorkPlanCardProps>(({ workPlan }) => {
  const [collapsed, setCollapsed] = useState(false);
  const status = statusConfig[workPlan.status];
  const progressPercentage =
    workPlan.steps.length > 0
      ? Math.round((workPlan.current_step_index / workPlan.steps.length) * 100)
      : 0;

  if (workPlan.steps.length === 0) {
    return (
      <Card size="small" style={{ marginBottom: 16 }}>
        <Space orientation="vertical" size="small" style={{ width: "100%" }}>
          <Space>
            <ThunderboltOutlined />
            <Text strong>Work Plan</Text>
            <Tag color={status.color} icon={status.icon}>
              {status.label}
            </Tag>
          </Space>
          <Text type="secondary">No steps in this plan</Text>
        </Space>
      </Card>
    );
  }

  return (
    <Card
      size="small"
      style={{ marginBottom: 16 }}
      title={
        <Space>
          <ThunderboltOutlined />
          <Text strong>Work Plan</Text>
          <Tag color={status.color} icon={status.icon}>
            {status.label}
          </Tag>
          {workPlan.workflow_pattern_id && (
            <Tooltip title={`Pattern: ${workPlan.workflow_pattern_id}`}>
              <Tag color="blue">Pattern Matched</Tag>
            </Tooltip>
          )}
          <Text type="secondary">{progressPercentage}%</Text>
        </Space>
      }
      extra={
        <Button
          type="link"
          onClick={() => setCollapsed(!collapsed)}
          style={{ fontSize: 12 }}
          aria-label={collapsed ? "Expand" : "Collapse"}
        >
          {collapsed ? <CaretRightOutlined /> : <CaretDownOutlined />}
        </Button>
      }
    >
      <Collapse
        ghost
        activeKey={!collapsed ? "steps" : undefined}
        items={[
          {
            key: "steps",
            children: (
              <Space
                orientation="vertical"
                size="small"
                style={{ width: "100%" }}
              >
                {/* Progress Bar */}
                <Progress
                  percent={progressPercentage}
                  status={
                    workPlan.status === "failed"
                      ? "exception"
                      : workPlan.status === "completed"
                      ? "success"
                      : "active"
                  }
                  size="small"
                  className="progress-bar"
                />

                {/* Steps List */}
                <Space
                  orientation="vertical"
                  size="small"
                  style={{ width: "100%" }}
                >
                  {workPlan.steps.map((step) => {
                    const stepStatus = getStepStatus(
                      step.step_number,
                      workPlan.current_step_index,
                      workPlan.status
                    );
                    const config = stepStatusConfig[stepStatus];

                    return (
                      <div
                        key={step.step_number}
                        data-step-number={step.step_number}
                        className={`work-plan-step ${config.class}`}
                        style={{
                          padding: 8,
                          borderRadius: 4,
                          backgroundColor:
                            stepStatus === "completed"
                              ? "#f6ffed"
                              : stepStatus === "running"
                              ? "#e6f7ff"
                              : stepStatus === "failed"
                              ? "#fff1f0"
                              : "#f5f5f5",
                          border: `1px solid ${
                            stepStatus === "completed"
                              ? "#b7eb8f"
                              : stepStatus === "running"
                              ? "#91d5ff"
                              : stepStatus === "failed"
                              ? "#ffccc7"
                              : "#d9d9d9"
                          }`,
                        }}
                      >
                        <Space
                          orientation="vertical"
                          size="small"
                          style={{ width: "100%" }}
                        >
                          {/* Step Header */}
                          <Space>
                            <span
                              style={{
                                color:
                                  stepStatus === "completed"
                                    ? "#52c41a"
                                    : stepStatus === "failed"
                                    ? "#ff4d4f"
                                    : undefined,
                              }}
                            >
                              {config.icon}
                            </span>
                            <Text strong>
                              Step {step.step_number + 1}: {step.description}
                            </Text>
                          </Space>

                          {/* Step Details */}
                          <Space wrap>
                            {step.required_tools.map((tool) => (
                              <Tag
                                key={tool}
                                color="blue"
                                style={{ fontSize: 11 }}
                              >
                                {tool}
                              </Tag>
                            ))}
                            <Text type="secondary" style={{ fontSize: 11 }}>
                              Expected: {step.expected_output}
                            </Text>
                          </Space>

                          {/* Dependencies */}
                          {step.dependencies.length > 0 ? (
                            <Text type="secondary" style={{ fontSize: 11 }}>
                              Depends on: Steps{" "}
                              {step.dependencies.map((d) => d + 1).join(", ")}
                            </Text>
                          ) : (
                            <Text type="secondary" style={{ fontSize: 11 }}>
                              No dependencies
                            </Text>
                          )}
                        </Space>
                      </div>
                    );
                  })}
                </Space>
              </Space>
            ),
          },
        ]}
      />
    </Card>
  );
});

WorkPlanCard.displayName = 'WorkPlanCard';

export default WorkPlanCard;
