export type ManagementCategory = 'models' | 'skills' | 'plugins' | 'agents';

export interface ManagementItem {
  id: string;
  name: string;
  description: string;
  status: string;
  statusLabel: string;
  meta: string;
  scope: string;
  usedBy: number;
  tags: string[];
  provider?: string;
  publisher?: string;
  owner?: string;
  modelId?: string;
  latency?: string;
  spend?: string;
  success?: string;
  fallback?: string;
  temperature?: string;
  timeout?: string;
  budget?: string;
  updated?: string;
  version?: string;
  model?: string;
  tools?: string[];
  instructions?: string;
  permissions?: string[];
  events?: string;
  role?: string;
  autonomy?: string;
  memory?: string;
  skills?: string[];
  plugins?: string[];
}

export const managementCatalog: Record<ManagementCategory, ManagementItem[]> = {
  models: [
    {
      id: 'gpt-55',
      name: 'GPT-5.5',
      description: 'Primary reasoning model for planning, execution, and review.',
      status: 'healthy',
      statusLabel: 'Healthy',
      provider: 'OpenAI',
      modelId: 'gpt-5.5',
      meta: 'Default · 128k context',
      scope: 'Workspace',
      usedBy: 6,
      latency: '1.8s median',
      spend: '$184.20 this month',
      success: '99.2%',
      fallback: 'Claude Sonnet 4.5',
      temperature: '0.2',
      timeout: '120 seconds',
      budget: '$500 / month',
      tags: ['Reasoning', 'Tools', 'Vision'],
    },
    {
      id: 'claude-sonnet',
      name: 'Claude Sonnet 4.5',
      description: 'Balanced long-context model for synthesis and code review.',
      status: 'healthy',
      statusLabel: 'Healthy',
      provider: 'Anthropic',
      modelId: 'claude-sonnet-4-5',
      meta: 'Fallback · 200k context',
      scope: 'Workspace',
      usedBy: 4,
      latency: '2.1s median',
      spend: '$96.40 this month',
      success: '98.7%',
      fallback: 'Gemini 2.5 Pro',
      temperature: '0.3',
      timeout: '120 seconds',
      budget: '$300 / month',
      tags: ['Long context', 'Code', 'Vision'],
    },
    {
      id: 'gemini-pro',
      name: 'Gemini 2.5 Pro',
      description: 'Multimodal model for large source sets and visual analysis.',
      status: 'attention',
      statusLabel: 'Budget alert',
      provider: 'Google',
      modelId: 'gemini-2.5-pro',
      meta: 'Analysis · 1m context',
      scope: 'Product Strategy',
      usedBy: 2,
      latency: '2.6s median',
      spend: '$142.80 this month',
      success: '97.9%',
      fallback: 'GPT-5.5',
      temperature: '0.2',
      timeout: '180 seconds',
      budget: '$150 / month',
      tags: ['Multimodal', 'Long context'],
    },
    {
      id: 'local-coder',
      name: 'Qwen Coder Local',
      description: 'Private local inference for code classification and indexing.',
      status: 'offline',
      statusLabel: 'Offline',
      provider: 'Local runtime',
      modelId: 'qwen3-coder-30b',
      meta: 'Private · 32k context',
      scope: 'Desktop Client',
      usedBy: 1,
      latency: 'Unavailable',
      spend: 'Local compute',
      success: '94.5%',
      fallback: 'GPT-5.5',
      temperature: '0.1',
      timeout: '90 seconds',
      budget: 'No API budget',
      tags: ['Private', 'Code'],
    },
  ],
  skills: [
    {
      id: 'competitive-research',
      name: 'Competitive research',
      description: 'Builds an evidence-backed market brief from verified sources.',
      status: 'active',
      statusLabel: 'Published',
      meta: 'v2.4 · 6 tools',
      scope: 'Workspace',
      usedBy: 3,
      owner: 'Strategy Ops',
      updated: '2 days ago',
      version: '2.4.0',
      success: '96% validation pass',
      model: 'GPT-5.5',
      tools: ['Web search', 'Browser', 'Documents', 'Citations'],
      tags: ['Research', 'Brief'],
      instructions: 'Clarify the market and decision first. Gather primary sources, compare claims, and preserve a traceable citation for every material conclusion.',
    },
    {
      id: 'document-synthesis',
      name: 'Document synthesis',
      description: 'Turns mixed files and notes into a structured decision document.',
      status: 'active',
      statusLabel: 'Published',
      meta: 'v3.1 · 4 tools',
      scope: 'Workspace',
      usedBy: 5,
      owner: 'Knowledge Team',
      updated: 'Yesterday',
      version: '3.1.2',
      success: '98% validation pass',
      model: 'Claude Sonnet 4.5',
      tools: ['Documents', 'PDF', 'Memory', 'Artifacts'],
      tags: ['Synthesis', 'Documents'],
      instructions: 'Inventory sources, identify agreements and conflicts, and produce an answer-first document with provenance and unresolved questions.',
    },
    {
      id: 'code-review',
      name: 'Code review',
      description: 'Reviews diffs for correctness, regressions, and missing tests.',
      status: 'draft',
      statusLabel: 'Draft',
      meta: 'v1.8 · 7 tools',
      scope: 'Desktop Client',
      usedBy: 2,
      owner: 'Developer Experience',
      updated: '4 hours ago',
      version: '1.8.0-rc2',
      success: '91% validation pass',
      model: 'GPT-5.5',
      tools: ['Git diff', 'Code graph', 'Terminal', 'Tests'],
      tags: ['Code', 'Review'],
      instructions: 'Inspect the requested change and its blast radius. Report only actionable findings with severity, evidence, and a concrete repair path.',
    },
    {
      id: 'ui-audit',
      name: 'UI quality audit',
      description: 'Checks rendered interfaces for hierarchy, states, and accessibility.',
      status: 'attention',
      statusLabel: 'Test failed',
      meta: 'v1.3 · 3 tools',
      scope: 'Workspace',
      usedBy: 1,
      owner: 'Design Systems',
      updated: '18 minutes ago',
      version: '1.3.4',
      success: '84% validation pass',
      model: 'Gemini 2.5 Pro',
      tools: ['Browser', 'Screenshots', 'Accessibility tree'],
      tags: ['Design', 'QA'],
      instructions: 'Inspect the live interface at target viewports. Prioritize layout and interaction defects, attach visual evidence, and finish with a pass or fail verdict.',
    },
  ],
  plugins: [
    {
      id: 'github',
      name: 'GitHub',
      description: 'Repositories, pull requests, issues, actions, and review threads.',
      status: 'connected',
      statusLabel: 'Connected',
      meta: 'v4.8.1 · 12 tools',
      scope: 'Workspace',
      usedBy: 4,
      publisher: 'MemStack verified',
      updated: 'Auto-update on',
      permissions: ['Read repository metadata', 'Read and write pull requests', 'Read Actions status'],
      tools: ['Browse repository', 'Create branch', 'Open pull request', 'Review checks'],
      events: '42 actions this week',
      tags: ['Code', 'Verified'],
    },
    {
      id: 'slack',
      name: 'Slack',
      description: 'Search channels, summarize threads, and deliver approved updates.',
      status: 'connected',
      statusLabel: 'Connected',
      meta: 'v2.6.0 · 8 tools',
      scope: 'Workspace',
      usedBy: 3,
      publisher: 'MemStack verified',
      updated: 'Auto-update on',
      permissions: ['Read selected channels', 'Post with approval', 'Read user directory'],
      tools: ['Search messages', 'Read thread', 'Draft update', 'Post approved update'],
      events: '18 actions this week',
      tags: ['Communication', 'Verified'],
    },
    {
      id: 'figma',
      name: 'Figma',
      description: 'Inspect design files, components, variables, and review context.',
      status: 'update',
      statusLabel: 'Update available',
      meta: 'v1.9.2 → 2.0.0',
      scope: 'Design Systems',
      usedBy: 2,
      publisher: 'Figma',
      updated: 'Manual updates',
      permissions: ['Read selected files', 'Read comments', 'Create draft frames'],
      tools: ['Inspect selection', 'Read variables', 'Capture frame', 'Create draft'],
      events: '11 actions this week',
      tags: ['Design', 'Update'],
    },
    {
      id: 'drive',
      name: 'Google Drive',
      description: 'Find and read team documents with inherited Drive permissions.',
      status: 'available',
      statusLabel: 'Not installed',
      meta: 'v3.2.0 · 9 tools',
      scope: 'Marketplace',
      usedBy: 0,
      publisher: 'Google',
      updated: 'Verified 5 days ago',
      permissions: ['Read selected files', 'Search permitted folders', 'Create approved exports'],
      tools: ['Search files', 'Read document', 'List folder', 'Create export'],
      events: 'No activity',
      tags: ['Documents', 'Verified'],
    },
  ],
  agents: [
    {
      id: 'atlas',
      name: 'Atlas',
      description: 'General work agent for research, synthesis, and decision support.',
      status: 'active',
      statusLabel: 'Active',
      meta: 'GPT-5.5 · 5 skills',
      scope: 'Workspace',
      usedBy: 18,
      role: 'General work agent',
      model: 'GPT-5.5',
      fallback: 'Claude Sonnet 4.5',
      autonomy: 'Plan approval required',
      memory: 'Project-scoped memory',
      skills: ['Competitive research', 'Document synthesis', 'Meeting brief', 'Decision memo', 'Source verification'],
      plugins: ['Slack', 'Google Drive'],
      owner: 'Strategy Ops',
      success: '94% tasks accepted',
      tags: ['Work', 'Default'],
    },
    {
      id: 'dev',
      name: 'Dev',
      description: 'Coding agent for isolated implementation, tests, and code review.',
      status: 'active',
      statusLabel: 'Active',
      meta: 'GPT-5.5 · 6 skills',
      scope: 'Desktop Client',
      usedBy: 31,
      role: 'Software engineering agent',
      model: 'GPT-5.5',
      fallback: 'Claude Sonnet 4.5',
      autonomy: 'Approve before write',
      memory: 'Repository-scoped memory',
      skills: ['Code exploration', 'Implementation', 'Code review', 'Test generation', 'Debugging', 'Release notes'],
      plugins: ['GitHub'],
      owner: 'Developer Experience',
      success: '91% PRs merged',
      tags: ['Code', 'Worktree'],
    },
    {
      id: 'research-analyst',
      name: 'Research analyst',
      description: 'Focused analyst for market, customer, and policy research.',
      status: 'active',
      statusLabel: 'Active',
      meta: 'Claude Sonnet 4.5 · 3 skills',
      scope: 'Product Strategy',
      usedBy: 12,
      role: 'Evidence and market analyst',
      model: 'Claude Sonnet 4.5',
      fallback: 'GPT-5.5',
      autonomy: 'Read-only without approval',
      memory: 'Project-scoped memory',
      skills: ['Competitive research', 'Source verification', 'Document synthesis'],
      plugins: ['Google Drive', 'Slack'],
      owner: 'Product Strategy',
      success: '97% briefs accepted',
      tags: ['Research', 'Read-only'],
    },
    {
      id: 'review-guardian',
      name: 'Review guardian',
      description: 'Independent reviewer for plans, code changes, and final artifacts.',
      status: 'paused',
      statusLabel: 'Paused',
      meta: 'Gemini 2.5 Pro · 2 skills',
      scope: 'Workspace',
      usedBy: 7,
      role: 'Independent quality reviewer',
      model: 'Gemini 2.5 Pro',
      fallback: 'GPT-5.5',
      autonomy: 'Review only',
      memory: 'Task-only memory',
      skills: ['Code review', 'UI quality audit'],
      plugins: ['GitHub', 'Figma'],
      owner: 'Quality Systems',
      success: '89% findings confirmed',
      tags: ['Review', 'Independent'],
    },
  ],
};
