import { PLUGIN_MODULE_CATALOG_V2, RuntimeV2Error, type ContextV2, type PluginDefinitionV2 } from '@agistack/plugin-runtime';
import type { DesktopRuntimeConfig } from '../types';
import type { TenantAdminRequestOptions } from '../features/tenant-admin/tenantAdminHttp';
import type { TenantGovernanceClient, TenantGovernanceSnapshot, TenantInvitation } from '../features/tenant-admin/tenantGovernanceClient';
import type { DesktopRendererGenerationActionsV2, DesktopRendererServiceOperationLeaseAdmissionV2 } from './desktopRendererGenerationContextV2';
import { createDesktopTenantGovernanceHttpProjectionV2 } from './desktopTenantGovernanceHttpProjectionV2';
import { freezeTenantGovernanceConfigV2, prepareTenantGovernanceInputV2, prepareTenantGovernanceInviteV2, prepareTenantGovernanceMemberV2, prepareTenantGovernanceRoleV2, requireTenantGovernanceInvitationV2, requireTenantGovernanceSnapshotV2, type DesktopTenantGovernanceInputV2, type DesktopTenantGovernanceInviteInputV2, type DesktopTenantGovernanceMemberInputV2, type DesktopTenantGovernanceRoleInputV2 } from './desktopTenantGovernanceOperationContractV2';

export const DESKTOP_TENANT_GOVERNANCE_AUTHORITY_MODULE_REF_V2 = 'builtin://memstack/desktop/tenant-governance-authority';
export const DESKTOP_TENANT_GOVERNANCE_AUTHORITY_SERVICE_V2 = 'service:desktop-renderer.tenant-governance-authority';
export const DESKTOP_TENANT_GOVERNANCE_AUTHORITY_VERSION_V2 = '1.0.0';
export interface DesktopTenantGovernanceAuthorityServiceV2 { bindOperation(config: DesktopRuntimeConfig): TenantGovernanceClient }
export interface DesktopTenantGovernanceOperationsV2 { loadTenantGovernance(input: DesktopTenantGovernanceInputV2): Promise<TenantGovernanceSnapshot>; inviteTenantMember(input: DesktopTenantGovernanceInviteInputV2): Promise<TenantInvitation>; changeTenantMemberRole(input: DesktopTenantGovernanceRoleInputV2): Promise<void>; removeTenantMember(input: DesktopTenantGovernanceMemberInputV2): Promise<void> }
type Rejection = Extract<DesktopRendererServiceOperationLeaseAdmissionV2<never>, { status: 'rejected' }> | Readonly<{ reasonCode: 'desktop_renderer_generation_actions_unavailable'; runtimeCode?: undefined }>;
export class DesktopTenantGovernanceAuthorityUnavailableErrorV2 extends Error { readonly reasonCode; readonly runtimeCode; constructor(rejection: Rejection) { super(rejection.reasonCode); this.name = 'DesktopTenantGovernanceAuthorityUnavailableErrorV2'; this.reasonCode = rejection.reasonCode; this.runtimeCode = rejection.runtimeCode; } }
export function applyDesktopTenantGovernanceAuthorityV2(context: ContextV2, config: Readonly<Record<string, unknown>>): void { if (Object.keys(config).length !== 1 || config.strategy !== 'desktop-api-fetch') throw new RuntimeV2Error('desktop_tenant_governance_authority_config_invalid', 'desktop tenant governance authority requires desktop-api-fetch strategy'); context.provide(DESKTOP_TENANT_GOVERNANCE_AUTHORITY_SERVICE_V2, Object.freeze({ bindOperation: createDesktopTenantGovernanceHttpProjectionV2 })); }
export const desktopTenantGovernanceAuthorityDefinitionV2: PluginDefinitionV2 = Object.freeze({ moduleRef: DESKTOP_TENANT_GOVERNANCE_AUTHORITY_MODULE_REF_V2, contractDigest: generatedDigest(), apply: applyDesktopTenantGovernanceAuthorityV2 });
export function createDesktopTenantGovernanceOperationsV2(resolve: () => DesktopRendererGenerationActionsV2 | null): DesktopTenantGovernanceOperationsV2 { return Object.freeze({
  loadTenantGovernance(input: DesktopTenantGovernanceInputV2) { const p = prepareTenantGovernanceInputV2(input); return run(resolve, p, (a) => a.load(p.scope, options(p.signal)).then((v) => requireTenantGovernanceSnapshotV2(v, p.scope))); },
  inviteTenantMember(input: DesktopTenantGovernanceInviteInputV2) { const p = prepareTenantGovernanceInviteV2(input); return run(resolve, p, (a) => a.invite(p.scope, p.invitation, options(p.signal)).then((v) => requireTenantGovernanceInvitationV2(v, p.scope.tenantId))); },
  changeTenantMemberRole(input: DesktopTenantGovernanceRoleInputV2) { const p = prepareTenantGovernanceRoleV2(input); return run(resolve, p, (a) => a.changeRole(p.scope, p.userId, p.role, options(p.signal))); },
  removeTenantMember(input: DesktopTenantGovernanceMemberInputV2) { const p = prepareTenantGovernanceMemberV2(input); return run(resolve, p, (a) => a.removeMember(p.scope, p.userId, options(p.signal))); },
}); }
export function createDesktopTenantGovernanceClientV2(operations: DesktopTenantGovernanceOperationsV2, config: DesktopRuntimeConfig): TenantGovernanceClient { const frozen = freezeTenantGovernanceConfigV2(config); return Object.freeze({ load: (scope, request) => operations.loadTenantGovernance({ config: frozen, scope, ...(request?.signal === undefined ? {} : { signal: request.signal }) }), invite: (scope, invitation, request) => operations.inviteTenantMember({ config: frozen, scope, invitation, ...(request?.signal === undefined ? {} : { signal: request.signal }) }), changeRole: (scope, userId, role, request) => operations.changeTenantMemberRole({ config: frozen, scope, userId, role, ...(request?.signal === undefined ? {} : { signal: request.signal }) }), removeMember: (scope, userId, request) => operations.removeTenantMember({ config: frozen, scope, userId, ...(request?.signal === undefined ? {} : { signal: request.signal }) }) }); }
async function run<T>(resolve: () => DesktopRendererGenerationActionsV2 | null, prepared: DesktopTenantGovernanceInputV2, operation: (authority: TenantGovernanceClient) => Promise<T>): Promise<T> { const actions = resolve(); if (!actions) throw new DesktopTenantGovernanceAuthorityUnavailableErrorV2({ reasonCode: 'desktop_renderer_generation_actions_unavailable' }); const admission = await actions.acquireServiceOperationLease<DesktopTenantGovernanceAuthorityServiceV2>({ service: DESKTOP_TENANT_GOVERNANCE_AUTHORITY_SERVICE_V2, version: DESKTOP_TENANT_GOVERNANCE_AUTHORITY_VERSION_V2, scope: Object.freeze({ kind: 'tenant', tenant_id: prepared.scope.tenantId }) }); if (admission.status === 'rejected') throw new DesktopTenantGovernanceAuthorityUnavailableErrorV2(admission); let failed = false; let active = true; try { return await admission.useService(async (candidate) => { if (!record(candidate) || Object.keys(candidate).length !== 1 || typeof candidate.bindOperation !== 'function') throw invalidService(); const raw = candidate.bindOperation(prepared.config); if (!record(raw) || Object.keys(raw).length !== 4 || typeof raw.load !== 'function' || typeof raw.invite !== 'function' || typeof raw.changeRole !== 'function' || typeof raw.removeMember !== 'function') throw invalidService(); const authority = Object.freeze({ load: (...args: Parameters<TenantGovernanceClient['load']>) => { assertActive(active); return raw.load(...args); }, invite: (...args: Parameters<TenantGovernanceClient['invite']>) => { assertActive(active); return raw.invite(...args); }, changeRole: (...args: Parameters<TenantGovernanceClient['changeRole']>) => { assertActive(active); return raw.changeRole(...args); }, removeMember: (...args: Parameters<TenantGovernanceClient['removeMember']>) => { assertActive(active); return raw.removeMember(...args); } }); const result = await operation(authority); assertActive(active); return result; }); } catch (error) { failed = true; throw error; } finally { active = false; try { await admission.release(); } catch (error) { if (!failed) throw error; } } }
function options(signal?: AbortSignal): TenantAdminRequestOptions | undefined { return signal === undefined ? undefined : Object.freeze({ signal }); }
function assertActive(active: boolean) { if (!active) throw new RuntimeV2Error('desktop_tenant_governance_operation_released', 'desktop tenant governance operation released'); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function invalidService() { return new RuntimeV2Error('desktop_tenant_governance_service_invalid', 'desktop tenant governance authority service invalid'); }
function generatedDigest() { const entry = PLUGIN_MODULE_CATALOG_V2.modules.find((item) => item.module_ref === DESKTOP_TENANT_GOVERNANCE_AUTHORITY_MODULE_REF_V2); if (!entry) throw new RuntimeV2Error('desktop_tenant_governance_authority_catalog_missing', 'desktop tenant governance authority absent from catalog'); return entry.contract_digest; }
