allowBuilds:
  '@modelcontextprotocol/ext-apps': false
  '@scarf/scarf': false
  core-js: true
  esbuild: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@modelcontextprotocol/ext-apps'
  - '@scarf/scarf'

onlyBuiltDependencies:
  - core-js
  - electron
  - esbuild
  - unrs-resolver
